// gen-defaults reads format_contract_proven.json and emits rive/gen_defaults.go
// with per-type ApplyDefaults() methods and New*() constructors.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type orderConstraint struct {
	Before int `json:"before"`
	After  int `json:"after"`
}

type contractEntry struct {
	Type             string                 `json:"type"`
	Proven           bool                   `json:"proven"`
	RequiredDefaults map[string]interface{} `json:"required_defaults"`
	ToCRequiredKeys  []int                  `json:"toc_required_keys"`
	ToCOrdering      []orderConstraint      `json:"toc_ordering"`
}

type contract struct {
	WasmVersion string          `json:"wasm_version"`
	Entries     []contractEntry `json:"entries"`
}

// propInfo maps a JSON property name to its Go field name and type.
// Properties absent from this map are skipped with a warning.
type propInfo struct {
	field  string
	goType string
}

var propMap = map[string]propInfo{
	"blendModeValue":   {"BlendModeValue", "uint64"},
	"fractionalWidth":  {"FractionalWidth", "float64"},
	"fractionalHeight": {"FractionalHeight", "float64"},
	"opacity":          {"Opacity", "float64"},
	"scaleX":           {"ScaleX", "float64"},
	"scaleY":           {"ScaleY", "float64"},
	"isVisible":        {"IsVisible", "bool"},
	"thickness":        {"Thickness", "float64"},
	"fps":              {"Fps", "uint64"},
	"speed":            {"Speed", "float64"},
	"originX":          {"OriginX", "float64"},
	"originY":          {"OriginY", "float64"},
	"linkCornerRadius": {"LinkCornerRadius", "bool"},
}

func main() {
	contractPath := flag.String("contract", "format_contract_proven.json", "path to proven contract JSON")
	outPath := flag.String("out", "gen_defaults.go", "output file path")
	pkg := flag.String("package", "rive", "Go package name for generated file")
	typesOut := flag.String("types-out", "", "path for types list sidecar (default: <out-dir>/gen_defaults_types.txt)")
	tocRulesOut := flag.String("toc-out", "", "path for ToC rules file (default: <out-dir>/gen_toc_rules.go)")
	flag.Parse()

	data, err := os.ReadFile(*contractPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-defaults: read contract: %v\n", err)
		os.Exit(1)
	}

	var c contract
	if err := json.Unmarshal(data, &c); err != nil {
		fmt.Fprintf(os.Stderr, "gen-defaults: parse contract: %v\n", err)
		os.Exit(1)
	}

	src, typeNames, err := generate(*pkg, *contractPath, c)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-defaults: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(*outPath, src, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "gen-defaults: write %s: %v\n", *outPath, err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "gen-defaults: wrote %s\n", *outPath)

	// Write the types sidecar.
	tp := *typesOut
	if tp == "" {
		tp = filepath.Join(filepath.Dir(*outPath), "gen_defaults_types.txt")
	}
	typesContent := strings.Join(typeNames, "\n") + "\n"
	if err := os.WriteFile(tp, []byte(typesContent), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "gen-defaults: write %s: %v\n", tp, err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "gen-defaults: wrote %s (%d types)\n", tp, len(typeNames))

	// Write the ToC rules file.
	tocSrc, err := generateToCRules(*pkg, *contractPath, c)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-defaults: generateToCRules: %v\n", err)
		os.Exit(1)
	}
	tocPath := *tocRulesOut
	if tocPath == "" {
		tocPath = filepath.Join(filepath.Dir(*outPath), "gen_toc_rules.go")
	}
	if err := os.WriteFile(tocPath, tocSrc, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "gen-defaults: write %s: %v\n", tocPath, err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "gen-defaults: wrote %s\n", tocPath)
}

func generate(pkg, contractPath string, c contract) ([]byte, []string, error) {
	var buf bytes.Buffer
	var typeNames []string

	fmt.Fprintf(&buf, "// Code generated by gen-defaults. DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "// Source: %s (wasm: %s)\n", contractPath, c.WasmVersion)
	fmt.Fprintf(&buf, "package %s\n\n", pkg)

	wrote := 0
	for _, entry := range c.Entries {
		if !entry.Proven || len(entry.RequiredDefaults) == 0 {
			continue
		}

		type resolvedProp struct {
			jsonName string
			info     propInfo
			rawVal   interface{}
		}
		var props []resolvedProp
		for jsonName, rawVal := range entry.RequiredDefaults {
			info, ok := propMap[jsonName]
			if !ok {
				fmt.Fprintf(os.Stderr, "gen-defaults: %s.%s: no Go field mapping — skipping\n", entry.Type, jsonName)
				continue
			}
			props = append(props, resolvedProp{jsonName, info, rawVal})
		}
		if len(props) == 0 {
			continue
		}
		sort.Slice(props, func(i, j int) bool { return props[i].info.field < props[j].info.field })

		typeName := entry.Type
		lowerType := strings.ToLower(typeName[:1]) + typeName[1:]
		structName := lowerType + "Defaults"
		varName := typeName + "Defaults"

		fmt.Fprintf(&buf, "type %s struct {\n", structName)
		for _, p := range props {
			fmt.Fprintf(&buf, "\t%s %s\n", p.info.field, p.info.goType)
		}
		fmt.Fprintf(&buf, "}\n\n")

		fmt.Fprintf(&buf, "// %s holds required runtime defaults for %s.\n", varName, typeName)
		fmt.Fprintf(&buf, "var %s = %s{\n", varName, structName)
		for _, p := range props {
			lit, err := formatLiteral(p.info.goType, p.rawVal)
			if err != nil {
				return nil, nil, fmt.Errorf("%s.%s: %w", typeName, p.jsonName, err)
			}
			fmt.Fprintf(&buf, "\t%s: %s,\n", p.info.field, lit)
		}
		fmt.Fprintf(&buf, "}\n\n")

		fmt.Fprintf(&buf, "// ApplyDefaults sets required runtime defaults on %s.\n", typeName)
		fmt.Fprintf(&buf, "func (x *%s) ApplyDefaults() {\n", typeName)
		for _, p := range props {
			fmt.Fprintf(&buf, "\tx.%s = %s.%s\n", p.info.field, varName, p.info.field)
		}
		fmt.Fprintf(&buf, "}\n\n")

		fmt.Fprintf(&buf, "// New%s creates a %s with required defaults applied.\n", typeName, typeName)
		fmt.Fprintf(&buf, "func New%s() *%s {\n", typeName, typeName)
		fmt.Fprintf(&buf, "\tx := &%s{}\n", typeName)
		fmt.Fprintf(&buf, "\tx.ApplyDefaults()\n")
		fmt.Fprintf(&buf, "\treturn x\n")
		fmt.Fprintf(&buf, "}\n\n")

		typeNames = append(typeNames, typeName)
		wrote++
	}

	if wrote == 0 {
		buf.Reset()
		fmt.Fprintf(&buf, "// Code generated by gen-defaults. DO NOT EDIT.\n")
		fmt.Fprintf(&buf, "// No types with required defaults found in contract.\n\n")
		fmt.Fprintf(&buf, "package %s\n", pkg)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, nil, fmt.Errorf("gofmt: %w\nraw:\n%s", err, buf.String())
	}
	return formatted, typeNames, nil
}

// generateToCRules emits gen_toc_rules.go with per-type *ToC() functions
// and an objectRequiredToCKeys dispatch switch.
func generateToCRules(pkg, contractPath string, c contract) ([]byte, error) {
	// Collect types that have non-empty ToCRequiredKeys.
	type tocEntry struct {
		typeName string
		keys     []int
	}
	var entries []tocEntry
	for _, e := range c.Entries {
		if !e.Proven || len(e.ToCRequiredKeys) == 0 {
			continue
		}
		keys := make([]int, len(e.ToCRequiredKeys))
		copy(keys, e.ToCRequiredKeys)
		sort.Ints(keys)
		entries = append(entries, tocEntry{e.Type, keys})
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by gen-defaults. DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "// Source: %s (wasm: %s)\n", contractPath, c.WasmVersion)
	fmt.Fprintf(&buf, "package %s\n\n", pkg)

	// Emit per-type ToC functions.
	for _, te := range entries {
		keyLits := make([]string, len(te.keys))
		for i, k := range te.keys {
			keyLits[i] = fmt.Sprintf("%d", k)
		}
		fmt.Fprintf(&buf, "// %sToC returns the required ToC property keys for %s.\n", te.typeName, te.typeName)
		fmt.Fprintf(&buf, "func %sToC() []uint32 {\n", te.typeName)
		fmt.Fprintf(&buf, "\treturn []uint32{%s}\n", strings.Join(keyLits, ", "))
		fmt.Fprintf(&buf, "}\n\n")
	}

	// Emit dispatch function.
	fmt.Fprintf(&buf, "// objectRequiredToCKeys returns the required ToC property keys for obj, or nil if none.\n")
	fmt.Fprintf(&buf, "func objectRequiredToCKeys(obj Object) []uint32 {\n")
	if len(entries) > 0 {
		fmt.Fprintf(&buf, "\tswitch obj.(type) {\n")
		for _, te := range entries {
			fmt.Fprintf(&buf, "\tcase *%s:\n", te.typeName)
			fmt.Fprintf(&buf, "\t\treturn %sToC()\n", te.typeName)
		}
		fmt.Fprintf(&buf, "\t}\n")
	}
	fmt.Fprintf(&buf, "\treturn nil\n")
	fmt.Fprintf(&buf, "}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt: %w\nraw:\n%s", err, buf.String())
	}
	return formatted, nil
}

// formatLiteral returns a Go literal string for a JSON-decoded value.
func formatLiteral(goType string, v interface{}) (string, error) {
	f, isFloat := v.(float64)
	b, isBool := v.(bool)

	switch goType {
	case "float64":
		if !isFloat {
			return "", fmt.Errorf("expected number, got %T", v)
		}
		if f == float64(int64(f)) {
			return fmt.Sprintf("%d.0", int64(f)), nil
		}
		return fmt.Sprintf("%g", f), nil
	case "uint64":
		if !isFloat {
			return "", fmt.Errorf("expected number, got %T", v)
		}
		return fmt.Sprintf("%d", uint64(f)), nil
	case "bool":
		if !isBool {
			return "", fmt.Errorf("expected bool, got %T", v)
		}
		if b {
			return "true", nil
		}
		return "false", nil
	}
	return "", fmt.Errorf("unknown goType %q", goType)
}
