// Code generated by rivegen. DO NOT EDIT.
package rive

// KeyboardInput (typeKey: 664)
type KeyboardInput struct {
	UserInput
	KeyType   uint64 `rive:"971,uint"`
	KeyPhase  uint64 `rive:"972,uint"`
	Modifiers uint64 `rive:"973,uint"`
}

func (o *KeyboardInput) TypeKey() uint32 { return 664 }

func (o *KeyboardInput) Properties() []Property {
	props := o.UserInput.Properties()
	if o.KeyType != ^uint64(0) {
		props = append(props, Property{Key: 971, Type: PropertyTypeUint, Value: o.KeyType})
	}
	if o.KeyPhase != 0 {
		props = append(props, Property{Key: 972, Type: PropertyTypeUint, Value: o.KeyPhase})
	}
	if o.Modifiers != 0 {
		props = append(props, Property{Key: 973, Type: PropertyTypeUint, Value: o.Modifiers})
	}
	return props
}

// SemanticInput (typeKey: 670)
type SemanticInput struct {
	UserInput
	ActionType uint64 `rive:"1010,uint"`
}

func (o *SemanticInput) TypeKey() uint32 { return 670 }

func (o *SemanticInput) Properties() []Property {
	props := o.UserInput.Properties()
	if o.ActionType != 0 {
		props = append(props, Property{Key: 1010, Type: PropertyTypeUint, Value: o.ActionType})
	}
	return props
}

// UserInput (typeKey: 663)
type UserInput struct {
}

func (o *UserInput) TypeKey() uint32 { return 663 }

func (o *UserInput) Properties() []Property {
	return nil
}
