// Code generated by rivegen. DO NOT EDIT.
package rive

// Text (typeKey: 134)
type Text struct {
	Drawable
	AlignValue         uint64  `rive:"281,uint"`
	SizingValue        uint64  `rive:"284,uint"`
	Width              float64 `rive:"285,float"`
	Height             float64 `rive:"286,float"`
	OverflowValue      uint64  `rive:"287,uint"`
	OriginX            float64 `rive:"366,float"`
	OriginY            float64 `rive:"367,float"`
	ParagraphSpacing   float64 `rive:"371,float"`
	OriginValue        uint64  `rive:"377,uint"`
	WrapValue          uint64  `rive:"683,uint"`
	VerticalAlignValue uint64  `rive:"685,uint"`
	FitFromBaseline    bool    `rive:"703,bool"`
	TextRunListSource  uint64  `rive:"932,uint"`
}

func (o *Text) TypeKey() uint32 { return 134 }

func (o *Text) Properties() []Property {
	props := o.Drawable.Properties()
	if o.AlignValue != 0 {
		props = append(props, Property{Key: 281, Type: PropertyTypeUint, Value: o.AlignValue})
	}
	if o.SizingValue != 0 {
		props = append(props, Property{Key: 284, Type: PropertyTypeUint, Value: o.SizingValue})
	}
	if o.Width != 0 {
		props = append(props, Property{Key: 285, Type: PropertyTypeFloat, Value: o.Width})
	}
	if o.Height != 0 {
		props = append(props, Property{Key: 286, Type: PropertyTypeFloat, Value: o.Height})
	}
	if o.OverflowValue != 0 {
		props = append(props, Property{Key: 287, Type: PropertyTypeUint, Value: o.OverflowValue})
	}
	if o.OriginX != 0 {
		props = append(props, Property{Key: 366, Type: PropertyTypeFloat, Value: o.OriginX})
	}
	if o.OriginY != 0 {
		props = append(props, Property{Key: 367, Type: PropertyTypeFloat, Value: o.OriginY})
	}
	if o.ParagraphSpacing != 0 {
		props = append(props, Property{Key: 371, Type: PropertyTypeFloat, Value: o.ParagraphSpacing})
	}
	if o.OriginValue != 0 {
		props = append(props, Property{Key: 377, Type: PropertyTypeUint, Value: o.OriginValue})
	}
	if o.WrapValue != 0 {
		props = append(props, Property{Key: 683, Type: PropertyTypeUint, Value: o.WrapValue})
	}
	if o.VerticalAlignValue != 0 {
		props = append(props, Property{Key: 685, Type: PropertyTypeUint, Value: o.VerticalAlignValue})
	}
	if !o.FitFromBaseline {
		props = append(props, Property{Key: 703, Type: PropertyTypeUint, Value: boolToUint64(o.FitFromBaseline)})
	}
	if o.TextRunListSource != ^uint64(0) {
		props = append(props, Property{Key: 932, Type: PropertyTypeUint, Value: o.TextRunListSource})
	}
	return props
}

// TextFollowPathModifier (typeKey: 547)
type TextFollowPathModifier struct {
	TextTargetModifier
	Radial   bool    `rive:"779,bool"`
	Orient   bool    `rive:"782,bool"`
	Start    float64 `rive:"783,float"`
	End      float64 `rive:"784,float"`
	Strength float64 `rive:"785,float"`
	Offset   float64 `rive:"786,float"`
}

func (o *TextFollowPathModifier) TypeKey() uint32 { return 547 }

func (o *TextFollowPathModifier) Properties() []Property {
	props := o.TextTargetModifier.Properties()
	if o.Radial {
		props = append(props, Property{Key: 779, Type: PropertyTypeUint, Value: boolToUint64(o.Radial)})
	}
	if !o.Orient {
		props = append(props, Property{Key: 782, Type: PropertyTypeUint, Value: boolToUint64(o.Orient)})
	}
	if o.Start != 0 {
		props = append(props, Property{Key: 783, Type: PropertyTypeFloat, Value: o.Start})
	}
	if o.End != 1 {
		props = append(props, Property{Key: 784, Type: PropertyTypeFloat, Value: o.End})
	}
	if o.Strength != 1 {
		props = append(props, Property{Key: 785, Type: PropertyTypeFloat, Value: o.Strength})
	}
	if o.Offset != 0 {
		props = append(props, Property{Key: 786, Type: PropertyTypeFloat, Value: o.Offset})
	}
	return props
}

// TextInput (typeKey: 569)
type TextInput struct {
	Drawable
	Text            string  `rive:"817,string"`
	SelectionRadius float64 `rive:"818,float"`
	Multiline       bool    `rive:"979,bool"`
}

func (o *TextInput) TypeKey() uint32 { return 569 }

func (o *TextInput) Properties() []Property {
	props := o.Drawable.Properties()
	if o.Text != "" {
		props = append(props, Property{Key: 817, Type: PropertyTypeString, Value: o.Text})
	}
	if o.SelectionRadius != 5 {
		props = append(props, Property{Key: 818, Type: PropertyTypeFloat, Value: o.SelectionRadius})
	}
	if !o.Multiline {
		props = append(props, Property{Key: 979, Type: PropertyTypeUint, Value: boolToUint64(o.Multiline)})
	}
	return props
}

// TextInputCursor (typeKey: 571)
type TextInputCursor struct {
	TextInputDrawable
}

func (o *TextInputCursor) TypeKey() uint32 { return 571 }

func (o *TextInputCursor) Properties() []Property {
	return o.TextInputDrawable.Properties()
}

// TextInputDrawable (typeKey: 570) [abstract]
type TextInputDrawable struct {
	Drawable
}

func (o *TextInputDrawable) Properties() []Property {
	return o.Drawable.Properties()
}

// TextInputSelectedText (typeKey: 575)
type TextInputSelectedText struct {
	TextInputDrawable
}

func (o *TextInputSelectedText) TypeKey() uint32 { return 575 }

func (o *TextInputSelectedText) Properties() []Property {
	return o.TextInputDrawable.Properties()
}

// TextInputSelection (typeKey: 574)
type TextInputSelection struct {
	TextInputDrawable
}

func (o *TextInputSelection) TypeKey() uint32 { return 574 }

func (o *TextInputSelection) Properties() []Property {
	return o.TextInputDrawable.Properties()
}

// TextInputText (typeKey: 572)
type TextInputText struct {
	TextInputDrawable
}

func (o *TextInputText) TypeKey() uint32 { return 572 }

func (o *TextInputText) Properties() []Property {
	return o.TextInputDrawable.Properties()
}

// TextModifier (typeKey: 160) [abstract]
type TextModifier struct {
	Component
}

func (o *TextModifier) Properties() []Property {
	return o.Component.Properties()
}

// TextModifierGroup (typeKey: 159)
type TextModifierGroup struct {
	ContainerComponent
	X             float64 `rive:"322,float"`
	Y             float64 `rive:"323,float"`
	Opacity       float64 `rive:"324,float"`
	OriginX       float64 `rive:"328,float"`
	OriginY       float64 `rive:"329,float"`
	ScaleX        float64 `rive:"330,float"`
	ScaleY        float64 `rive:"331,float"`
	Rotation      float64 `rive:"332,float"`
	ModifierFlags uint64  `rive:"335,uint"`
}

func (o *TextModifierGroup) TypeKey() uint32 { return 159 }

func (o *TextModifierGroup) Properties() []Property {
	props := o.ContainerComponent.Properties()
	if o.X != 0 {
		props = append(props, Property{Key: 322, Type: PropertyTypeFloat, Value: o.X})
	}
	if o.Y != 0 {
		props = append(props, Property{Key: 323, Type: PropertyTypeFloat, Value: o.Y})
	}
	if o.Opacity != 1 {
		props = append(props, Property{Key: 324, Type: PropertyTypeFloat, Value: o.Opacity})
	}
	if o.OriginX != 0 {
		props = append(props, Property{Key: 328, Type: PropertyTypeFloat, Value: o.OriginX})
	}
	if o.OriginY != 0 {
		props = append(props, Property{Key: 329, Type: PropertyTypeFloat, Value: o.OriginY})
	}
	if o.ScaleX != 1 {
		props = append(props, Property{Key: 330, Type: PropertyTypeFloat, Value: o.ScaleX})
	}
	if o.ScaleY != 1 {
		props = append(props, Property{Key: 331, Type: PropertyTypeFloat, Value: o.ScaleY})
	}
	if o.Rotation != 0 {
		props = append(props, Property{Key: 332, Type: PropertyTypeFloat, Value: o.Rotation})
	}
	if o.ModifierFlags != 0 {
		props = append(props, Property{Key: 335, Type: PropertyTypeUint, Value: o.ModifierFlags})
	}
	return props
}

// TextModifierRange (typeKey: 158)
type TextModifierRange struct {
	ContainerComponent
	UnitsValue  uint64  `rive:"316,uint"`
	FalloffFrom float64 `rive:"317,float"`
	FalloffTo   float64 `rive:"318,float"`
	Offset      float64 `rive:"319,float"`
	TypeValue   uint64  `rive:"325,uint"`
	ModeValue   uint64  `rive:"326,uint"`
	ModifyFrom  float64 `rive:"327,float"`
	Clamp       bool    `rive:"333,bool"`
	Strength    float64 `rive:"334,float"`
	ModifyTo    float64 `rive:"336,float"`
	RunId       uint64  `rive:"378,uint"`
}

func (o *TextModifierRange) TypeKey() uint32 { return 158 }

func (o *TextModifierRange) Properties() []Property {
	props := o.ContainerComponent.Properties()
	if o.UnitsValue != 0 {
		props = append(props, Property{Key: 316, Type: PropertyTypeUint, Value: o.UnitsValue})
	}
	if o.FalloffFrom != 0 {
		props = append(props, Property{Key: 317, Type: PropertyTypeFloat, Value: o.FalloffFrom})
	}
	if o.FalloffTo != 1 {
		props = append(props, Property{Key: 318, Type: PropertyTypeFloat, Value: o.FalloffTo})
	}
	if o.Offset != 0 {
		props = append(props, Property{Key: 319, Type: PropertyTypeFloat, Value: o.Offset})
	}
	if o.TypeValue != 0 {
		props = append(props, Property{Key: 325, Type: PropertyTypeUint, Value: o.TypeValue})
	}
	if o.ModeValue != 0 {
		props = append(props, Property{Key: 326, Type: PropertyTypeUint, Value: o.ModeValue})
	}
	if o.ModifyFrom != 0 {
		props = append(props, Property{Key: 327, Type: PropertyTypeFloat, Value: o.ModifyFrom})
	}
	if o.Clamp {
		props = append(props, Property{Key: 333, Type: PropertyTypeUint, Value: boolToUint64(o.Clamp)})
	}
	if o.Strength != 1 {
		props = append(props, Property{Key: 334, Type: PropertyTypeFloat, Value: o.Strength})
	}
	if o.ModifyTo != 1 {
		props = append(props, Property{Key: 336, Type: PropertyTypeFloat, Value: o.ModifyTo})
	}
	if o.RunId != ^uint64(0) {
		props = append(props, Property{Key: 378, Type: PropertyTypeUint, Value: o.RunId})
	}
	return props
}

// TextShapeModifier (typeKey: 161) [abstract]
type TextShapeModifier struct {
	TextModifier
}

func (o *TextShapeModifier) Properties() []Property {
	return o.TextModifier.Properties()
}

// TextStyle (typeKey: 573)
type TextStyle struct {
	ContainerComponent
	FontSize      float64 `rive:"274,float"`
	FontAssetId   uint64  `rive:"279,uint"`
	LineHeight    float64 `rive:"370,float"`
	LetterSpacing float64 `rive:"390,float"`
}

func (o *TextStyle) TypeKey() uint32 { return 573 }

func (o *TextStyle) Properties() []Property {
	props := o.ContainerComponent.Properties()
	if o.FontSize != 12 {
		props = append(props, Property{Key: 274, Type: PropertyTypeFloat, Value: o.FontSize})
	}
	if o.FontAssetId != ^uint64(0) {
		props = append(props, Property{Key: 279, Type: PropertyTypeUint, Value: o.FontAssetId})
	}
	if o.LineHeight != -1 {
		props = append(props, Property{Key: 370, Type: PropertyTypeFloat, Value: o.LineHeight})
	}
	if o.LetterSpacing != 0 {
		props = append(props, Property{Key: 390, Type: PropertyTypeFloat, Value: o.LetterSpacing})
	}
	return props
}

// TextStyleAxis (typeKey: 144)
type TextStyleAxis struct {
	Component
	AxisValue float64 `rive:"288,float"`
	Tag       uint64  `rive:"289,uint"`
}

func (o *TextStyleAxis) TypeKey() uint32 { return 144 }

func (o *TextStyleAxis) Properties() []Property {
	props := o.Component.Properties()
	if o.AxisValue != 0 {
		props = append(props, Property{Key: 288, Type: PropertyTypeFloat, Value: o.AxisValue})
	}
	if o.Tag != 0 {
		props = append(props, Property{Key: 289, Type: PropertyTypeUint, Value: o.Tag})
	}
	return props
}

// TextStyleFeature (typeKey: 164)
type TextStyleFeature struct {
	Component
	Tag          uint64 `rive:"356,uint"`
	FeatureValue uint64 `rive:"357,uint"`
}

func (o *TextStyleFeature) TypeKey() uint32 { return 164 }

func (o *TextStyleFeature) Properties() []Property {
	props := o.Component.Properties()
	if o.Tag != 0 {
		props = append(props, Property{Key: 356, Type: PropertyTypeUint, Value: o.Tag})
	}
	if o.FeatureValue != 1 {
		props = append(props, Property{Key: 357, Type: PropertyTypeUint, Value: o.FeatureValue})
	}
	return props
}

// TextStylePaint (typeKey: 137)
type TextStylePaint struct {
	TextStyle
}

func (o *TextStylePaint) TypeKey() uint32 { return 137 }

func (o *TextStylePaint) Properties() []Property {
	return o.TextStyle.Properties()
}

// TextTargetModifier (typeKey: 546) [abstract]
type TextTargetModifier struct {
	TextModifier
	TargetId uint64 `rive:"778,uint"`
}

func (o *TextTargetModifier) Properties() []Property {
	props := o.TextModifier.Properties()
	if o.TargetId != ^uint64(0) {
		props = append(props, Property{Key: 778, Type: PropertyTypeUint, Value: o.TargetId})
	}
	return props
}

// TextValueRun (typeKey: 135)
type TextValueRun struct {
	Component
	Text    string `rive:"268,string"`
	StyleId uint64 `rive:"272,uint"`
}

func (o *TextValueRun) TypeKey() uint32 { return 135 }

func (o *TextValueRun) Properties() []Property {
	props := o.Component.Properties()
	if o.Text != "" {
		props = append(props, Property{Key: 268, Type: PropertyTypeString, Value: o.Text})
	}
	if o.StyleId != ^uint64(0) {
		props = append(props, Property{Key: 272, Type: PropertyTypeUint, Value: o.StyleId})
	}
	return props
}

// TextVariationModifier (typeKey: 162)
type TextVariationModifier struct {
	TextShapeModifier
	AxisTag   uint64  `rive:"320,uint"`
	AxisValue float64 `rive:"321,float"`
}

func (o *TextVariationModifier) TypeKey() uint32 { return 162 }

func (o *TextVariationModifier) Properties() []Property {
	props := o.TextShapeModifier.Properties()
	if o.AxisTag != 0 {
		props = append(props, Property{Key: 320, Type: PropertyTypeUint, Value: o.AxisTag})
	}
	if o.AxisValue != 0 {
		props = append(props, Property{Key: 321, Type: PropertyTypeFloat, Value: o.AxisValue})
	}
	return props
}
