// Code generated by rivegen. DO NOT EDIT.
package rive

// ClampedScrollPhysics (typeKey: 524)
type ClampedScrollPhysics struct {
	ScrollPhysics
}

func (o *ClampedScrollPhysics) TypeKey() uint32 { return 524 }

func (o *ClampedScrollPhysics) Properties() []Property {
	return o.ScrollPhysics.Properties()
}

// Constraint (typeKey: 79) [abstract]
type Constraint struct {
	Component
	Strength float64 `rive:"172,float"`
}

func (o *Constraint) Properties() []Property {
	props := o.Component.Properties()
	if o.Strength != 1 {
		props = append(props, Property{Key: 172, Type: PropertyTypeFloat, Value: o.Strength})
	}
	return props
}

// DistanceConstraint (typeKey: 82)
type DistanceConstraint struct {
	TargetedConstraint
	Distance  float64 `rive:"177,float"`
	ModeValue uint64  `rive:"178,uint"`
}

func (o *DistanceConstraint) TypeKey() uint32 { return 82 }

func (o *DistanceConstraint) Properties() []Property {
	props := o.TargetedConstraint.Properties()
	if o.Distance != 100 {
		props = append(props, Property{Key: 177, Type: PropertyTypeFloat, Value: o.Distance})
	}
	if o.ModeValue != 0 {
		props = append(props, Property{Key: 178, Type: PropertyTypeUint, Value: o.ModeValue})
	}
	return props
}

// DraggableConstraint (typeKey: 520) [abstract]
type DraggableConstraint struct {
	Constraint
	DirectionValue uint64 `rive:"722,uint"`
}

func (o *DraggableConstraint) Properties() []Property {
	props := o.Constraint.Properties()
	if o.DirectionValue != 1 {
		props = append(props, Property{Key: 722, Type: PropertyTypeUint, Value: o.DirectionValue})
	}
	return props
}

// ElasticScrollPhysics (typeKey: 525)
type ElasticScrollPhysics struct {
	ScrollPhysics
	Friction        float64 `rive:"728,float"`
	SpeedMultiplier float64 `rive:"729,float"`
	ElasticFactor   float64 `rive:"730,float"`
}

func (o *ElasticScrollPhysics) TypeKey() uint32 { return 525 }

func (o *ElasticScrollPhysics) Properties() []Property {
	props := o.ScrollPhysics.Properties()
	if o.Friction != 8 {
		props = append(props, Property{Key: 728, Type: PropertyTypeFloat, Value: o.Friction})
	}
	if o.SpeedMultiplier != 1 {
		props = append(props, Property{Key: 729, Type: PropertyTypeFloat, Value: o.SpeedMultiplier})
	}
	if o.ElasticFactor != 0.66 {
		props = append(props, Property{Key: 730, Type: PropertyTypeFloat, Value: o.ElasticFactor})
	}
	return props
}

// FollowPathConstraint (typeKey: 165)
type FollowPathConstraint struct {
	TransformSpaceConstraint
	Distance float64 `rive:"363,float"`
	Orient   bool    `rive:"364,bool"`
	Offset   bool    `rive:"365,bool"`
}

func (o *FollowPathConstraint) TypeKey() uint32 { return 165 }

func (o *FollowPathConstraint) Properties() []Property {
	props := o.TransformSpaceConstraint.Properties()
	if o.Distance != 0 {
		props = append(props, Property{Key: 363, Type: PropertyTypeFloat, Value: o.Distance})
	}
	if !o.Orient {
		props = append(props, Property{Key: 364, Type: PropertyTypeUint, Value: boolToUint64(o.Orient)})
	}
	if o.Offset {
		props = append(props, Property{Key: 365, Type: PropertyTypeUint, Value: boolToUint64(o.Offset)})
	}
	return props
}

// IKConstraint (typeKey: 81)
type IKConstraint struct {
	TargetedConstraint
	InvertDirection bool   `rive:"174,bool"`
	ParentBoneCount uint64 `rive:"175,uint"`
}

func (o *IKConstraint) TypeKey() uint32 { return 81 }

func (o *IKConstraint) Properties() []Property {
	props := o.TargetedConstraint.Properties()
	if o.InvertDirection {
		props = append(props, Property{Key: 174, Type: PropertyTypeUint, Value: boolToUint64(o.InvertDirection)})
	}
	if o.ParentBoneCount != 0 {
		props = append(props, Property{Key: 175, Type: PropertyTypeUint, Value: o.ParentBoneCount})
	}
	return props
}

// ListFollowPathConstraint (typeKey: 625)
type ListFollowPathConstraint struct {
	FollowPathConstraint
	DistanceEnd    float64 `rive:"888,float"`
	DistanceOffset float64 `rive:"889,float"`
}

func (o *ListFollowPathConstraint) TypeKey() uint32 { return 625 }

func (o *ListFollowPathConstraint) Properties() []Property {
	props := o.FollowPathConstraint.Properties()
	if o.DistanceEnd != 1 {
		props = append(props, Property{Key: 888, Type: PropertyTypeFloat, Value: o.DistanceEnd})
	}
	if o.DistanceOffset != 0 {
		props = append(props, Property{Key: 889, Type: PropertyTypeFloat, Value: o.DistanceOffset})
	}
	return props
}

// RotationConstraint (typeKey: 89)
type RotationConstraint struct {
	TransformComponentConstraint
}

func (o *RotationConstraint) TypeKey() uint32 { return 89 }

func (o *RotationConstraint) Properties() []Property {
	return o.TransformComponentConstraint.Properties()
}

// ScaleConstraint (typeKey: 88)
type ScaleConstraint struct {
	TransformComponentConstraintY
}

func (o *ScaleConstraint) TypeKey() uint32 { return 88 }

func (o *ScaleConstraint) Properties() []Property {
	return o.TransformComponentConstraintY.Properties()
}

// ScrollBarConstraint (typeKey: 522)
type ScrollBarConstraint struct {
	DraggableConstraint
	ScrollConstraintId uint64 `rive:"725,uint"`
	AutoSize           bool   `rive:"734,bool"`
}

func (o *ScrollBarConstraint) TypeKey() uint32 { return 522 }

func (o *ScrollBarConstraint) Properties() []Property {
	props := o.DraggableConstraint.Properties()
	if o.ScrollConstraintId != ^uint64(0) {
		props = append(props, Property{Key: 725, Type: PropertyTypeUint, Value: o.ScrollConstraintId})
	}
	if !o.AutoSize {
		props = append(props, Property{Key: 734, Type: PropertyTypeUint, Value: boolToUint64(o.AutoSize)})
	}
	return props
}

// ScrollConstraint (typeKey: 521)
type ScrollConstraint struct {
	DraggableConstraint
	Snap             bool    `rive:"724,bool"`
	PhysicsId        uint64  `rive:"726,uint"`
	PhysicsTypeValue uint64  `rive:"727,uint"`
	ScrollOffsetX    float64 `rive:"759,float"`
	ScrollOffsetY    float64 `rive:"760,float"`
	Virtualize       bool    `rive:"850,bool"`
	Infinite         bool    `rive:"851,bool"`
	Interactive      bool    `rive:"891,bool"`
	Threshold        float64 `rive:"894,float"`
}

func (o *ScrollConstraint) TypeKey() uint32 { return 521 }

func (o *ScrollConstraint) Properties() []Property {
	props := o.DraggableConstraint.Properties()
	if o.Snap {
		props = append(props, Property{Key: 724, Type: PropertyTypeUint, Value: boolToUint64(o.Snap)})
	}
	if o.PhysicsId != ^uint64(0) {
		props = append(props, Property{Key: 726, Type: PropertyTypeUint, Value: o.PhysicsId})
	}
	if o.PhysicsTypeValue != 0 {
		props = append(props, Property{Key: 727, Type: PropertyTypeUint, Value: o.PhysicsTypeValue})
	}
	if o.ScrollOffsetX != 0 {
		props = append(props, Property{Key: 759, Type: PropertyTypeFloat, Value: o.ScrollOffsetX})
	}
	if o.ScrollOffsetY != 0 {
		props = append(props, Property{Key: 760, Type: PropertyTypeFloat, Value: o.ScrollOffsetY})
	}
	if o.Virtualize {
		props = append(props, Property{Key: 850, Type: PropertyTypeUint, Value: boolToUint64(o.Virtualize)})
	}
	if o.Infinite {
		props = append(props, Property{Key: 851, Type: PropertyTypeUint, Value: boolToUint64(o.Infinite)})
	}
	if !o.Interactive {
		props = append(props, Property{Key: 891, Type: PropertyTypeUint, Value: boolToUint64(o.Interactive)})
	}
	if o.Threshold != 0 {
		props = append(props, Property{Key: 894, Type: PropertyTypeFloat, Value: o.Threshold})
	}
	return props
}

// ScrollPhysics (typeKey: 523) [abstract]
type ScrollPhysics struct {
	Component
	ConstraintId uint64 `rive:"731,uint"`
}

func (o *ScrollPhysics) Properties() []Property {
	props := o.Component.Properties()
	if o.ConstraintId != ^uint64(0) {
		props = append(props, Property{Key: 731, Type: PropertyTypeUint, Value: o.ConstraintId})
	}
	return props
}

// TargetedConstraint (typeKey: 80) [abstract]
type TargetedConstraint struct {
	Constraint
	TargetId uint64 `rive:"173,uint"`
}

func (o *TargetedConstraint) Properties() []Property {
	props := o.Constraint.Properties()
	if o.TargetId != ^uint64(0) {
		props = append(props, Property{Key: 173, Type: PropertyTypeUint, Value: o.TargetId})
	}
	return props
}

// TransformComponentConstraint (typeKey: 85) [abstract]
type TransformComponentConstraint struct {
	TransformSpaceConstraint
	CopyFactor       float64 `rive:"182,float"`
	MinValue         float64 `rive:"183,float"`
	MaxValue         float64 `rive:"184,float"`
	Offset           bool    `rive:"188,bool"`
	DoesCopy         bool    `rive:"189,bool"`
	Min              bool    `rive:"190,bool"`
	Max              bool    `rive:"191,bool"`
	MinMaxSpaceValue uint64  `rive:"195,uint"`
}

func (o *TransformComponentConstraint) Properties() []Property {
	props := o.TransformSpaceConstraint.Properties()
	if o.CopyFactor != 1 {
		props = append(props, Property{Key: 182, Type: PropertyTypeFloat, Value: o.CopyFactor})
	}
	if o.MinValue != 0 {
		props = append(props, Property{Key: 183, Type: PropertyTypeFloat, Value: o.MinValue})
	}
	if o.MaxValue != 0 {
		props = append(props, Property{Key: 184, Type: PropertyTypeFloat, Value: o.MaxValue})
	}
	if o.Offset {
		props = append(props, Property{Key: 188, Type: PropertyTypeUint, Value: boolToUint64(o.Offset)})
	}
	if !o.DoesCopy {
		props = append(props, Property{Key: 189, Type: PropertyTypeUint, Value: boolToUint64(o.DoesCopy)})
	}
	if o.Min {
		props = append(props, Property{Key: 190, Type: PropertyTypeUint, Value: boolToUint64(o.Min)})
	}
	if o.Max {
		props = append(props, Property{Key: 191, Type: PropertyTypeUint, Value: boolToUint64(o.Max)})
	}
	if o.MinMaxSpaceValue != 0 {
		props = append(props, Property{Key: 195, Type: PropertyTypeUint, Value: o.MinMaxSpaceValue})
	}
	return props
}

// TransformComponentConstraintY (typeKey: 86) [abstract]
type TransformComponentConstraintY struct {
	TransformComponentConstraint
	CopyFactorY float64 `rive:"185,float"`
	MinValueY   float64 `rive:"186,float"`
	MaxValueY   float64 `rive:"187,float"`
	DoesCopyY   bool    `rive:"192,bool"`
	MinY        bool    `rive:"193,bool"`
	MaxY        bool    `rive:"194,bool"`
}

func (o *TransformComponentConstraintY) Properties() []Property {
	props := o.TransformComponentConstraint.Properties()
	if o.CopyFactorY != 1 {
		props = append(props, Property{Key: 185, Type: PropertyTypeFloat, Value: o.CopyFactorY})
	}
	if o.MinValueY != 0 {
		props = append(props, Property{Key: 186, Type: PropertyTypeFloat, Value: o.MinValueY})
	}
	if o.MaxValueY != 0 {
		props = append(props, Property{Key: 187, Type: PropertyTypeFloat, Value: o.MaxValueY})
	}
	if !o.DoesCopyY {
		props = append(props, Property{Key: 192, Type: PropertyTypeUint, Value: boolToUint64(o.DoesCopyY)})
	}
	if o.MinY {
		props = append(props, Property{Key: 193, Type: PropertyTypeUint, Value: boolToUint64(o.MinY)})
	}
	if o.MaxY {
		props = append(props, Property{Key: 194, Type: PropertyTypeUint, Value: boolToUint64(o.MaxY)})
	}
	return props
}

// TransformConstraint (typeKey: 83)
type TransformConstraint struct {
	TransformSpaceConstraint
	OriginX float64 `rive:"372,float"`
	OriginY float64 `rive:"373,float"`
}

func (o *TransformConstraint) TypeKey() uint32 { return 83 }

func (o *TransformConstraint) Properties() []Property {
	props := o.TransformSpaceConstraint.Properties()
	if o.OriginX != 0 {
		props = append(props, Property{Key: 372, Type: PropertyTypeFloat, Value: o.OriginX})
	}
	if o.OriginY != 0 {
		props = append(props, Property{Key: 373, Type: PropertyTypeFloat, Value: o.OriginY})
	}
	return props
}

// TransformSpaceConstraint (typeKey: 90) [abstract]
type TransformSpaceConstraint struct {
	TargetedConstraint
	SourceSpaceValue uint64 `rive:"179,uint"`
	DestSpaceValue   uint64 `rive:"180,uint"`
}

func (o *TransformSpaceConstraint) Properties() []Property {
	props := o.TargetedConstraint.Properties()
	if o.SourceSpaceValue != 0 {
		props = append(props, Property{Key: 179, Type: PropertyTypeUint, Value: o.SourceSpaceValue})
	}
	if o.DestSpaceValue != 0 {
		props = append(props, Property{Key: 180, Type: PropertyTypeUint, Value: o.DestSpaceValue})
	}
	return props
}

// TranslationConstraint (typeKey: 87)
type TranslationConstraint struct {
	TransformComponentConstraintY
}

func (o *TranslationConstraint) TypeKey() uint32 { return 87 }

func (o *TranslationConstraint) Properties() []Property {
	return o.TransformComponentConstraintY.Properties()
}
