// Code generated by rivegen. DO NOT EDIT.
package rive

// ScriptedDataConverter (typeKey: 629)
type ScriptedDataConverter struct {
	DataConverter
	ScriptAssetId uint64 `rive:"892,uint"`
}

func (o *ScriptedDataConverter) TypeKey() uint32 { return 629 }

func (o *ScriptedDataConverter) Properties() []Property {
	props := o.DataConverter.Properties()
	if o.ScriptAssetId != ^uint64(0) {
		props = append(props, Property{Key: 892, Type: PropertyTypeUint, Value: o.ScriptAssetId})
	}
	return props
}

// ScriptedDrawable (typeKey: 603)
type ScriptedDrawable struct {
	Drawable
	ScriptAssetId uint64 `rive:"848,uint"`
}

func (o *ScriptedDrawable) TypeKey() uint32 { return 603 }

func (o *ScriptedDrawable) Properties() []Property {
	props := o.Drawable.Properties()
	if o.ScriptAssetId != ^uint64(0) {
		props = append(props, Property{Key: 848, Type: PropertyTypeUint, Value: o.ScriptAssetId})
	}
	return props
}

// ScriptedLayout (typeKey: 637)
type ScriptedLayout struct {
	ScriptedDrawable
}

func (o *ScriptedLayout) TypeKey() uint32 { return 637 }

func (o *ScriptedLayout) Properties() []Property {
	return o.ScriptedDrawable.Properties()
}

// ScriptedPathEffect (typeKey: 640)
type ScriptedPathEffect struct {
	ContainerComponent
	ScriptAssetId uint64 `rive:"912,uint"`
}

func (o *ScriptedPathEffect) TypeKey() uint32 { return 640 }

func (o *ScriptedPathEffect) Properties() []Property {
	props := o.ContainerComponent.Properties()
	if o.ScriptAssetId != ^uint64(0) {
		props = append(props, Property{Key: 912, Type: PropertyTypeUint, Value: o.ScriptAssetId})
	}
	return props
}
