// Code generated by gen-defaults. DO NOT EDIT.
// Source: format_contract_proven.json (wasm: @rive-app/canvas-advanced@2.37.6)
package rive

// ImageToC returns the required ToC property keys for Image.
func ImageToC() []uint32 {
	return []uint32{206}
}

// objectRequiredToCKeys returns the required ToC property keys for obj, or nil if none.
func objectRequiredToCKeys(obj Object) []uint32 {
	switch obj.(type) {
	case *Image:
		return ImageToC()
	}
	return nil
}
