// Code generated by rivegen. DO NOT EDIT.
package rive

// ArtboardComponentListOverride (typeKey: 606)
type ArtboardComponentListOverride struct {
	Component
	InstanceWidthUnitsValue  uint64  `rive:"856,uint"`
	ArtboardId               uint64  `rive:"858,uint"`
	InstanceWidth            float64 `rive:"859,float"`
	InstanceHeight           float64 `rive:"860,float"`
	InstanceHeightUnitsValue uint64  `rive:"861,uint"`
	InstanceWidthScaleType   uint64  `rive:"862,uint"`
	InstanceHeightScaleType  uint64  `rive:"863,uint"`
}

func (o *ArtboardComponentListOverride) TypeKey() uint32 { return 606 }

func (o *ArtboardComponentListOverride) Properties() []Property {
	props := o.Component.Properties()
	if o.InstanceWidthUnitsValue != 1 {
		props = append(props, Property{Key: 856, Type: PropertyTypeUint, Value: o.InstanceWidthUnitsValue})
	}
	if o.ArtboardId != ^uint64(0) {
		props = append(props, Property{Key: 858, Type: PropertyTypeUint, Value: o.ArtboardId})
	}
	if o.InstanceWidth != -1 {
		props = append(props, Property{Key: 859, Type: PropertyTypeFloat, Value: o.InstanceWidth})
	}
	if o.InstanceHeight != -1 {
		props = append(props, Property{Key: 860, Type: PropertyTypeFloat, Value: o.InstanceHeight})
	}
	if o.InstanceHeightUnitsValue != 1 {
		props = append(props, Property{Key: 861, Type: PropertyTypeUint, Value: o.InstanceHeightUnitsValue})
	}
	if o.InstanceWidthScaleType != 0 {
		props = append(props, Property{Key: 862, Type: PropertyTypeUint, Value: o.InstanceWidthScaleType})
	}
	if o.InstanceHeightScaleType != 0 {
		props = append(props, Property{Key: 863, Type: PropertyTypeUint, Value: o.InstanceHeightScaleType})
	}
	return props
}

// Axis (typeKey: 492) [abstract]
type Axis struct {
	Component
	Offset     float64 `rive:"675,float"`
	Normalized bool    `rive:"676,bool"`
}

func (o *Axis) Properties() []Property {
	props := o.Component.Properties()
	if o.Offset != 0 {
		props = append(props, Property{Key: 675, Type: PropertyTypeFloat, Value: o.Offset})
	}
	if o.Normalized {
		props = append(props, Property{Key: 676, Type: PropertyTypeUint, Value: boolToUint64(o.Normalized)})
	}
	return props
}

// AxisX (typeKey: 495)
type AxisX struct {
	Axis
}

func (o *AxisX) TypeKey() uint32 { return 495 }

func (o *AxisX) Properties() []Property {
	return o.Axis.Properties()
}

// AxisY (typeKey: 494)
type AxisY struct {
	Axis
}

func (o *AxisY) TypeKey() uint32 { return 494 }

func (o *AxisY) Properties() []Property {
	return o.Axis.Properties()
}

// LayoutComponentStyle (typeKey: 420)
type LayoutComponentStyle struct {
	Component
	GapHorizontal            float64 `rive:"498,float"`
	GapVertical              float64 `rive:"499,float"`
	MaxWidth                 float64 `rive:"500,float"`
	MaxHeight                float64 `rive:"501,float"`
	MinWidth                 float64 `rive:"502,float"`
	MinHeight                float64 `rive:"503,float"`
	BorderLeft               float64 `rive:"504,float"`
	BorderRight              float64 `rive:"505,float"`
	BorderTop                float64 `rive:"506,float"`
	BorderBottom             float64 `rive:"507,float"`
	MarginLeft               float64 `rive:"508,float"`
	MarginRight              float64 `rive:"509,float"`
	MarginTop                float64 `rive:"510,float"`
	MarginBottom             float64 `rive:"511,float"`
	PaddingLeft              float64 `rive:"512,float"`
	PaddingRight             float64 `rive:"513,float"`
	PaddingTop               float64 `rive:"514,float"`
	PaddingBottom            float64 `rive:"515,float"`
	PositionLeft             float64 `rive:"516,float"`
	PositionRight            float64 `rive:"517,float"`
	PositionTop              float64 `rive:"518,float"`
	PositionBottom           float64 `rive:"519,float"`
	Flex                     float64 `rive:"520,float"`
	FlexGrow                 float64 `rive:"521,float"`
	FlexShrink               float64 `rive:"522,float"`
	FlexBasis                float64 `rive:"523,float"`
	AspectRatio              float64 `rive:"524,float"`
	AnimationStyleType       uint64  `rive:"589,uint"`
	InterpolationType        uint64  `rive:"590,uint"`
	InterpolatorId           uint64  `rive:"591,uint"`
	InterpolationTime        float64 `rive:"592,float"`
	DisplayValue             uint64  `rive:"596,uint"`
	PositionTypeValue        uint64  `rive:"597,uint"`
	FlexDirectionValue       uint64  `rive:"598,uint"`
	DirectionValue           uint64  `rive:"599,uint"`
	AlignContentValue        uint64  `rive:"600,uint"`
	AlignItemsValue          uint64  `rive:"601,uint"`
	AlignSelfValue           uint64  `rive:"602,uint"`
	JustifyContentValue      uint64  `rive:"603,uint"`
	FlexWrapValue            uint64  `rive:"604,uint"`
	OverflowValue            uint64  `rive:"605,uint"`
	IntrinsicallySizedValue  bool    `rive:"606,bool"`
	WidthUnitsValue          uint64  `rive:"607,uint"`
	HeightUnitsValue         uint64  `rive:"608,uint"`
	BorderLeftUnitsValue     uint64  `rive:"609,uint"`
	BorderRightUnitsValue    uint64  `rive:"610,uint"`
	BorderTopUnitsValue      uint64  `rive:"611,uint"`
	BorderBottomUnitsValue   uint64  `rive:"612,uint"`
	MarginLeftUnitsValue     uint64  `rive:"613,uint"`
	MarginRightUnitsValue    uint64  `rive:"614,uint"`
	MarginTopUnitsValue      uint64  `rive:"615,uint"`
	MarginBottomUnitsValue   uint64  `rive:"616,uint"`
	PaddingLeftUnitsValue    uint64  `rive:"617,uint"`
	PaddingRightUnitsValue   uint64  `rive:"618,uint"`
	PaddingTopUnitsValue     uint64  `rive:"619,uint"`
	PaddingBottomUnitsValue  uint64  `rive:"620,uint"`
	PositionLeftUnitsValue   uint64  `rive:"621,uint"`
	PositionRightUnitsValue  uint64  `rive:"622,uint"`
	PositionTopUnitsValue    uint64  `rive:"623,uint"`
	PositionBottomUnitsValue uint64  `rive:"624,uint"`
	GapHorizontalUnitsValue  uint64  `rive:"625,uint"`
	GapVerticalUnitsValue    uint64  `rive:"626,uint"`
	MinWidthUnitsValue       uint64  `rive:"627,uint"`
	MinHeightUnitsValue      uint64  `rive:"628,uint"`
	MaxWidthUnitsValue       uint64  `rive:"629,uint"`
	MaxHeightUnitsValue      uint64  `rive:"630,uint"`
	LayoutAlignmentType      uint64  `rive:"632,uint"`
	LinkCornerRadius         bool    `rive:"639,bool"`
	CornerRadiusTL           float64 `rive:"640,float"`
	CornerRadiusTR           float64 `rive:"641,float"`
	CornerRadiusBL           float64 `rive:"642,float"`
	CornerRadiusBR           float64 `rive:"643,float"`
	LayoutWidthScaleType     uint64  `rive:"655,uint"`
	LayoutHeightScaleType    uint64  `rive:"656,uint"`
	FlexBasisUnitsValue      uint64  `rive:"705,uint"`
}

func (o *LayoutComponentStyle) TypeKey() uint32 { return 420 }

func (o *LayoutComponentStyle) Properties() []Property {
	props := o.Component.Properties()
	if o.GapHorizontal != 0 {
		props = append(props, Property{Key: 498, Type: PropertyTypeFloat, Value: o.GapHorizontal})
	}
	if o.GapVertical != 0 {
		props = append(props, Property{Key: 499, Type: PropertyTypeFloat, Value: o.GapVertical})
	}
	if o.MaxWidth != 0 {
		props = append(props, Property{Key: 500, Type: PropertyTypeFloat, Value: o.MaxWidth})
	}
	if o.MaxHeight != 0 {
		props = append(props, Property{Key: 501, Type: PropertyTypeFloat, Value: o.MaxHeight})
	}
	if o.MinWidth != 0 {
		props = append(props, Property{Key: 502, Type: PropertyTypeFloat, Value: o.MinWidth})
	}
	if o.MinHeight != 0 {
		props = append(props, Property{Key: 503, Type: PropertyTypeFloat, Value: o.MinHeight})
	}
	if o.BorderLeft != 0 {
		props = append(props, Property{Key: 504, Type: PropertyTypeFloat, Value: o.BorderLeft})
	}
	if o.BorderRight != 0 {
		props = append(props, Property{Key: 505, Type: PropertyTypeFloat, Value: o.BorderRight})
	}
	if o.BorderTop != 0 {
		props = append(props, Property{Key: 506, Type: PropertyTypeFloat, Value: o.BorderTop})
	}
	if o.BorderBottom != 0 {
		props = append(props, Property{Key: 507, Type: PropertyTypeFloat, Value: o.BorderBottom})
	}
	if o.MarginLeft != 0 {
		props = append(props, Property{Key: 508, Type: PropertyTypeFloat, Value: o.MarginLeft})
	}
	if o.MarginRight != 0 {
		props = append(props, Property{Key: 509, Type: PropertyTypeFloat, Value: o.MarginRight})
	}
	if o.MarginTop != 0 {
		props = append(props, Property{Key: 510, Type: PropertyTypeFloat, Value: o.MarginTop})
	}
	if o.MarginBottom != 0 {
		props = append(props, Property{Key: 511, Type: PropertyTypeFloat, Value: o.MarginBottom})
	}
	if o.PaddingLeft != 0 {
		props = append(props, Property{Key: 512, Type: PropertyTypeFloat, Value: o.PaddingLeft})
	}
	if o.PaddingRight != 0 {
		props = append(props, Property{Key: 513, Type: PropertyTypeFloat, Value: o.PaddingRight})
	}
	if o.PaddingTop != 0 {
		props = append(props, Property{Key: 514, Type: PropertyTypeFloat, Value: o.PaddingTop})
	}
	if o.PaddingBottom != 0 {
		props = append(props, Property{Key: 515, Type: PropertyTypeFloat, Value: o.PaddingBottom})
	}
	if o.PositionLeft != 0 {
		props = append(props, Property{Key: 516, Type: PropertyTypeFloat, Value: o.PositionLeft})
	}
	if o.PositionRight != 0 {
		props = append(props, Property{Key: 517, Type: PropertyTypeFloat, Value: o.PositionRight})
	}
	if o.PositionTop != 0 {
		props = append(props, Property{Key: 518, Type: PropertyTypeFloat, Value: o.PositionTop})
	}
	if o.PositionBottom != 0 {
		props = append(props, Property{Key: 519, Type: PropertyTypeFloat, Value: o.PositionBottom})
	}
	if o.Flex != 0 {
		props = append(props, Property{Key: 520, Type: PropertyTypeFloat, Value: o.Flex})
	}
	if o.FlexGrow != 0 {
		props = append(props, Property{Key: 521, Type: PropertyTypeFloat, Value: o.FlexGrow})
	}
	if o.FlexShrink != 1 {
		props = append(props, Property{Key: 522, Type: PropertyTypeFloat, Value: o.FlexShrink})
	}
	if o.FlexBasis != 0 {
		props = append(props, Property{Key: 523, Type: PropertyTypeFloat, Value: o.FlexBasis})
	}
	if o.AspectRatio != 0 {
		props = append(props, Property{Key: 524, Type: PropertyTypeFloat, Value: o.AspectRatio})
	}
	if o.AnimationStyleType != 0 {
		props = append(props, Property{Key: 589, Type: PropertyTypeUint, Value: o.AnimationStyleType})
	}
	if o.InterpolationType != 0 {
		props = append(props, Property{Key: 590, Type: PropertyTypeUint, Value: o.InterpolationType})
	}
	if o.InterpolatorId != ^uint64(0) {
		props = append(props, Property{Key: 591, Type: PropertyTypeUint, Value: o.InterpolatorId})
	}
	if o.InterpolationTime != 0 {
		props = append(props, Property{Key: 592, Type: PropertyTypeFloat, Value: o.InterpolationTime})
	}
	if o.DisplayValue != 0 {
		props = append(props, Property{Key: 596, Type: PropertyTypeUint, Value: o.DisplayValue})
	}
	if o.PositionTypeValue != 1 {
		props = append(props, Property{Key: 597, Type: PropertyTypeUint, Value: o.PositionTypeValue})
	}
	if o.FlexDirectionValue != 2 {
		props = append(props, Property{Key: 598, Type: PropertyTypeUint, Value: o.FlexDirectionValue})
	}
	if o.DirectionValue != 0 {
		props = append(props, Property{Key: 599, Type: PropertyTypeUint, Value: o.DirectionValue})
	}
	if o.AlignContentValue != 0 {
		props = append(props, Property{Key: 600, Type: PropertyTypeUint, Value: o.AlignContentValue})
	}
	if o.AlignItemsValue != 1 {
		props = append(props, Property{Key: 601, Type: PropertyTypeUint, Value: o.AlignItemsValue})
	}
	if o.AlignSelfValue != 0 {
		props = append(props, Property{Key: 602, Type: PropertyTypeUint, Value: o.AlignSelfValue})
	}
	if o.JustifyContentValue != 0 {
		props = append(props, Property{Key: 603, Type: PropertyTypeUint, Value: o.JustifyContentValue})
	}
	if o.FlexWrapValue != 0 {
		props = append(props, Property{Key: 604, Type: PropertyTypeUint, Value: o.FlexWrapValue})
	}
	if o.OverflowValue != 0 {
		props = append(props, Property{Key: 605, Type: PropertyTypeUint, Value: o.OverflowValue})
	}
	if o.IntrinsicallySizedValue {
		props = append(props, Property{Key: 606, Type: PropertyTypeUint, Value: boolToUint64(o.IntrinsicallySizedValue)})
	}
	if o.WidthUnitsValue != 1 {
		props = append(props, Property{Key: 607, Type: PropertyTypeUint, Value: o.WidthUnitsValue})
	}
	if o.HeightUnitsValue != 1 {
		props = append(props, Property{Key: 608, Type: PropertyTypeUint, Value: o.HeightUnitsValue})
	}
	if o.BorderLeftUnitsValue != 0 {
		props = append(props, Property{Key: 609, Type: PropertyTypeUint, Value: o.BorderLeftUnitsValue})
	}
	if o.BorderRightUnitsValue != 0 {
		props = append(props, Property{Key: 610, Type: PropertyTypeUint, Value: o.BorderRightUnitsValue})
	}
	if o.BorderTopUnitsValue != 0 {
		props = append(props, Property{Key: 611, Type: PropertyTypeUint, Value: o.BorderTopUnitsValue})
	}
	if o.BorderBottomUnitsValue != 0 {
		props = append(props, Property{Key: 612, Type: PropertyTypeUint, Value: o.BorderBottomUnitsValue})
	}
	if o.MarginLeftUnitsValue != 0 {
		props = append(props, Property{Key: 613, Type: PropertyTypeUint, Value: o.MarginLeftUnitsValue})
	}
	if o.MarginRightUnitsValue != 0 {
		props = append(props, Property{Key: 614, Type: PropertyTypeUint, Value: o.MarginRightUnitsValue})
	}
	if o.MarginTopUnitsValue != 0 {
		props = append(props, Property{Key: 615, Type: PropertyTypeUint, Value: o.MarginTopUnitsValue})
	}
	if o.MarginBottomUnitsValue != 0 {
		props = append(props, Property{Key: 616, Type: PropertyTypeUint, Value: o.MarginBottomUnitsValue})
	}
	if o.PaddingLeftUnitsValue != 0 {
		props = append(props, Property{Key: 617, Type: PropertyTypeUint, Value: o.PaddingLeftUnitsValue})
	}
	if o.PaddingRightUnitsValue != 0 {
		props = append(props, Property{Key: 618, Type: PropertyTypeUint, Value: o.PaddingRightUnitsValue})
	}
	if o.PaddingTopUnitsValue != 0 {
		props = append(props, Property{Key: 619, Type: PropertyTypeUint, Value: o.PaddingTopUnitsValue})
	}
	if o.PaddingBottomUnitsValue != 0 {
		props = append(props, Property{Key: 620, Type: PropertyTypeUint, Value: o.PaddingBottomUnitsValue})
	}
	if o.PositionLeftUnitsValue != 0 {
		props = append(props, Property{Key: 621, Type: PropertyTypeUint, Value: o.PositionLeftUnitsValue})
	}
	if o.PositionRightUnitsValue != 0 {
		props = append(props, Property{Key: 622, Type: PropertyTypeUint, Value: o.PositionRightUnitsValue})
	}
	if o.PositionTopUnitsValue != 0 {
		props = append(props, Property{Key: 623, Type: PropertyTypeUint, Value: o.PositionTopUnitsValue})
	}
	if o.PositionBottomUnitsValue != 0 {
		props = append(props, Property{Key: 624, Type: PropertyTypeUint, Value: o.PositionBottomUnitsValue})
	}
	if o.GapHorizontalUnitsValue != 0 {
		props = append(props, Property{Key: 625, Type: PropertyTypeUint, Value: o.GapHorizontalUnitsValue})
	}
	if o.GapVerticalUnitsValue != 0 {
		props = append(props, Property{Key: 626, Type: PropertyTypeUint, Value: o.GapVerticalUnitsValue})
	}
	if o.MinWidthUnitsValue != 0 {
		props = append(props, Property{Key: 627, Type: PropertyTypeUint, Value: o.MinWidthUnitsValue})
	}
	if o.MinHeightUnitsValue != 0 {
		props = append(props, Property{Key: 628, Type: PropertyTypeUint, Value: o.MinHeightUnitsValue})
	}
	if o.MaxWidthUnitsValue != 0 {
		props = append(props, Property{Key: 629, Type: PropertyTypeUint, Value: o.MaxWidthUnitsValue})
	}
	if o.MaxHeightUnitsValue != 0 {
		props = append(props, Property{Key: 630, Type: PropertyTypeUint, Value: o.MaxHeightUnitsValue})
	}
	if o.LayoutAlignmentType != 0 {
		props = append(props, Property{Key: 632, Type: PropertyTypeUint, Value: o.LayoutAlignmentType})
	}
	if !o.LinkCornerRadius {
		props = append(props, Property{Key: 639, Type: PropertyTypeUint, Value: boolToUint64(o.LinkCornerRadius)})
	}
	if o.CornerRadiusTL != 0 {
		props = append(props, Property{Key: 640, Type: PropertyTypeFloat, Value: o.CornerRadiusTL})
	}
	if o.CornerRadiusTR != 0 {
		props = append(props, Property{Key: 641, Type: PropertyTypeFloat, Value: o.CornerRadiusTR})
	}
	if o.CornerRadiusBL != 0 {
		props = append(props, Property{Key: 642, Type: PropertyTypeFloat, Value: o.CornerRadiusBL})
	}
	if o.CornerRadiusBR != 0 {
		props = append(props, Property{Key: 643, Type: PropertyTypeFloat, Value: o.CornerRadiusBR})
	}
	if o.LayoutWidthScaleType != 0 {
		props = append(props, Property{Key: 655, Type: PropertyTypeUint, Value: o.LayoutWidthScaleType})
	}
	if o.LayoutHeightScaleType != 0 {
		props = append(props, Property{Key: 656, Type: PropertyTypeUint, Value: o.LayoutHeightScaleType})
	}
	if o.FlexBasisUnitsValue != 3 {
		props = append(props, Property{Key: 705, Type: PropertyTypeUint, Value: o.FlexBasisUnitsValue})
	}
	return props
}

// NSlicedNode (typeKey: 508)
type NSlicedNode struct {
	Node
	InitialWidth  float64 `rive:"697,float"`
	InitialHeight float64 `rive:"698,float"`
	Width         float64 `rive:"699,float"`
	Height        float64 `rive:"700,float"`
}

func (o *NSlicedNode) TypeKey() uint32 { return 508 }

func (o *NSlicedNode) Properties() []Property {
	props := o.Node.Properties()
	if o.InitialWidth != 0 {
		props = append(props, Property{Key: 697, Type: PropertyTypeFloat, Value: o.InitialWidth})
	}
	if o.InitialHeight != 0 {
		props = append(props, Property{Key: 698, Type: PropertyTypeFloat, Value: o.InitialHeight})
	}
	if o.Width != 0 {
		props = append(props, Property{Key: 699, Type: PropertyTypeFloat, Value: o.Width})
	}
	if o.Height != 0 {
		props = append(props, Property{Key: 700, Type: PropertyTypeFloat, Value: o.Height})
	}
	return props
}

// NSlicer (typeKey: 493)
type NSlicer struct {
	ContainerComponent
}

func (o *NSlicer) TypeKey() uint32 { return 493 }

func (o *NSlicer) Properties() []Property {
	return o.ContainerComponent.Properties()
}

// NSlicerTileMode (typeKey: 491)
type NSlicerTileMode struct {
	Component
	PatchIndex uint64 `rive:"672,uint"`
	Style      uint64 `rive:"673,uint"`
}

func (o *NSlicerTileMode) TypeKey() uint32 { return 491 }

func (o *NSlicerTileMode) Properties() []Property {
	props := o.Component.Properties()
	if o.PatchIndex != 0 {
		props = append(props, Property{Key: 672, Type: PropertyTypeUint, Value: o.PatchIndex})
	}
	if o.Style != 0 {
		props = append(props, Property{Key: 673, Type: PropertyTypeUint, Value: o.Style})
	}
	return props
}
