// Code generated by rivegen. DO NOT EDIT.
package rive

// Asset (typeKey: 99) [abstract]
type Asset struct {
	Name string `rive:"203,string"`
}

func (o *Asset) Properties() []Property {
	var props []Property
	if o.Name != "" {
		props = append(props, Property{Key: 203, Type: PropertyTypeString, Value: o.Name})
	}
	return props
}

// AudioAsset (typeKey: 406)
type AudioAsset struct {
	ExportAudio
}

func (o *AudioAsset) TypeKey() uint32 { return 406 }

func (o *AudioAsset) Properties() []Property {
	return o.ExportAudio.Properties()
}

// BlobAsset (typeKey: 649)
type BlobAsset struct {
	FileAsset
}

func (o *BlobAsset) TypeKey() uint32 { return 649 }

func (o *BlobAsset) Properties() []Property {
	return o.FileAsset.Properties()
}

// DrawableAsset (typeKey: 104) [abstract]
type DrawableAsset struct {
	FileAsset
	Height float64 `rive:"207,float"`
	Width  float64 `rive:"208,float"`
}

func (o *DrawableAsset) Properties() []Property {
	props := o.FileAsset.Properties()
	if o.Height != 0 {
		props = append(props, Property{Key: 207, Type: PropertyTypeFloat, Value: o.Height})
	}
	if o.Width != 0 {
		props = append(props, Property{Key: 208, Type: PropertyTypeFloat, Value: o.Width})
	}
	return props
}

// ExportAudio (typeKey: 422) [abstract]
type ExportAudio struct {
	FileAsset
	Volume float64 `rive:"530,float"`
}

func (o *ExportAudio) Properties() []Property {
	props := o.FileAsset.Properties()
	if o.Volume != 1 {
		props = append(props, Property{Key: 530, Type: PropertyTypeFloat, Value: o.Volume})
	}
	return props
}

// FileAsset (typeKey: 103) [abstract]
type FileAsset struct {
	Asset
	AssetId    uint64 `rive:"204,uint"`
	CdnUuid    []byte `rive:"359,bytes"`
	CdnBaseUrl string `rive:"362,string"`
}

func (o *FileAsset) Properties() []Property {
	props := o.Asset.Properties()
	if o.AssetId != 0 {
		props = append(props, Property{Key: 204, Type: PropertyTypeUint, Value: o.AssetId})
	}
	if len(o.CdnUuid) > 0 {
		props = append(props, Property{Key: 359, Type: PropertyTypeBytes, Value: o.CdnUuid})
	}
	if o.CdnBaseUrl != "" {
		props = append(props, Property{Key: 362, Type: PropertyTypeString, Value: o.CdnBaseUrl})
	}
	return props
}

// FileAssetContents (typeKey: 106)
type FileAssetContents struct {
	Bytes     []byte `rive:"212,bytes"`
	Signature []byte `rive:"911,bytes"`
}

func (o *FileAssetContents) TypeKey() uint32 { return 106 }

func (o *FileAssetContents) Properties() []Property {
	var props []Property
	if len(o.Bytes) > 0 {
		props = append(props, Property{Key: 212, Type: PropertyTypeBytes, Value: o.Bytes})
	}
	if len(o.Signature) > 0 {
		props = append(props, Property{Key: 911, Type: PropertyTypeBytes, Value: o.Signature})
	}
	return props
}

// Folder (typeKey: 102)
type Folder struct {
	Asset
}

func (o *Folder) TypeKey() uint32 { return 102 }

func (o *Folder) Properties() []Property {
	return o.Asset.Properties()
}

// FontAsset (typeKey: 141)
type FontAsset struct {
	FileAsset
}

func (o *FontAsset) TypeKey() uint32 { return 141 }

func (o *FontAsset) Properties() []Property {
	return o.FileAsset.Properties()
}

// ImageAsset (typeKey: 105)
type ImageAsset struct {
	DrawableAsset
}

func (o *ImageAsset) TypeKey() uint32 { return 105 }

func (o *ImageAsset) Properties() []Property {
	return o.DrawableAsset.Properties()
}

// LayerImageAsset (typeKey: 120)
type LayerImageAsset struct {
	ImageAsset
}

func (o *LayerImageAsset) TypeKey() uint32 { return 120 }

func (o *LayerImageAsset) Properties() []Property {
	return o.ImageAsset.Properties()
}

// LayeredAsset (typeKey: 119)
type LayeredAsset struct {
	DrawableAsset
}

func (o *LayeredAsset) TypeKey() uint32 { return 119 }

func (o *LayeredAsset) Properties() []Property {
	return o.DrawableAsset.Properties()
}

// LottieAsset (typeKey: 133)
type LottieAsset struct {
	DrawableAsset
}

func (o *LottieAsset) TypeKey() uint32 { return 133 }

func (o *LottieAsset) Properties() []Property {
	return o.DrawableAsset.Properties()
}

// ManifestAsset (typeKey: 642)
type ManifestAsset struct {
	FileAsset
}

func (o *ManifestAsset) TypeKey() uint32 { return 642 }

func (o *ManifestAsset) Properties() []Property {
	return o.FileAsset.Properties()
}

// ProfilerAsset (typeKey: 651)
type ProfilerAsset struct {
	FileAsset
}

func (o *ProfilerAsset) TypeKey() uint32 { return 651 }

func (o *ProfilerAsset) Properties() []Property {
	return o.FileAsset.Properties()
}

// SVGAsset (typeKey: 132)
type SVGAsset struct {
	DrawableAsset
}

func (o *SVGAsset) TypeKey() uint32 { return 132 }

func (o *SVGAsset) Properties() []Property {
	return o.DrawableAsset.Properties()
}

// ScriptAsset (typeKey: 529)
type ScriptAsset struct {
	TextAsset
	GeneratorFunctionRef uint64 `rive:"893,uint"`
	IsModule             bool   `rive:"914,bool"`
}

func (o *ScriptAsset) TypeKey() uint32 { return 529 }

func (o *ScriptAsset) Properties() []Property {
	props := o.TextAsset.Properties()
	if o.GeneratorFunctionRef != 0 {
		props = append(props, Property{Key: 893, Type: PropertyTypeUint, Value: o.GeneratorFunctionRef})
	}
	if o.IsModule {
		props = append(props, Property{Key: 914, Type: PropertyTypeUint, Value: boolToUint64(o.IsModule)})
	}
	return props
}

// ShaderAsset (typeKey: 970)
type ShaderAsset struct {
	TextAsset
}

func (o *ShaderAsset) TypeKey() uint32 { return 970 }

func (o *ShaderAsset) Properties() []Property {
	return o.TextAsset.Properties()
}

// TextAsset (typeKey: 971) [abstract]
type TextAsset struct {
	FileAsset
	FolderPath string `rive:"926,string"`
}

func (o *TextAsset) Properties() []Property {
	props := o.FileAsset.Properties()
	if o.FolderPath != "" {
		props = append(props, Property{Key: 926, Type: PropertyTypeString, Value: o.FolderPath})
	}
	return props
}
