// Code generated by rivegen -contract format_contract.json. DO NOT EDIT.
package rive

// EmissionPhase classifies where in the object stream a type belongs.
type EmissionPhase int

const (
	PhaseGlobal       EmissionPhase = iota // Before any Artboard (Backboard, FontAsset pairs)
	PhaseArtboard                          // The Artboard itself
	PhaseChildren                          // Artboard children (shapes, text, nodes)
	PhasePaint                             // Fill/Stroke/SolidColor/Gradient
	PhaseAnimation                         // LinearAnimation + keyframes
	PhaseStateMachine                      // StateMachine + layers + states + transitions
)

// TypePhaseInfo holds phase classification for a typeKey.
type TypePhaseInfo struct {
	Phase    EmissionPhase
	Priority int
}

// TypePhase maps typeKey → emission phase and priority within that phase.
// Derived from official Rive test assets via rivtool analyze.
var TypePhase = map[uint32]TypePhaseInfo{
	1:   {PhaseArtboard, 0},
	3:   {PhaseChildren, 3},
	4:   {PhaseChildren, 4},
	7:   {PhaseChildren, 10},
	18:  {PhasePaint, 0},
	19:  {PhaseChildren, 21},
	20:  {PhasePaint, 1},
	22:  {PhasePaint, 2},
	23:  {PhaseGlobal, 0},
	24:  {PhaseChildren, 23},
	25:  {PhaseChildren, 6},
	26:  {PhaseChildren, 7},
	28:  {PhaseChildren, 11},
	30:  {PhaseChildren, 9},
	31:  {PhaseAnimation, 1},
	42:  {PhaseChildren, 22},
	53:  {PhaseStateMachine, 0},
	56:  {PhaseChildren, 12},
	57:  {PhaseStateMachine, 1},
	61:  {PhaseStateMachine, 2},
	62:  {PhaseStateMachine, 3},
	63:  {PhaseStateMachine, 5},
	64:  {PhaseStateMachine, 4},
	65:  {PhaseStateMachine, 6},
	73:  {PhaseStateMachine, 8},
	75:  {PhaseChildren, 16},
	76:  {PhaseChildren, 14},
	77:  {PhaseChildren, 13},
	78:  {PhaseChildren, 15},
	92:  {PhaseChildren, 1},
	95:  {PhaseAnimation, 0},
	106: {PhaseGlobal, 2},
	114: {PhaseAnimation, 2},
	128: {PhaseChildren, 0},
	134: {PhaseChildren, 17},
	135: {PhaseChildren, 20},
	137: {PhaseChildren, 18},
	138: {PhaseChildren, 5},
	141: {PhaseGlobal, 1},
	142: {PhaseChildren, 24},
	144: {PhaseChildren, 19},
	168: {PhaseStateMachine, 7},
	171: {PhaseChildren, 8},
	420: {PhaseChildren, 2},
}

// ToCIncludeKeys maps property key → field index in the ToC bit-pack.
// Keys present here must appear in every .riv file's Table of Contents.
// Keys absent from this set are CoreRegistry-known and must be excluded from the ToC.
// Field indices: 0=uint, 1=string/bytes, 2=float, 3=color.
var ToCIncludeKeys = map[uint32]uint32{
	160: 0,
	165: 0,
	166: 2,
	167: 0,
	168: 0,
	171: 0,
	197: 0,
	198: 0,
	203: 1,
	204: 0,
	206: 0,
	212: 1,
	224: 0,
	225: 0,
	236: 0,
	268: 1,
	272: 0,
	274: 2,
	279: 0,
	280: 1,
	284: 0,
	285: 2,
	286: 2,
	287: 0,
	288: 2,
	289: 0,
	389: 0,
	399: 0,
	494: 0,
}

// RiveDefault maps property key → Rive runtime default value.
// Only contains entries where rive_default differs from Go's zero value (mismatch=true).
// Properties at their RiveDefault MUST be omitted from the binary stream.
// Properties at Go's zero value that differ from RiveDefault MUST be emitted.
var RiveDefault = map[uint32]interface{}{
	16:  float64(1),                         // scaleX
	17:  float64(1),                         // scaleY
	18:  float64(1),                         // opacity
	23:  uint64(3),                          // blendModeValue
	37:  uint64(0xFF747474),                 // colorValue
	38:  uint64(0xFFFFFFFF),                 // colorValue
	41:  true,                               // isVisible
	46:  float64(1),                         // opacity
	47:  float64(1),                         // thickness
	50:  true,                               // transformAffectsStroke
	56:  uint64(60),                         // fps
	57:  uint64(60),                         // duration
	58:  float64(1),                         // speed
	60:  ^uint64(0),                         // workStart
	61:  ^uint64(0),                         // workEnd
	63:  float64(0.42),                      // x1
	65:  float64(0.58),                      // x2
	66:  float64(1),                         // y2
	69:  ^uint64(0),                         // interpolatorId
	92:  ^uint64(0),                         // sourceId
	94:  true,                               // isVisible
	95:  ^uint64(0),                         // boneId
	96:  float64(1),                         // xx
	99:  float64(1),                         // yy
	102: uint64(255),                        // values
	103: uint64(1),                          // indices
	104: float64(1),                         // xx
	107: float64(1),                         // yy
	110: uint64(255),                        // inValues
	111: uint64(1),                          // inIndices
	112: uint64(255),                        // outValues
	113: uint64(1),                          // outIndices
	119: ^uint64(0),                         // drawableId
	121: ^uint64(0),                         // drawTargetId
	122: ^uint64(0),                         // value
	123: float64(0.5),                       // originX
	124: float64(0.5),                       // originY
	125: uint64(5),                          // points
	127: float64(0.5),                       // innerRadius
	149: ^uint64(0),                         // animationId
	151: ^uint64(0),                         // stateToId
	155: ^uint64(0),                         // inputId
	164: true,                               // linkCornerRadius
	165: ^uint64(0),                         // animationId
	167: ^uint64(0),                         // inputId
	168: ^uint64(0),                         // inputId
	171: ^uint64(0),                         // exitBlendAnimationId
	172: float64(1),                         // strength
	173: ^uint64(0),                         // targetId
	177: float64(100),                       // distance
	182: float64(1),                         // copyFactor
	185: float64(1),                         // copyFactorY
	189: true,                               // doesCopy
	192: true,                               // doesCopyY
	197: ^uint64(0),                         // artboardId
	198: ^uint64(0),                         // animationId
	199: float64(1),                         // speed
	200: float64(1),                         // mix
	206: ^uint64(0),                         // assetId
	212: ([]byte)(nil),                      // bytes
	223: ([]byte)(nil),                      // triangleIndexBytes
	224: ^uint64(0),                         // targetId
	227: ^uint64(0),                         // inputId
	228: uint64(1),                          // value
	236: ^uint64(0),                         // defaultStateMachineId
	237: ^uint64(0),                         // inputId
	240: ^uint64(0),                         // targetId
	272: ^uint64(0),                         // styleId
	274: float64(12),                        // fontSize
	279: ^uint64(0),                         // fontAssetId
	292: float64(1),                         // speed
	297: float64(100),                       // mixValue
	301: ^uint64(0),                         // xId
	302: ^uint64(0),                         // yId
	305: float64(100),                       // width
	306: float64(100),                       // height
	307: float64(0.5),                       // originX
	308: float64(0.5),                       // originY
	313: ^uint64(0),                         // handleSourceId
	318: float64(1),                         // falloffTo
	324: float64(1),                         // opacity
	330: float64(1),                         // scaleX
	331: float64(1),                         // scaleY
	334: float64(1),                         // strength
	336: float64(1),                         // modifyTo
	337: float64(0.42),                      // x1
	339: float64(0.58),                      // x2
	340: float64(1),                         // y2
	349: uint64(1),                          // interpolationType
	350: ^uint64(0),                         // interpolatorId
	357: uint64(1),                          // featureValue
	359: ([]byte)(nil),                      // cdnUuid
	362: "https://public.rive.app/cdn/uuid", // cdnBaseUrl
	364: true,                               // orient
	370: float64(-1),                        // lineHeight
	378: ^uint64(0),                         // runId
	380: float64(0.5),                       // originX
	381: float64(0.5),                       // originY
	389: ^uint64(0),                         // eventId
	392: ^uint64(0),                         // eventId
	399: ^uint64(0),                         // eventId
	400: ^uint64(0),                         // nestedInputId
	405: uint64(1),                          // easingValue
	406: float64(1),                         // amplitude
	407: float64(1),                         // period
	408: ^uint64(0),                         // assetId
	494: ^uint64(0),                         // styleId
	522: float64(1),                         // flexShrink
	530: float64(1),                         // volume
	537: uint64(1),                          // randomWeight
	549: ^uint64(0),                         // viewModelId
	550: ^uint64(0),                         // viewModelInstanceId
	555: uint64(0xFF000000),                 // propertyValue
	574: ^uint64(0),                         // enumId
	582: ([]byte)(nil),                      // dataBindPathIds
	583: ^uint64(0),                         // viewModelId
	588: ([]byte)(nil),                      // sourcePathIds
	591: ^uint64(0),                         // interpolatorId
	597: uint64(1),                          // positionTypeValue
	598: uint64(2),                          // flexDirectionValue
	601: uint64(1),                          // alignItemsValue
	607: uint64(1),                          // widthUnitsValue
	608: uint64(1),                          // heightUnitsValue
	637: ^uint64(0),                         // propertyValue
	638: uint64(0xFF1D1D1D),                 // propertyValue
	639: true,                               // linkCornerRadius
	651: uint64(0xFF1D1D1D),                 // value
	653: ^uint64(0),                         // value
	660: ^uint64(0),                         // converterId
	663: float64(-1),                        // instanceWidth
	664: float64(-1),                        // instanceHeight
	665: uint64(1),                          // instanceWidthUnitsValue
	666: uint64(1),                          // instanceHeightUnitsValue
	679: ^uint64(0),                         // converterId
	681: float64(1),                         // operationValue
	703: true,                               // fitFromBaseline
	705: uint64(3),                          // flexBasisUnitsValue
	706: float64(1),                         // fractionalWidth
	707: float64(1),                         // fractionalHeight
	711: ([]byte)(nil),                      // sourcePathIds
	713: uint64(1),                          // interpolationType
	714: ^uint64(0),                         // interpolatorId
	716: float64(1),                         // minInput
	717: float64(1),                         // maxInput
	718: float64(1),                         // minOutput
	719: float64(1),                         // maxOutput
	722: uint64(1),                          // directionValue
	725: ^uint64(0),                         // scrollConstraintId
	726: ^uint64(0),                         // physicsId
	728: float64(8),                         // friction
	729: float64(1),                         // speedMultiplier
	730: float64(0.66),                      // elasticFactor
	731: ^uint64(0),                         // constraintId
	734: true,                               // autoSize
	743: uint64(1),                          // length
	746: uint64(1),                          // trimType
	747: uint64(127),                        // blendModeValue
	749: float64(12),                        // strength
	756: float64(1),                         // duration
	757: uint64(1),                          // interpolationType
	758: ^uint64(0),                         // interpolatorId
	777: float64(1),                         // operationValue
	778: ^uint64(0),                         // targetId
	782: true,                               // orient
	784: float64(1),                         // end
	785: float64(1),                         // strength
	800: ^uint64(0),                         // listSource
	816: ^uint64(0),                         // viewModelId
	818: float64(5),                         // selectionRadius
	823: ^uint64(0),                         // propertyValue
	824: ^uint64(0),                         // propertyValue
	835: ^uint64(0),                         // propertyValue
	836: uint64(0xFF1D1D1D),                 // propertyValue
	846: ^uint64(0),                         // propertyValue
	848: ^uint64(0),                         // scriptAssetId
	856: uint64(1),                          // instanceWidthUnitsValue
	858: ^uint64(0),                         // artboardId
	859: float64(-1),                        // instanceWidth
	860: float64(-1),                        // instanceHeight
	861: uint64(1),                          // instanceHeightUnitsValue
	866: ([]byte)(nil),                      // dataBindPathIds
	868: ([]byte)(nil),                      // viewModelPathIds
	871: ([]byte)(nil),                      // viewModelPathIds
	872: ^uint64(0),                         // propertyValue
	873: ^uint64(0),                         // enumId
	874: ^uint64(0),                         // listSource
	876: ^uint64(0),                         // artboardId
	888: float64(1),                         // distanceEnd
	891: true,                               // interactive
	892: ^uint64(0),                         // scriptAssetId
	907: float64(1),                         // speed
	908: float64(-1),                        // quantize
	911: ([]byte)(nil),                      // signature
	912: ^uint64(0),                         // scriptAssetId
	920: ([]byte)(nil),                      // path
	922: ^uint64(0),                         // targetId
	930: ^uint64(0),                         // scriptAssetId
	931: ^uint64(0),                         // scriptAssetId
	932: ^uint64(0),                         // textRunListSource
	934: ^uint64(0),                         // artboardId
	935: ^uint64(0),                         // viewModelId
	952: ^uint64(0),                         // targetId
	953: true,                               // canFocus
	954: true,                               // canTouch
	955: true,                               // canTraverse
	962: ^uint64(0),                         // eventId
	963: ([]byte)(nil),                      // viewModelPathIds
	966: ^uint64(0),                         // listSource
	971: ^uint64(0),                         // keyType
	979: true,                               // multiline
}

// RiveDefaultMismatch lists property keys where Go zero ≠ Rive runtime default.
// Struct fields at these keys must be initialized explicitly in constructors.
var RiveDefaultMismatch = []uint32{
	16,
	17,
	18,
	23,
	37,
	38,
	41,
	46,
	47,
	50,
	56,
	57,
	58,
	60,
	61,
	63,
	65,
	66,
	69,
	92,
	94,
	95,
	96,
	99,
	102,
	103,
	104,
	107,
	110,
	111,
	112,
	113,
	119,
	121,
	122,
	123,
	124,
	125,
	127,
	149,
	151,
	155,
	164,
	165,
	167,
	168,
	171,
	172,
	173,
	177,
	182,
	185,
	189,
	192,
	197,
	198,
	199,
	200,
	206,
	212,
	223,
	224,
	227,
	228,
	236,
	237,
	240,
	272,
	274,
	279,
	292,
	297,
	301,
	302,
	305,
	306,
	307,
	308,
	313,
	318,
	324,
	330,
	331,
	334,
	336,
	337,
	339,
	340,
	349,
	350,
	357,
	359,
	362,
	364,
	370,
	378,
	380,
	381,
	389,
	392,
	399,
	400,
	405,
	406,
	407,
	408,
	494,
	522,
	530,
	537,
	549,
	550,
	555,
	574,
	582,
	583,
	588,
	591,
	597,
	598,
	601,
	607,
	608,
	637,
	638,
	639,
	651,
	653,
	660,
	663,
	664,
	665,
	666,
	679,
	681,
	703,
	705,
	706,
	707,
	711,
	713,
	714,
	716,
	717,
	718,
	719,
	722,
	725,
	726,
	728,
	729,
	730,
	731,
	734,
	743,
	746,
	747,
	749,
	756,
	757,
	758,
	777,
	778,
	782,
	784,
	785,
	800,
	816,
	818,
	823,
	824,
	835,
	836,
	846,
	848,
	856,
	858,
	859,
	860,
	861,
	866,
	868,
	871,
	872,
	873,
	874,
	876,
	888,
	891,
	892,
	907,
	908,
	911,
	912,
	920,
	922,
	930,
	931,
	932,
	934,
	935,
	952,
	953,
	954,
	955,
	962,
	963,
	966,
	971,
	979,
}

// FormatParentIdRule describes parentId semantics for a typeKey.
type FormatParentIdRule struct {
	HasParentId bool
	RelativeTo  string // "artboard" for artboard-relative parentId, "" otherwise
}

// FormatParentIdRules maps typeKey → parentId rule derived from official .riv assets.
var FormatParentIdRules = map[uint32]FormatParentIdRule{
	1:   {HasParentId: false},
	3:   {HasParentId: true, RelativeTo: "artboard"},
	4:   {HasParentId: true, RelativeTo: "artboard"},
	7:   {HasParentId: true, RelativeTo: "artboard"},
	18:  {HasParentId: true, RelativeTo: "artboard"},
	19:  {HasParentId: true, RelativeTo: "artboard"},
	20:  {HasParentId: true, RelativeTo: "artboard"},
	22:  {HasParentId: true, RelativeTo: "artboard"},
	23:  {HasParentId: false},
	24:  {HasParentId: true, RelativeTo: "artboard"},
	25:  {HasParentId: false},
	26:  {HasParentId: false},
	28:  {HasParentId: false},
	30:  {HasParentId: false},
	31:  {HasParentId: false},
	42:  {HasParentId: true, RelativeTo: "artboard"},
	53:  {HasParentId: false},
	56:  {HasParentId: false},
	57:  {HasParentId: false},
	61:  {HasParentId: false},
	62:  {HasParentId: false},
	63:  {HasParentId: false},
	64:  {HasParentId: false},
	65:  {HasParentId: false},
	73:  {HasParentId: false},
	75:  {HasParentId: false},
	76:  {HasParentId: false},
	77:  {HasParentId: false},
	78:  {HasParentId: false},
	92:  {HasParentId: true, RelativeTo: "artboard"},
	95:  {HasParentId: true, RelativeTo: "artboard"},
	106: {HasParentId: false},
	114: {HasParentId: false},
	128: {HasParentId: true, RelativeTo: "artboard"},
	134: {HasParentId: true, RelativeTo: "artboard"},
	135: {HasParentId: true, RelativeTo: "artboard"},
	137: {HasParentId: true, RelativeTo: "artboard"},
	138: {HasParentId: false},
	141: {HasParentId: false},
	142: {HasParentId: false},
	144: {HasParentId: true, RelativeTo: "artboard"},
	168: {HasParentId: false},
	171: {HasParentId: false},
	420: {HasParentId: true, RelativeTo: "artboard"},
}
