// Code generated by gen-defaults. DO NOT EDIT.
// Source: format_contract_proven.json (wasm: @rive-app/canvas-advanced@2.37.6)
package rive

type artboardDefaults struct {
	BlendModeValue   uint64
	FractionalHeight float64
	FractionalWidth  float64
	Opacity          float64
	ScaleX           float64
	ScaleY           float64
}

// ArtboardDefaults holds required runtime defaults for Artboard.
var ArtboardDefaults = artboardDefaults{
	BlendModeValue:   3,
	FractionalHeight: 1.0,
	FractionalWidth:  1.0,
	Opacity:          1.0,
	ScaleX:           1.0,
	ScaleY:           1.0,
}

// ApplyDefaults sets required runtime defaults on Artboard.
func (x *Artboard) ApplyDefaults() {
	x.BlendModeValue = ArtboardDefaults.BlendModeValue
	x.FractionalHeight = ArtboardDefaults.FractionalHeight
	x.FractionalWidth = ArtboardDefaults.FractionalWidth
	x.Opacity = ArtboardDefaults.Opacity
	x.ScaleX = ArtboardDefaults.ScaleX
	x.ScaleY = ArtboardDefaults.ScaleY
}

// NewArtboard creates a Artboard with required defaults applied.
func NewArtboard() *Artboard {
	x := &Artboard{}
	x.ApplyDefaults()
	return x
}

type nodeDefaults struct {
	Opacity float64
	ScaleX  float64
	ScaleY  float64
}

// NodeDefaults holds required runtime defaults for Node.
var NodeDefaults = nodeDefaults{
	Opacity: 1.0,
	ScaleX:  1.0,
	ScaleY:  1.0,
}

// ApplyDefaults sets required runtime defaults on Node.
func (x *Node) ApplyDefaults() {
	x.Opacity = NodeDefaults.Opacity
	x.ScaleX = NodeDefaults.ScaleX
	x.ScaleY = NodeDefaults.ScaleY
}

// NewNode creates a Node with required defaults applied.
func NewNode() *Node {
	x := &Node{}
	x.ApplyDefaults()
	return x
}

type shapeDefaults struct {
	BlendModeValue uint64
	Opacity        float64
	ScaleX         float64
	ScaleY         float64
}

// ShapeDefaults holds required runtime defaults for Shape.
var ShapeDefaults = shapeDefaults{
	BlendModeValue: 3,
	Opacity:        1.0,
	ScaleX:         1.0,
	ScaleY:         1.0,
}

// ApplyDefaults sets required runtime defaults on Shape.
func (x *Shape) ApplyDefaults() {
	x.BlendModeValue = ShapeDefaults.BlendModeValue
	x.Opacity = ShapeDefaults.Opacity
	x.ScaleX = ShapeDefaults.ScaleX
	x.ScaleY = ShapeDefaults.ScaleY
}

// NewShape creates a Shape with required defaults applied.
func NewShape() *Shape {
	x := &Shape{}
	x.ApplyDefaults()
	return x
}

type rectangleDefaults struct {
	LinkCornerRadius bool
	Opacity          float64
	OriginX          float64
	OriginY          float64
	ScaleX           float64
	ScaleY           float64
}

// RectangleDefaults holds required runtime defaults for Rectangle.
var RectangleDefaults = rectangleDefaults{
	LinkCornerRadius: true,
	Opacity:          1.0,
	OriginX:          0.5,
	OriginY:          0.5,
	ScaleX:           1.0,
	ScaleY:           1.0,
}

// ApplyDefaults sets required runtime defaults on Rectangle.
func (x *Rectangle) ApplyDefaults() {
	x.LinkCornerRadius = RectangleDefaults.LinkCornerRadius
	x.Opacity = RectangleDefaults.Opacity
	x.OriginX = RectangleDefaults.OriginX
	x.OriginY = RectangleDefaults.OriginY
	x.ScaleX = RectangleDefaults.ScaleX
	x.ScaleY = RectangleDefaults.ScaleY
}

// NewRectangle creates a Rectangle with required defaults applied.
func NewRectangle() *Rectangle {
	x := &Rectangle{}
	x.ApplyDefaults()
	return x
}

type ellipseDefaults struct {
	Opacity float64
	OriginX float64
	OriginY float64
	ScaleX  float64
	ScaleY  float64
}

// EllipseDefaults holds required runtime defaults for Ellipse.
var EllipseDefaults = ellipseDefaults{
	Opacity: 1.0,
	OriginX: 0.5,
	OriginY: 0.5,
	ScaleX:  1.0,
	ScaleY:  1.0,
}

// ApplyDefaults sets required runtime defaults on Ellipse.
func (x *Ellipse) ApplyDefaults() {
	x.Opacity = EllipseDefaults.Opacity
	x.OriginX = EllipseDefaults.OriginX
	x.OriginY = EllipseDefaults.OriginY
	x.ScaleX = EllipseDefaults.ScaleX
	x.ScaleY = EllipseDefaults.ScaleY
}

// NewEllipse creates a Ellipse with required defaults applied.
func NewEllipse() *Ellipse {
	x := &Ellipse{}
	x.ApplyDefaults()
	return x
}

type parametricPathDefaults struct {
	Opacity float64
	OriginX float64
	OriginY float64
	ScaleX  float64
	ScaleY  float64
}

// ParametricPathDefaults holds required runtime defaults for ParametricPath.
var ParametricPathDefaults = parametricPathDefaults{
	Opacity: 1.0,
	OriginX: 0.5,
	OriginY: 0.5,
	ScaleX:  1.0,
	ScaleY:  1.0,
}

// ApplyDefaults sets required runtime defaults on ParametricPath.
func (x *ParametricPath) ApplyDefaults() {
	x.Opacity = ParametricPathDefaults.Opacity
	x.OriginX = ParametricPathDefaults.OriginX
	x.OriginY = ParametricPathDefaults.OriginY
	x.ScaleX = ParametricPathDefaults.ScaleX
	x.ScaleY = ParametricPathDefaults.ScaleY
}

// NewParametricPath creates a ParametricPath with required defaults applied.
func NewParametricPath() *ParametricPath {
	x := &ParametricPath{}
	x.ApplyDefaults()
	return x
}

type fillDefaults struct {
	BlendModeValue uint64
	IsVisible      bool
}

// FillDefaults holds required runtime defaults for Fill.
var FillDefaults = fillDefaults{
	BlendModeValue: 127,
	IsVisible:      true,
}

// ApplyDefaults sets required runtime defaults on Fill.
func (x *Fill) ApplyDefaults() {
	x.BlendModeValue = FillDefaults.BlendModeValue
	x.IsVisible = FillDefaults.IsVisible
}

// NewFill creates a Fill with required defaults applied.
func NewFill() *Fill {
	x := &Fill{}
	x.ApplyDefaults()
	return x
}

type strokeDefaults struct {
	BlendModeValue uint64
	IsVisible      bool
	Thickness      float64
}

// StrokeDefaults holds required runtime defaults for Stroke.
var StrokeDefaults = strokeDefaults{
	BlendModeValue: 127,
	IsVisible:      true,
	Thickness:      1.0,
}

// ApplyDefaults sets required runtime defaults on Stroke.
func (x *Stroke) ApplyDefaults() {
	x.BlendModeValue = StrokeDefaults.BlendModeValue
	x.IsVisible = StrokeDefaults.IsVisible
	x.Thickness = StrokeDefaults.Thickness
}

// NewStroke creates a Stroke with required defaults applied.
func NewStroke() *Stroke {
	x := &Stroke{}
	x.ApplyDefaults()
	return x
}

type linearAnimationDefaults struct {
	Fps   uint64
	Speed float64
}

// LinearAnimationDefaults holds required runtime defaults for LinearAnimation.
var LinearAnimationDefaults = linearAnimationDefaults{
	Fps:   60,
	Speed: 1.0,
}

// ApplyDefaults sets required runtime defaults on LinearAnimation.
func (x *LinearAnimation) ApplyDefaults() {
	x.Fps = LinearAnimationDefaults.Fps
	x.Speed = LinearAnimationDefaults.Speed
}

// NewLinearAnimation creates a LinearAnimation with required defaults applied.
func NewLinearAnimation() *LinearAnimation {
	x := &LinearAnimation{}
	x.ApplyDefaults()
	return x
}

type imageDefaults struct {
	BlendModeValue uint64
	Opacity        float64
	ScaleX         float64
	ScaleY         float64
}

// ImageDefaults holds required runtime defaults for Image.
var ImageDefaults = imageDefaults{
	BlendModeValue: 3,
	Opacity:        1.0,
	ScaleX:         1.0,
	ScaleY:         1.0,
}

// ApplyDefaults sets required runtime defaults on Image.
func (x *Image) ApplyDefaults() {
	x.BlendModeValue = ImageDefaults.BlendModeValue
	x.Opacity = ImageDefaults.Opacity
	x.ScaleX = ImageDefaults.ScaleX
	x.ScaleY = ImageDefaults.ScaleY
}

// NewImage creates a Image with required defaults applied.
func NewImage() *Image {
	x := &Image{}
	x.ApplyDefaults()
	return x
}
