// Code generated by rivegen. DO NOT EDIT.
package rive

// ClippingShape (typeKey: 42)
type ClippingShape struct {
	Component
	SourceId  uint64 `rive:"92,uint"`
	FillRule  uint64 `rive:"93,uint"`
	IsVisible bool   `rive:"94,bool"`
}

func (o *ClippingShape) TypeKey() uint32 { return 42 }

func (o *ClippingShape) Properties() []Property {
	props := o.Component.Properties()
	if o.SourceId != ^uint64(0) {
		props = append(props, Property{Key: 92, Type: PropertyTypeUint, Value: o.SourceId})
	}
	if o.FillRule != 0 {
		props = append(props, Property{Key: 93, Type: PropertyTypeUint, Value: o.FillRule})
	}
	if !o.IsVisible {
		props = append(props, Property{Key: 94, Type: PropertyTypeUint, Value: boolToUint64(o.IsVisible)})
	}
	return props
}

// ContourMeshVertex (typeKey: 111)
type ContourMeshVertex struct {
	MeshVertex
}

func (o *ContourMeshVertex) TypeKey() uint32 { return 111 }

func (o *ContourMeshVertex) Properties() []Property {
	return o.MeshVertex.Properties()
}

// CubicAsymmetricVertex (typeKey: 34)
type CubicAsymmetricVertex struct {
	CubicVertex
	Rotation    float64 `rive:"79,float"`
	InDistance  float64 `rive:"80,float"`
	OutDistance float64 `rive:"81,float"`
}

func (o *CubicAsymmetricVertex) TypeKey() uint32 { return 34 }

func (o *CubicAsymmetricVertex) Properties() []Property {
	props := o.CubicVertex.Properties()
	if o.Rotation != 0 {
		props = append(props, Property{Key: 79, Type: PropertyTypeFloat, Value: o.Rotation})
	}
	if o.InDistance != 0 {
		props = append(props, Property{Key: 80, Type: PropertyTypeFloat, Value: o.InDistance})
	}
	if o.OutDistance != 0 {
		props = append(props, Property{Key: 81, Type: PropertyTypeFloat, Value: o.OutDistance})
	}
	return props
}

// CubicDetachedVertex (typeKey: 6)
type CubicDetachedVertex struct {
	CubicVertex
	InRotation  float64 `rive:"84,float"`
	InDistance  float64 `rive:"85,float"`
	OutRotation float64 `rive:"86,float"`
	OutDistance float64 `rive:"87,float"`
}

func (o *CubicDetachedVertex) TypeKey() uint32 { return 6 }

func (o *CubicDetachedVertex) Properties() []Property {
	props := o.CubicVertex.Properties()
	if o.InRotation != 0 {
		props = append(props, Property{Key: 84, Type: PropertyTypeFloat, Value: o.InRotation})
	}
	if o.InDistance != 0 {
		props = append(props, Property{Key: 85, Type: PropertyTypeFloat, Value: o.InDistance})
	}
	if o.OutRotation != 0 {
		props = append(props, Property{Key: 86, Type: PropertyTypeFloat, Value: o.OutRotation})
	}
	if o.OutDistance != 0 {
		props = append(props, Property{Key: 87, Type: PropertyTypeFloat, Value: o.OutDistance})
	}
	return props
}

// CubicMirroredVertex (typeKey: 35)
type CubicMirroredVertex struct {
	CubicVertex
	Rotation float64 `rive:"82,float"`
	Distance float64 `rive:"83,float"`
}

func (o *CubicMirroredVertex) TypeKey() uint32 { return 35 }

func (o *CubicMirroredVertex) Properties() []Property {
	props := o.CubicVertex.Properties()
	if o.Rotation != 0 {
		props = append(props, Property{Key: 82, Type: PropertyTypeFloat, Value: o.Rotation})
	}
	if o.Distance != 0 {
		props = append(props, Property{Key: 83, Type: PropertyTypeFloat, Value: o.Distance})
	}
	return props
}

// CubicVertex (typeKey: 36) [abstract]
type CubicVertex struct {
	PathVertex
}

func (o *CubicVertex) Properties() []Property {
	return o.PathVertex.Properties()
}

// Dash (typeKey: 507)
type Dash struct {
	Component
	Length             float64 `rive:"692,float"`
	LengthIsPercentage bool    `rive:"693,bool"`
}

func (o *Dash) TypeKey() uint32 { return 507 }

func (o *Dash) Properties() []Property {
	props := o.Component.Properties()
	if o.Length != 0 {
		props = append(props, Property{Key: 692, Type: PropertyTypeFloat, Value: o.Length})
	}
	if o.LengthIsPercentage {
		props = append(props, Property{Key: 693, Type: PropertyTypeUint, Value: boolToUint64(o.LengthIsPercentage)})
	}
	return props
}

// DashPath (typeKey: 506)
type DashPath struct {
	ContainerComponent
	Offset             float64 `rive:"690,float"`
	OffsetIsPercentage bool    `rive:"691,bool"`
}

func (o *DashPath) TypeKey() uint32 { return 506 }

func (o *DashPath) Properties() []Property {
	props := o.ContainerComponent.Properties()
	if o.Offset != 0 {
		props = append(props, Property{Key: 690, Type: PropertyTypeFloat, Value: o.Offset})
	}
	if o.OffsetIsPercentage {
		props = append(props, Property{Key: 691, Type: PropertyTypeUint, Value: boolToUint64(o.OffsetIsPercentage)})
	}
	return props
}

// Ellipse (typeKey: 4)
type Ellipse struct {
	ParametricPath
}

func (o *Ellipse) TypeKey() uint32 { return 4 }

func (o *Ellipse) Properties() []Property {
	return o.ParametricPath.Properties()
}

// Feather (typeKey: 533)
type Feather struct {
	ContainerComponent
	SpaceValue uint64  `rive:"748,uint"`
	Strength   float64 `rive:"749,float"`
	OffsetX    float64 `rive:"750,float"`
	OffsetY    float64 `rive:"751,float"`
	Inner      bool    `rive:"752,bool"`
}

func (o *Feather) TypeKey() uint32 { return 533 }

func (o *Feather) Properties() []Property {
	props := o.ContainerComponent.Properties()
	if o.SpaceValue != 0 {
		props = append(props, Property{Key: 748, Type: PropertyTypeUint, Value: o.SpaceValue})
	}
	if o.Strength != 12 {
		props = append(props, Property{Key: 749, Type: PropertyTypeFloat, Value: o.Strength})
	}
	if o.OffsetX != 0 {
		props = append(props, Property{Key: 750, Type: PropertyTypeFloat, Value: o.OffsetX})
	}
	if o.OffsetY != 0 {
		props = append(props, Property{Key: 751, Type: PropertyTypeFloat, Value: o.OffsetY})
	}
	if o.Inner {
		props = append(props, Property{Key: 752, Type: PropertyTypeUint, Value: boolToUint64(o.Inner)})
	}
	return props
}

// Fill (typeKey: 20)
type Fill struct {
	ShapePaint
	FillRule uint64 `rive:"40,uint"`
}

func (o *Fill) TypeKey() uint32 { return 20 }

func (o *Fill) Properties() []Property {
	props := o.ShapePaint.Properties()
	if o.FillRule != 0 {
		props = append(props, Property{Key: 40, Type: PropertyTypeUint, Value: o.FillRule})
	}
	return props
}

// ForcedEdge (typeKey: 112)
type ForcedEdge struct {
	Component
	FromId uint64 `rive:"219,uint"`
	ToId   uint64 `rive:"220,uint"`
}

func (o *ForcedEdge) TypeKey() uint32 { return 112 }

func (o *ForcedEdge) Properties() []Property {
	props := o.Component.Properties()
	if o.FromId != 0 {
		props = append(props, Property{Key: 219, Type: PropertyTypeUint, Value: o.FromId})
	}
	if o.ToId != 0 {
		props = append(props, Property{Key: 220, Type: PropertyTypeUint, Value: o.ToId})
	}
	return props
}

// GradientStop (typeKey: 19)
type GradientStop struct {
	Component
	ColorValue uint32  `rive:"38,color"`
	Position   float64 `rive:"39,float"`
}

func (o *GradientStop) TypeKey() uint32 { return 19 }

func (o *GradientStop) Properties() []Property {
	props := o.Component.Properties()
	if o.ColorValue != 0 {
		props = append(props, Property{Key: 38, Type: PropertyTypeColor, Value: uint64(o.ColorValue)})
	}
	if o.Position != 0 {
		props = append(props, Property{Key: 39, Type: PropertyTypeFloat, Value: o.Position})
	}
	return props
}

// GroupEffect (typeKey: 645)
type GroupEffect struct {
	ContainerComponent
}

func (o *GroupEffect) TypeKey() uint32 { return 645 }

func (o *GroupEffect) Properties() []Property {
	return o.ContainerComponent.Properties()
}

// Image (typeKey: 100)
type Image struct {
	Drawable
	AssetId    uint64  `rive:"206,uint"`
	OriginX    float64 `rive:"380,float"`
	OriginY    float64 `rive:"381,float"`
	Fit        uint64  `rive:"974,uint"`
	AlignmentX float64 `rive:"975,float"`
	AlignmentY float64 `rive:"976,float"`
}

func (o *Image) TypeKey() uint32 { return 100 }

func (o *Image) Properties() []Property {
	props := o.Drawable.Properties()
	if o.AssetId != ^uint64(0) {
		props = append(props, Property{Key: 206, Type: PropertyTypeUint, Value: o.AssetId})
	}
	if o.OriginX != 0.5 {
		props = append(props, Property{Key: 380, Type: PropertyTypeFloat, Value: o.OriginX})
	}
	if o.OriginY != 0.5 {
		props = append(props, Property{Key: 381, Type: PropertyTypeFloat, Value: o.OriginY})
	}
	if o.Fit != 0 {
		props = append(props, Property{Key: 974, Type: PropertyTypeUint, Value: o.Fit})
	}
	if o.AlignmentX != 0 {
		props = append(props, Property{Key: 975, Type: PropertyTypeFloat, Value: o.AlignmentX})
	}
	if o.AlignmentY != 0 {
		props = append(props, Property{Key: 976, Type: PropertyTypeFloat, Value: o.AlignmentY})
	}
	return props
}

// LinearGradient (typeKey: 22)
type LinearGradient struct {
	ContainerComponent
	StartY  float64 `rive:"33,float"`
	EndX    float64 `rive:"34,float"`
	EndY    float64 `rive:"35,float"`
	StartX  float64 `rive:"42,float"`
	Opacity float64 `rive:"46,float"`
}

func (o *LinearGradient) TypeKey() uint32 { return 22 }

func (o *LinearGradient) Properties() []Property {
	props := o.ContainerComponent.Properties()
	if o.StartY != 0 {
		props = append(props, Property{Key: 33, Type: PropertyTypeFloat, Value: o.StartY})
	}
	if o.EndX != 0 {
		props = append(props, Property{Key: 34, Type: PropertyTypeFloat, Value: o.EndX})
	}
	if o.EndY != 0 {
		props = append(props, Property{Key: 35, Type: PropertyTypeFloat, Value: o.EndY})
	}
	if o.StartX != 0 {
		props = append(props, Property{Key: 42, Type: PropertyTypeFloat, Value: o.StartX})
	}
	if o.Opacity != 1 {
		props = append(props, Property{Key: 46, Type: PropertyTypeFloat, Value: o.Opacity})
	}
	return props
}

// ListPath (typeKey: 619)
type ListPath struct {
	PointsCommonPath
	ListSource uint64 `rive:"874,uint"`
}

func (o *ListPath) TypeKey() uint32 { return 619 }

func (o *ListPath) Properties() []Property {
	props := o.PointsCommonPath.Properties()
	if o.ListSource != ^uint64(0) {
		props = append(props, Property{Key: 874, Type: PropertyTypeUint, Value: o.ListSource})
	}
	return props
}

// Mesh (typeKey: 109)
type Mesh struct {
	ContainerComponent
	TriangleIndexBytes []byte `rive:"223,bytes"`
}

func (o *Mesh) TypeKey() uint32 { return 109 }

func (o *Mesh) Properties() []Property {
	props := o.ContainerComponent.Properties()
	if len(o.TriangleIndexBytes) > 0 {
		props = append(props, Property{Key: 223, Type: PropertyTypeBytes, Value: o.TriangleIndexBytes})
	}
	return props
}

// MeshVertex (typeKey: 108)
type MeshVertex struct {
	Vertex
	U float64 `rive:"215,float"`
	V float64 `rive:"216,float"`
}

func (o *MeshVertex) TypeKey() uint32 { return 108 }

func (o *MeshVertex) Properties() []Property {
	props := o.Vertex.Properties()
	if o.U != 0 {
		props = append(props, Property{Key: 215, Type: PropertyTypeFloat, Value: o.U})
	}
	if o.V != 0 {
		props = append(props, Property{Key: 216, Type: PropertyTypeFloat, Value: o.V})
	}
	return props
}

// ParametricPath (typeKey: 15) [abstract]
type ParametricPath struct {
	Path
	Width   float64 `rive:"20,float"`
	Height  float64 `rive:"21,float"`
	OriginX float64 `rive:"123,float"`
	OriginY float64 `rive:"124,float"`
}

func (o *ParametricPath) Properties() []Property {
	props := o.Path.Properties()
	if o.Width != 0 {
		props = append(props, Property{Key: 20, Type: PropertyTypeFloat, Value: o.Width})
	}
	if o.Height != 0 {
		props = append(props, Property{Key: 21, Type: PropertyTypeFloat, Value: o.Height})
	}
	if o.OriginX != 0.5 {
		props = append(props, Property{Key: 123, Type: PropertyTypeFloat, Value: o.OriginX})
	}
	if o.OriginY != 0.5 {
		props = append(props, Property{Key: 124, Type: PropertyTypeFloat, Value: o.OriginY})
	}
	return props
}

// Path (typeKey: 12) [abstract]
type Path struct {
	Node
	PathFlags uint64 `rive:"128,uint"`
	IsHole    bool   `rive:"770,bool"`
}

func (o *Path) Properties() []Property {
	props := o.Node.Properties()
	if o.PathFlags != 0 {
		props = append(props, Property{Key: 128, Type: PropertyTypeUint, Value: o.PathFlags})
	}
	if o.IsHole {
		props = append(props, Property{Key: 770, Type: PropertyTypeUint, Value: boolToUint64(o.IsHole)})
	}
	return props
}

// PathVertex (typeKey: 14) [abstract]
type PathVertex struct {
	Vertex
}

func (o *PathVertex) Properties() []Property {
	return o.Vertex.Properties()
}

// PointsCommonPath (typeKey: 620) [abstract]
type PointsCommonPath struct {
	Path
	IsClosed bool `rive:"32,bool"`
}

func (o *PointsCommonPath) Properties() []Property {
	props := o.Path.Properties()
	if o.IsClosed {
		props = append(props, Property{Key: 32, Type: PropertyTypeUint, Value: boolToUint64(o.IsClosed)})
	}
	return props
}

// PointsPath (typeKey: 16)
type PointsPath struct {
	PointsCommonPath
}

func (o *PointsPath) TypeKey() uint32 { return 16 }

func (o *PointsPath) Properties() []Property {
	return o.PointsCommonPath.Properties()
}

// Polygon (typeKey: 51)
type Polygon struct {
	ParametricPath
	Points       uint64  `rive:"125,uint"`
	CornerRadius float64 `rive:"126,float"`
}

func (o *Polygon) TypeKey() uint32 { return 51 }

func (o *Polygon) Properties() []Property {
	props := o.ParametricPath.Properties()
	if o.Points != 5 {
		props = append(props, Property{Key: 125, Type: PropertyTypeUint, Value: o.Points})
	}
	if o.CornerRadius != 0 {
		props = append(props, Property{Key: 126, Type: PropertyTypeFloat, Value: o.CornerRadius})
	}
	return props
}

// RadialGradient (typeKey: 17)
type RadialGradient struct {
	LinearGradient
}

func (o *RadialGradient) TypeKey() uint32 { return 17 }

func (o *RadialGradient) Properties() []Property {
	return o.LinearGradient.Properties()
}

// Rectangle (typeKey: 7)
type Rectangle struct {
	ParametricPath
	CornerRadiusTL   float64 `rive:"31,float"`
	CornerRadiusTR   float64 `rive:"161,float"`
	CornerRadiusBL   float64 `rive:"162,float"`
	CornerRadiusBR   float64 `rive:"163,float"`
	LinkCornerRadius bool    `rive:"164,bool"`
}

func (o *Rectangle) TypeKey() uint32 { return 7 }

func (o *Rectangle) Properties() []Property {
	props := o.ParametricPath.Properties()
	if o.CornerRadiusTL != 0 {
		props = append(props, Property{Key: 31, Type: PropertyTypeFloat, Value: o.CornerRadiusTL})
	}
	if o.CornerRadiusTR != 0 {
		props = append(props, Property{Key: 161, Type: PropertyTypeFloat, Value: o.CornerRadiusTR})
	}
	if o.CornerRadiusBL != 0 {
		props = append(props, Property{Key: 162, Type: PropertyTypeFloat, Value: o.CornerRadiusBL})
	}
	if o.CornerRadiusBR != 0 {
		props = append(props, Property{Key: 163, Type: PropertyTypeFloat, Value: o.CornerRadiusBR})
	}
	if !o.LinkCornerRadius {
		props = append(props, Property{Key: 164, Type: PropertyTypeUint, Value: boolToUint64(o.LinkCornerRadius)})
	}
	return props
}

// Shape (typeKey: 3)
type Shape struct {
	Drawable
}

func (o *Shape) TypeKey() uint32 { return 3 }

func (o *Shape) Properties() []Property {
	return o.Drawable.Properties()
}

// ShapePaint (typeKey: 21) [abstract]
type ShapePaint struct {
	ContainerComponent
	IsVisible      bool   `rive:"41,bool"`
	BlendModeValue uint64 `rive:"747,uint"`
}

func (o *ShapePaint) Properties() []Property {
	props := o.ContainerComponent.Properties()
	if !o.IsVisible {
		props = append(props, Property{Key: 41, Type: PropertyTypeUint, Value: boolToUint64(o.IsVisible)})
	}
	if o.BlendModeValue != 127 {
		props = append(props, Property{Key: 747, Type: PropertyTypeUint, Value: o.BlendModeValue})
	}
	return props
}

// SolidColor (typeKey: 18)
type SolidColor struct {
	Component
	ColorValue uint32 `rive:"37,color"`
}

func (o *SolidColor) TypeKey() uint32 { return 18 }

func (o *SolidColor) Properties() []Property {
	props := o.Component.Properties()
	if o.ColorValue != 0 {
		props = append(props, Property{Key: 37, Type: PropertyTypeColor, Value: uint64(o.ColorValue)})
	}
	return props
}

// Star (typeKey: 52)
type Star struct {
	Polygon
	InnerRadius float64 `rive:"127,float"`
}

func (o *Star) TypeKey() uint32 { return 52 }

func (o *Star) Properties() []Property {
	props := o.Polygon.Properties()
	if o.InnerRadius != 0.5 {
		props = append(props, Property{Key: 127, Type: PropertyTypeFloat, Value: o.InnerRadius})
	}
	return props
}

// StraightVertex (typeKey: 5)
type StraightVertex struct {
	PathVertex
	Radius float64 `rive:"26,float"`
}

func (o *StraightVertex) TypeKey() uint32 { return 5 }

func (o *StraightVertex) Properties() []Property {
	props := o.PathVertex.Properties()
	if o.Radius != 0 {
		props = append(props, Property{Key: 26, Type: PropertyTypeFloat, Value: o.Radius})
	}
	return props
}

// Stroke (typeKey: 24)
type Stroke struct {
	ShapePaint
	Thickness              float64 `rive:"47,float"`
	Cap                    uint64  `rive:"48,uint"`
	Join                   uint64  `rive:"49,uint"`
	TransformAffectsStroke bool    `rive:"50,bool"`
}

func (o *Stroke) TypeKey() uint32 { return 24 }

func (o *Stroke) Properties() []Property {
	props := o.ShapePaint.Properties()
	if o.Thickness != 1 {
		props = append(props, Property{Key: 47, Type: PropertyTypeFloat, Value: o.Thickness})
	}
	if o.Cap != 0 {
		props = append(props, Property{Key: 48, Type: PropertyTypeUint, Value: o.Cap})
	}
	if o.Join != 0 {
		props = append(props, Property{Key: 49, Type: PropertyTypeUint, Value: o.Join})
	}
	if !o.TransformAffectsStroke {
		props = append(props, Property{Key: 50, Type: PropertyTypeUint, Value: boolToUint64(o.TransformAffectsStroke)})
	}
	return props
}

// TargetEffect (typeKey: 644)
type TargetEffect struct {
	Component
	TargetId uint64 `rive:"922,uint"`
}

func (o *TargetEffect) TypeKey() uint32 { return 644 }

func (o *TargetEffect) Properties() []Property {
	props := o.Component.Properties()
	if o.TargetId != ^uint64(0) {
		props = append(props, Property{Key: 922, Type: PropertyTypeUint, Value: o.TargetId})
	}
	return props
}

// Triangle (typeKey: 8)
type Triangle struct {
	ParametricPath
}

func (o *Triangle) TypeKey() uint32 { return 8 }

func (o *Triangle) Properties() []Property {
	return o.ParametricPath.Properties()
}

// TrimPath (typeKey: 47)
type TrimPath struct {
	Component
	Start     float64 `rive:"114,float"`
	End       float64 `rive:"115,float"`
	Offset    float64 `rive:"116,float"`
	ModeValue uint64  `rive:"117,uint"`
}

func (o *TrimPath) TypeKey() uint32 { return 47 }

func (o *TrimPath) Properties() []Property {
	props := o.Component.Properties()
	if o.Start != 0 {
		props = append(props, Property{Key: 114, Type: PropertyTypeFloat, Value: o.Start})
	}
	if o.End != 0 {
		props = append(props, Property{Key: 115, Type: PropertyTypeFloat, Value: o.End})
	}
	if o.Offset != 0 {
		props = append(props, Property{Key: 116, Type: PropertyTypeFloat, Value: o.Offset})
	}
	if o.ModeValue != 0 {
		props = append(props, Property{Key: 117, Type: PropertyTypeUint, Value: o.ModeValue})
	}
	return props
}

// Vertex (typeKey: 107) [abstract]
type Vertex struct {
	ContainerComponent
	X float64 `rive:"24,float"`
	Y float64 `rive:"25,float"`
}

func (o *Vertex) Properties() []Property {
	props := o.ContainerComponent.Properties()
	if o.X != 0 {
		props = append(props, Property{Key: 24, Type: PropertyTypeFloat, Value: o.X})
	}
	if o.Y != 0 {
		props = append(props, Property{Key: 25, Type: PropertyTypeFloat, Value: o.Y})
	}
	return props
}
