// Code generated by rivegen. DO NOT EDIT.
package rive

// Artboard (typeKey: 1)
type Artboard struct {
	LayoutComponent
	OriginX               float64 `rive:"11,float"`
	OriginY               float64 `rive:"12,float"`
	DefaultStateMachineId uint64  `rive:"236,uint"`
	ViewModelId           uint64  `rive:"583,uint"`
	IsStateful            bool    `rive:"951,bool"`
}

func (o *Artboard) TypeKey() uint32 { return 1 }

func (o *Artboard) Properties() []Property {
	props := o.LayoutComponent.Properties()
	if o.OriginX != 0 {
		props = append(props, Property{Key: 11, Type: PropertyTypeFloat, Value: o.OriginX})
	}
	if o.OriginY != 0 {
		props = append(props, Property{Key: 12, Type: PropertyTypeFloat, Value: o.OriginY})
	}
	if o.DefaultStateMachineId != ^uint64(0) {
		props = append(props, Property{Key: 236, Type: PropertyTypeUint, Value: o.DefaultStateMachineId})
	}
	if o.ViewModelId != ^uint64(0) {
		props = append(props, Property{Key: 583, Type: PropertyTypeUint, Value: o.ViewModelId})
	}
	if o.IsStateful {
		props = append(props, Property{Key: 951, Type: PropertyTypeUint, Value: boolToUint64(o.IsStateful)})
	}
	return props
}

// ArtboardComponentList (typeKey: 559)
type ArtboardComponentList struct {
	Drawable
	ListSource uint64 `rive:"800,uint"`
}

func (o *ArtboardComponentList) TypeKey() uint32 { return 559 }

func (o *ArtboardComponentList) Properties() []Property {
	props := o.Drawable.Properties()
	if o.ListSource != ^uint64(0) {
		props = append(props, Property{Key: 800, Type: PropertyTypeUint, Value: o.ListSource})
	}
	return props
}

// ArtboardListMapRule (typeKey: 648)
type ArtboardListMapRule struct {
	Component
	ArtboardId  uint64 `rive:"934,uint"`
	ViewModelId uint64 `rive:"935,uint"`
}

func (o *ArtboardListMapRule) TypeKey() uint32 { return 648 }

func (o *ArtboardListMapRule) Properties() []Property {
	props := o.Component.Properties()
	if o.ArtboardId != ^uint64(0) {
		props = append(props, Property{Key: 934, Type: PropertyTypeUint, Value: o.ArtboardId})
	}
	if o.ViewModelId != ^uint64(0) {
		props = append(props, Property{Key: 935, Type: PropertyTypeUint, Value: o.ViewModelId})
	}
	return props
}

// AudioEvent (typeKey: 407)
type AudioEvent struct {
	Event
	AssetId uint64 `rive:"408,uint"`
}

func (o *AudioEvent) TypeKey() uint32 { return 407 }

func (o *AudioEvent) Properties() []Property {
	props := o.Event.Properties()
	if o.AssetId != ^uint64(0) {
		props = append(props, Property{Key: 408, Type: PropertyTypeUint, Value: o.AssetId})
	}
	return props
}

// Backboard (typeKey: 23)
type Backboard struct {
}

func (o *Backboard) TypeKey() uint32 { return 23 }

func (o *Backboard) Properties() []Property {
	return nil
}

// ClipboardHeader (typeKey: 146)
type ClipboardHeader struct {
}

func (o *ClipboardHeader) TypeKey() uint32 { return 146 }

func (o *ClipboardHeader) Properties() []Property {
	return nil
}

// Component (typeKey: 10) [abstract]
type Component struct {
	Name     string `rive:"4,string"`
	ParentId uint64 `rive:"5,uint"`
}

func (o *Component) Properties() []Property {
	var props []Property
	if o.Name != "" {
		props = append(props, Property{Key: 4, Type: PropertyTypeString, Value: o.Name})
	}
	if o.ParentId != 0 {
		props = append(props, Property{Key: 5, Type: PropertyTypeUint, Value: o.ParentId})
	}
	return props
}

// ContainerComponent (typeKey: 11) [abstract]
type ContainerComponent struct {
	Component
}

func (o *ContainerComponent) Properties() []Property {
	return o.Component.Properties()
}

// CustomProperty (typeKey: 167) [abstract]
type CustomProperty struct {
	Component
}

func (o *CustomProperty) Properties() []Property {
	return o.Component.Properties()
}

// CustomPropertyBoolean (typeKey: 129)
type CustomPropertyBoolean struct {
	CustomProperty
	PropertyValue bool `rive:"245,bool"`
}

func (o *CustomPropertyBoolean) TypeKey() uint32 { return 129 }

func (o *CustomPropertyBoolean) Properties() []Property {
	props := o.CustomProperty.Properties()
	if o.PropertyValue {
		props = append(props, Property{Key: 245, Type: PropertyTypeUint, Value: boolToUint64(o.PropertyValue)})
	}
	return props
}

// CustomPropertyColor (typeKey: 592)
type CustomPropertyColor struct {
	CustomProperty
	PropertyValue uint32 `rive:"836,color"`
}

func (o *CustomPropertyColor) TypeKey() uint32 { return 592 }

func (o *CustomPropertyColor) Properties() []Property {
	props := o.CustomProperty.Properties()
	if o.PropertyValue != 0 {
		props = append(props, Property{Key: 836, Type: PropertyTypeColor, Value: uint64(o.PropertyValue)})
	}
	return props
}

// CustomPropertyEnum (typeKey: 616)
type CustomPropertyEnum struct {
	CustomProperty
	PropertyValue uint64 `rive:"872,uint"`
	EnumId        uint64 `rive:"873,uint"`
}

func (o *CustomPropertyEnum) TypeKey() uint32 { return 616 }

func (o *CustomPropertyEnum) Properties() []Property {
	props := o.CustomProperty.Properties()
	if o.PropertyValue != ^uint64(0) {
		props = append(props, Property{Key: 872, Type: PropertyTypeUint, Value: o.PropertyValue})
	}
	if o.EnumId != ^uint64(0) {
		props = append(props, Property{Key: 873, Type: PropertyTypeUint, Value: o.EnumId})
	}
	return props
}

// CustomPropertyGroup (typeKey: 548)
type CustomPropertyGroup struct {
	ContainerComponent
}

func (o *CustomPropertyGroup) TypeKey() uint32 { return 548 }

func (o *CustomPropertyGroup) Properties() []Property {
	return o.ContainerComponent.Properties()
}

// CustomPropertyNumber (typeKey: 127)
type CustomPropertyNumber struct {
	CustomProperty
	PropertyValue float64 `rive:"243,float"`
}

func (o *CustomPropertyNumber) TypeKey() uint32 { return 127 }

func (o *CustomPropertyNumber) Properties() []Property {
	props := o.CustomProperty.Properties()
	if o.PropertyValue != 0 {
		props = append(props, Property{Key: 243, Type: PropertyTypeFloat, Value: o.PropertyValue})
	}
	return props
}

// CustomPropertyString (typeKey: 130)
type CustomPropertyString struct {
	CustomProperty
	PropertyValue string `rive:"246,string"`
}

func (o *CustomPropertyString) TypeKey() uint32 { return 130 }

func (o *CustomPropertyString) Properties() []Property {
	props := o.CustomProperty.Properties()
	if o.PropertyValue != "" {
		props = append(props, Property{Key: 246, Type: PropertyTypeString, Value: o.PropertyValue})
	}
	return props
}

// CustomPropertyTrigger (typeKey: 613)
type CustomPropertyTrigger struct {
	CustomProperty
	PropertyValue uint64 `rive:"870,uint"`
}

func (o *CustomPropertyTrigger) TypeKey() uint32 { return 613 }

func (o *CustomPropertyTrigger) Properties() []Property {
	props := o.CustomProperty.Properties()
	if o.PropertyValue != 0 {
		props = append(props, Property{Key: 870, Type: PropertyTypeUint, Value: o.PropertyValue})
	}
	return props
}

// DrawRules (typeKey: 49)
type DrawRules struct {
	ContainerComponent
	DrawTargetId uint64 `rive:"121,uint"`
}

func (o *DrawRules) TypeKey() uint32 { return 49 }

func (o *DrawRules) Properties() []Property {
	props := o.ContainerComponent.Properties()
	if o.DrawTargetId != ^uint64(0) {
		props = append(props, Property{Key: 121, Type: PropertyTypeUint, Value: o.DrawTargetId})
	}
	return props
}

// DrawTarget (typeKey: 48)
type DrawTarget struct {
	Component
	DrawableId     uint64 `rive:"119,uint"`
	PlacementValue uint64 `rive:"120,uint"`
}

func (o *DrawTarget) TypeKey() uint32 { return 48 }

func (o *DrawTarget) Properties() []Property {
	props := o.Component.Properties()
	if o.DrawableId != ^uint64(0) {
		props = append(props, Property{Key: 119, Type: PropertyTypeUint, Value: o.DrawableId})
	}
	if o.PlacementValue != 0 {
		props = append(props, Property{Key: 120, Type: PropertyTypeUint, Value: o.PlacementValue})
	}
	return props
}

// Drawable (typeKey: 13) [abstract]
type Drawable struct {
	Node
	BlendModeValue uint64 `rive:"23,uint"`
	DrawableFlags  uint64 `rive:"129,uint"`
}

func (o *Drawable) Properties() []Property {
	props := o.Node.Properties()
	if o.BlendModeValue != 3 {
		props = append(props, Property{Key: 23, Type: PropertyTypeUint, Value: o.BlendModeValue})
	}
	if o.DrawableFlags != 0 {
		props = append(props, Property{Key: 129, Type: PropertyTypeUint, Value: o.DrawableFlags})
	}
	return props
}

// Event (typeKey: 128)
type Event struct {
	CustomPropertyGroup
}

func (o *Event) TypeKey() uint32 { return 128 }

func (o *Event) Properties() []Property {
	return o.CustomPropertyGroup.Properties()
}

// FocusData (typeKey: 653)
type FocusData struct {
	Component
	CanFocus          bool   `rive:"953,bool"`
	CanTouch          bool   `rive:"954,bool"`
	CanTraverse       bool   `rive:"955,bool"`
	EdgeBehaviorValue uint64 `rive:"956,uint"`
}

func (o *FocusData) TypeKey() uint32 { return 653 }

func (o *FocusData) Properties() []Property {
	props := o.Component.Properties()
	if !o.CanFocus {
		props = append(props, Property{Key: 953, Type: PropertyTypeUint, Value: boolToUint64(o.CanFocus)})
	}
	if !o.CanTouch {
		props = append(props, Property{Key: 954, Type: PropertyTypeUint, Value: boolToUint64(o.CanTouch)})
	}
	if !o.CanTraverse {
		props = append(props, Property{Key: 955, Type: PropertyTypeUint, Value: boolToUint64(o.CanTraverse)})
	}
	if o.EdgeBehaviorValue != 0 {
		props = append(props, Property{Key: 956, Type: PropertyTypeUint, Value: o.EdgeBehaviorValue})
	}
	return props
}

// ForegroundLayoutDrawable (typeKey: 513)
type ForegroundLayoutDrawable struct {
	Drawable
}

func (o *ForegroundLayoutDrawable) TypeKey() uint32 { return 513 }

func (o *ForegroundLayoutDrawable) Properties() []Property {
	return o.Drawable.Properties()
}

// Guide (typeKey: 140)
type Guide struct {
	Component
}

func (o *Guide) TypeKey() uint32 { return 140 }

func (o *Guide) Properties() []Property {
	return o.Component.Properties()
}

// Joystick (typeKey: 148)
type Joystick struct {
	Component
	X              float64 `rive:"299,float"`
	Y              float64 `rive:"300,float"`
	XId            uint64  `rive:"301,uint"`
	YId            uint64  `rive:"302,uint"`
	PosX           float64 `rive:"303,float"`
	PosY           float64 `rive:"304,float"`
	Width          float64 `rive:"305,float"`
	Height         float64 `rive:"306,float"`
	OriginX        float64 `rive:"307,float"`
	OriginY        float64 `rive:"308,float"`
	JoystickFlags  uint64  `rive:"312,uint"`
	HandleSourceId uint64  `rive:"313,uint"`
}

func (o *Joystick) TypeKey() uint32 { return 148 }

func (o *Joystick) Properties() []Property {
	props := o.Component.Properties()
	if o.X != 0 {
		props = append(props, Property{Key: 299, Type: PropertyTypeFloat, Value: o.X})
	}
	if o.Y != 0 {
		props = append(props, Property{Key: 300, Type: PropertyTypeFloat, Value: o.Y})
	}
	if o.XId != ^uint64(0) {
		props = append(props, Property{Key: 301, Type: PropertyTypeUint, Value: o.XId})
	}
	if o.YId != ^uint64(0) {
		props = append(props, Property{Key: 302, Type: PropertyTypeUint, Value: o.YId})
	}
	if o.PosX != 0 {
		props = append(props, Property{Key: 303, Type: PropertyTypeFloat, Value: o.PosX})
	}
	if o.PosY != 0 {
		props = append(props, Property{Key: 304, Type: PropertyTypeFloat, Value: o.PosY})
	}
	if o.Width != 100 {
		props = append(props, Property{Key: 305, Type: PropertyTypeFloat, Value: o.Width})
	}
	if o.Height != 100 {
		props = append(props, Property{Key: 306, Type: PropertyTypeFloat, Value: o.Height})
	}
	if o.OriginX != 0.5 {
		props = append(props, Property{Key: 307, Type: PropertyTypeFloat, Value: o.OriginX})
	}
	if o.OriginY != 0.5 {
		props = append(props, Property{Key: 308, Type: PropertyTypeFloat, Value: o.OriginY})
	}
	if o.JoystickFlags != 0 {
		props = append(props, Property{Key: 312, Type: PropertyTypeUint, Value: o.JoystickFlags})
	}
	if o.HandleSourceId != ^uint64(0) {
		props = append(props, Property{Key: 313, Type: PropertyTypeUint, Value: o.HandleSourceId})
	}
	return props
}

// LayoutComponent (typeKey: 409)
type LayoutComponent struct {
	Drawable
	Width            float64 `rive:"7,float"`
	Height           float64 `rive:"8,float"`
	Clip             bool    `rive:"196,bool"`
	StyleId          uint64  `rive:"494,uint"`
	FractionalWidth  float64 `rive:"706,float"`
	FractionalHeight float64 `rive:"707,float"`
}

func (o *LayoutComponent) TypeKey() uint32 { return 409 }

func (o *LayoutComponent) Properties() []Property {
	props := o.Drawable.Properties()
	if o.Width != 0 {
		props = append(props, Property{Key: 7, Type: PropertyTypeFloat, Value: o.Width})
	}
	if o.Height != 0 {
		props = append(props, Property{Key: 8, Type: PropertyTypeFloat, Value: o.Height})
	}
	if o.Clip {
		props = append(props, Property{Key: 196, Type: PropertyTypeUint, Value: boolToUint64(o.Clip)})
	}
	if o.StyleId != ^uint64(0) {
		props = append(props, Property{Key: 494, Type: PropertyTypeUint, Value: o.StyleId})
	}
	if o.FractionalWidth != 1 {
		props = append(props, Property{Key: 706, Type: PropertyTypeFloat, Value: o.FractionalWidth})
	}
	if o.FractionalHeight != 1 {
		props = append(props, Property{Key: 707, Type: PropertyTypeFloat, Value: o.FractionalHeight})
	}
	return props
}

// NestedAnimation (typeKey: 93) [abstract]
type NestedAnimation struct {
	ContainerComponent
	AnimationId uint64 `rive:"198,uint"`
}

func (o *NestedAnimation) Properties() []Property {
	props := o.ContainerComponent.Properties()
	if o.AnimationId != ^uint64(0) {
		props = append(props, Property{Key: 198, Type: PropertyTypeUint, Value: o.AnimationId})
	}
	return props
}

// NestedArtboard (typeKey: 92)
type NestedArtboard struct {
	Drawable
	ArtboardId      uint64  `rive:"197,uint"`
	DataBindPathIds []byte  `rive:"582,bytes"`
	IsPaused        bool    `rive:"895,bool"`
	Speed           float64 `rive:"907,float"`
	Quantize        float64 `rive:"908,float"`
}

func (o *NestedArtboard) TypeKey() uint32 { return 92 }

func (o *NestedArtboard) Properties() []Property {
	props := o.Drawable.Properties()
	if o.ArtboardId != ^uint64(0) {
		props = append(props, Property{Key: 197, Type: PropertyTypeUint, Value: o.ArtboardId})
	}
	if len(o.DataBindPathIds) > 0 {
		props = append(props, Property{Key: 582, Type: PropertyTypeBytes, Value: o.DataBindPathIds})
	}
	if o.IsPaused {
		props = append(props, Property{Key: 895, Type: PropertyTypeUint, Value: boolToUint64(o.IsPaused)})
	}
	if o.Speed != 1 {
		props = append(props, Property{Key: 907, Type: PropertyTypeFloat, Value: o.Speed})
	}
	if o.Quantize != -1 {
		props = append(props, Property{Key: 908, Type: PropertyTypeFloat, Value: o.Quantize})
	}
	return props
}

// NestedArtboardLayout (typeKey: 452)
type NestedArtboardLayout struct {
	NestedArtboard
	InstanceWidth            float64 `rive:"663,float"`
	InstanceHeight           float64 `rive:"664,float"`
	InstanceWidthUnitsValue  uint64  `rive:"665,uint"`
	InstanceHeightUnitsValue uint64  `rive:"666,uint"`
	InstanceWidthScaleType   uint64  `rive:"667,uint"`
	InstanceHeightScaleType  uint64  `rive:"668,uint"`
}

func (o *NestedArtboardLayout) TypeKey() uint32 { return 452 }

func (o *NestedArtboardLayout) Properties() []Property {
	props := o.NestedArtboard.Properties()
	if o.InstanceWidth != -1 {
		props = append(props, Property{Key: 663, Type: PropertyTypeFloat, Value: o.InstanceWidth})
	}
	if o.InstanceHeight != -1 {
		props = append(props, Property{Key: 664, Type: PropertyTypeFloat, Value: o.InstanceHeight})
	}
	if o.InstanceWidthUnitsValue != 1 {
		props = append(props, Property{Key: 665, Type: PropertyTypeUint, Value: o.InstanceWidthUnitsValue})
	}
	if o.InstanceHeightUnitsValue != 1 {
		props = append(props, Property{Key: 666, Type: PropertyTypeUint, Value: o.InstanceHeightUnitsValue})
	}
	if o.InstanceWidthScaleType != 0 {
		props = append(props, Property{Key: 667, Type: PropertyTypeUint, Value: o.InstanceWidthScaleType})
	}
	if o.InstanceHeightScaleType != 0 {
		props = append(props, Property{Key: 668, Type: PropertyTypeUint, Value: o.InstanceHeightScaleType})
	}
	return props
}

// NestedArtboardLeaf (typeKey: 451)
type NestedArtboardLeaf struct {
	NestedArtboard
	Fit        uint64  `rive:"538,uint"`
	AlignmentX float64 `rive:"644,float"`
	AlignmentY float64 `rive:"645,float"`
}

func (o *NestedArtboardLeaf) TypeKey() uint32 { return 451 }

func (o *NestedArtboardLeaf) Properties() []Property {
	props := o.NestedArtboard.Properties()
	if o.Fit != 0 {
		props = append(props, Property{Key: 538, Type: PropertyTypeUint, Value: o.Fit})
	}
	if o.AlignmentX != 0 {
		props = append(props, Property{Key: 644, Type: PropertyTypeFloat, Value: o.AlignmentX})
	}
	if o.AlignmentY != 0 {
		props = append(props, Property{Key: 645, Type: PropertyTypeFloat, Value: o.AlignmentY})
	}
	return props
}

// Node (typeKey: 2)
type Node struct {
	TransformComponent
	X float64 `rive:"13,float"`
	Y float64 `rive:"14,float"`
}

func (o *Node) TypeKey() uint32 { return 2 }

func (o *Node) Properties() []Property {
	props := o.TransformComponent.Properties()
	if o.X != 0 {
		props = append(props, Property{Key: 13, Type: PropertyTypeFloat, Value: o.X})
	}
	if o.Y != 0 {
		props = append(props, Property{Key: 14, Type: PropertyTypeFloat, Value: o.Y})
	}
	return props
}

// OpenUrlEvent (typeKey: 131)
type OpenUrlEvent struct {
	Event
	Url         string `rive:"248,string"`
	TargetValue uint64 `rive:"249,uint"`
}

func (o *OpenUrlEvent) TypeKey() uint32 { return 131 }

func (o *OpenUrlEvent) Properties() []Property {
	props := o.Event.Properties()
	if o.Url != "" {
		props = append(props, Property{Key: 248, Type: PropertyTypeString, Value: o.Url})
	}
	if o.TargetValue != 0 {
		props = append(props, Property{Key: 249, Type: PropertyTypeUint, Value: o.TargetValue})
	}
	return props
}

// ScriptInputArtboard (typeKey: 621)
type ScriptInputArtboard struct {
	CustomProperty
	ArtboardId uint64 `rive:"876,uint"`
}

func (o *ScriptInputArtboard) TypeKey() uint32 { return 621 }

func (o *ScriptInputArtboard) Properties() []Property {
	props := o.CustomProperty.Properties()
	if o.ArtboardId != ^uint64(0) {
		props = append(props, Property{Key: 876, Type: PropertyTypeUint, Value: o.ArtboardId})
	}
	return props
}

// ScriptInputBoolean (typeKey: 631)
type ScriptInputBoolean struct {
	CustomPropertyBoolean
}

func (o *ScriptInputBoolean) TypeKey() uint32 { return 631 }

func (o *ScriptInputBoolean) Properties() []Property {
	return o.CustomPropertyBoolean.Properties()
}

// ScriptInputColor (typeKey: 626)
type ScriptInputColor struct {
	CustomPropertyColor
}

func (o *ScriptInputColor) TypeKey() uint32 { return 626 }

func (o *ScriptInputColor) Properties() []Property {
	return o.CustomPropertyColor.Properties()
}

// ScriptInputNumber (typeKey: 611)
type ScriptInputNumber struct {
	CustomPropertyNumber
}

func (o *ScriptInputNumber) TypeKey() uint32 { return 611 }

func (o *ScriptInputNumber) Properties() []Property {
	return o.CustomPropertyNumber.Properties()
}

// ScriptInputString (typeKey: 627)
type ScriptInputString struct {
	CustomPropertyString
}

func (o *ScriptInputString) TypeKey() uint32 { return 627 }

func (o *ScriptInputString) Properties() []Property {
	return o.CustomPropertyString.Properties()
}

// ScriptInputTrigger (typeKey: 618)
type ScriptInputTrigger struct {
	CustomPropertyTrigger
}

func (o *ScriptInputTrigger) TypeKey() uint32 { return 618 }

func (o *ScriptInputTrigger) Properties() []Property {
	return o.CustomPropertyTrigger.Properties()
}

// ScriptInputViewModelProperty (typeKey: 612)
type ScriptInputViewModelProperty struct {
	CustomProperty
	DataBindPathIds []byte `rive:"866,bytes"`
}

func (o *ScriptInputViewModelProperty) TypeKey() uint32 { return 612 }

func (o *ScriptInputViewModelProperty) Properties() []Property {
	props := o.CustomProperty.Properties()
	if len(o.DataBindPathIds) > 0 {
		props = append(props, Property{Key: 866, Type: PropertyTypeBytes, Value: o.DataBindPathIds})
	}
	return props
}

// Solo (typeKey: 147)
type Solo struct {
	Node
	ActiveComponentId uint64 `rive:"296,uint"`
}

func (o *Solo) TypeKey() uint32 { return 147 }

func (o *Solo) Properties() []Property {
	props := o.Node.Properties()
	if o.ActiveComponentId != 0 {
		props = append(props, Property{Key: 296, Type: PropertyTypeUint, Value: o.ActiveComponentId})
	}
	return props
}

// Tag (typeKey: 166)
type Tag struct {
}

func (o *Tag) TypeKey() uint32 { return 166 }

func (o *Tag) Properties() []Property {
	return nil
}

// TransformComponent (typeKey: 38) [abstract]
type TransformComponent struct {
	WorldTransformComponent
	Rotation float64 `rive:"15,float"`
	ScaleX   float64 `rive:"16,float"`
	ScaleY   float64 `rive:"17,float"`
}

func (o *TransformComponent) Properties() []Property {
	props := o.WorldTransformComponent.Properties()
	if o.Rotation != 0 {
		props = append(props, Property{Key: 15, Type: PropertyTypeFloat, Value: o.Rotation})
	}
	if o.ScaleX != 1 {
		props = append(props, Property{Key: 16, Type: PropertyTypeFloat, Value: o.ScaleX})
	}
	if o.ScaleY != 1 {
		props = append(props, Property{Key: 17, Type: PropertyTypeFloat, Value: o.ScaleY})
	}
	return props
}

// WorldTransformComponent (typeKey: 91) [abstract]
type WorldTransformComponent struct {
	ContainerComponent
	Opacity float64 `rive:"18,float"`
}

func (o *WorldTransformComponent) Properties() []Property {
	props := o.ContainerComponent.Properties()
	if o.Opacity != 1 {
		props = append(props, Property{Key: 18, Type: PropertyTypeFloat, Value: o.Opacity})
	}
	return props
}
