// Code generated by rivegen. DO NOT EDIT.
package rive

// AdvanceableState (typeKey: 145) [abstract]
type AdvanceableState struct {
	LayerState
	Speed float64 `rive:"292,float"`
}

func (o *AdvanceableState) Properties() []Property {
	props := o.LayerState.Properties()
	if o.Speed != 1 {
		props = append(props, Property{Key: 292, Type: PropertyTypeFloat, Value: o.Speed})
	}
	return props
}

// Animation (typeKey: 27)
type Animation struct {
	Name string `rive:"55,string"`
}

func (o *Animation) TypeKey() uint32 { return 27 }

func (o *Animation) Properties() []Property {
	var props []Property
	if o.Name != "" {
		props = append(props, Property{Key: 55, Type: PropertyTypeString, Value: o.Name})
	}
	return props
}

// AnimationFolder (typeKey: 143)
type AnimationFolder struct {
	Animation
}

func (o *AnimationFolder) TypeKey() uint32 { return 143 }

func (o *AnimationFolder) Properties() []Property {
	return o.Animation.Properties()
}

// AnimationState (typeKey: 61)
type AnimationState struct {
	AdvanceableState
	AnimationId uint64 `rive:"149,uint"`
}

func (o *AnimationState) TypeKey() uint32 { return 61 }

func (o *AnimationState) Properties() []Property {
	props := o.AdvanceableState.Properties()
	if o.AnimationId != ^uint64(0) {
		props = append(props, Property{Key: 149, Type: PropertyTypeUint, Value: o.AnimationId})
	}
	return props
}

// AnyState (typeKey: 62)
type AnyState struct {
	LayerState
}

func (o *AnyState) TypeKey() uint32 { return 62 }

func (o *AnyState) Properties() []Property {
	return o.LayerState.Properties()
}

// BlendAnimation (typeKey: 74) [abstract]
type BlendAnimation struct {
	AnimationId uint64 `rive:"165,uint"`
}

func (o *BlendAnimation) Properties() []Property {
	var props []Property
	if o.AnimationId != ^uint64(0) {
		props = append(props, Property{Key: 165, Type: PropertyTypeUint, Value: o.AnimationId})
	}
	return props
}

// BlendAnimation1D (typeKey: 75)
type BlendAnimation1D struct {
	BlendAnimation
	Value float64 `rive:"166,float"`
}

func (o *BlendAnimation1D) TypeKey() uint32 { return 75 }

func (o *BlendAnimation1D) Properties() []Property {
	props := o.BlendAnimation.Properties()
	if o.Value != 0 {
		props = append(props, Property{Key: 166, Type: PropertyTypeFloat, Value: o.Value})
	}
	return props
}

// BlendAnimationDirect (typeKey: 77)
type BlendAnimationDirect struct {
	BlendAnimation
	InputId     uint64  `rive:"168,uint"`
	MixValue    float64 `rive:"297,float"`
	BlendSource uint64  `rive:"298,uint"`
}

func (o *BlendAnimationDirect) TypeKey() uint32 { return 77 }

func (o *BlendAnimationDirect) Properties() []Property {
	props := o.BlendAnimation.Properties()
	if o.InputId != ^uint64(0) {
		props = append(props, Property{Key: 168, Type: PropertyTypeUint, Value: o.InputId})
	}
	if o.MixValue != 100 {
		props = append(props, Property{Key: 297, Type: PropertyTypeFloat, Value: o.MixValue})
	}
	if o.BlendSource != 0 {
		props = append(props, Property{Key: 298, Type: PropertyTypeUint, Value: o.BlendSource})
	}
	return props
}

// BlendState (typeKey: 72) [abstract]
type BlendState struct {
	LayerState
}

func (o *BlendState) Properties() []Property {
	return o.LayerState.Properties()
}

// BlendState1D (typeKey: 527) [abstract]
type BlendState1D struct {
	BlendState
}

func (o *BlendState1D) Properties() []Property {
	return o.BlendState.Properties()
}

// BlendState1DInput (typeKey: 76)
type BlendState1DInput struct {
	BlendState1D
	InputId uint64 `rive:"167,uint"`
}

func (o *BlendState1DInput) TypeKey() uint32 { return 76 }

func (o *BlendState1DInput) Properties() []Property {
	props := o.BlendState1D.Properties()
	if o.InputId != ^uint64(0) {
		props = append(props, Property{Key: 167, Type: PropertyTypeUint, Value: o.InputId})
	}
	return props
}

// BlendState1DViewModel (typeKey: 528)
type BlendState1DViewModel struct {
	BlendState1D
}

func (o *BlendState1DViewModel) TypeKey() uint32 { return 528 }

func (o *BlendState1DViewModel) Properties() []Property {
	return o.BlendState1D.Properties()
}

// BlendStateDirect (typeKey: 73)
type BlendStateDirect struct {
	BlendState
}

func (o *BlendStateDirect) TypeKey() uint32 { return 73 }

func (o *BlendStateDirect) Properties() []Property {
	return o.BlendState.Properties()
}

// BlendStateTransition (typeKey: 78)
type BlendStateTransition struct {
	StateTransition
	ExitBlendAnimationId uint64 `rive:"171,uint"`
}

func (o *BlendStateTransition) TypeKey() uint32 { return 78 }

func (o *BlendStateTransition) Properties() []Property {
	props := o.StateTransition.Properties()
	if o.ExitBlendAnimationId != ^uint64(0) {
		props = append(props, Property{Key: 171, Type: PropertyTypeUint, Value: o.ExitBlendAnimationId})
	}
	return props
}

// CubicEaseInterpolator (typeKey: 28)
type CubicEaseInterpolator struct {
	CubicInterpolator
}

func (o *CubicEaseInterpolator) TypeKey() uint32 { return 28 }

func (o *CubicEaseInterpolator) Properties() []Property {
	return o.CubicInterpolator.Properties()
}

// CubicInterpolator (typeKey: 139) [abstract]
type CubicInterpolator struct {
	KeyFrameInterpolator
	X1 float64 `rive:"63,float"`
	Y1 float64 `rive:"64,float"`
	X2 float64 `rive:"65,float"`
	Y2 float64 `rive:"66,float"`
}

func (o *CubicInterpolator) Properties() []Property {
	props := o.KeyFrameInterpolator.Properties()
	if o.X1 != 0.42 {
		props = append(props, Property{Key: 63, Type: PropertyTypeFloat, Value: o.X1})
	}
	if o.Y1 != 0 {
		props = append(props, Property{Key: 64, Type: PropertyTypeFloat, Value: o.Y1})
	}
	if o.X2 != 0.58 {
		props = append(props, Property{Key: 65, Type: PropertyTypeFloat, Value: o.X2})
	}
	if o.Y2 != 1 {
		props = append(props, Property{Key: 66, Type: PropertyTypeFloat, Value: o.Y2})
	}
	return props
}

// CubicInterpolatorComponent (typeKey: 163)
type CubicInterpolatorComponent struct {
	Component
	X1 float64 `rive:"337,float"`
	Y1 float64 `rive:"338,float"`
	X2 float64 `rive:"339,float"`
	Y2 float64 `rive:"340,float"`
}

func (o *CubicInterpolatorComponent) TypeKey() uint32 { return 163 }

func (o *CubicInterpolatorComponent) Properties() []Property {
	props := o.Component.Properties()
	if o.X1 != 0.42 {
		props = append(props, Property{Key: 337, Type: PropertyTypeFloat, Value: o.X1})
	}
	if o.Y1 != 0 {
		props = append(props, Property{Key: 338, Type: PropertyTypeFloat, Value: o.Y1})
	}
	if o.X2 != 0.58 {
		props = append(props, Property{Key: 339, Type: PropertyTypeFloat, Value: o.X2})
	}
	if o.Y2 != 1 {
		props = append(props, Property{Key: 340, Type: PropertyTypeFloat, Value: o.Y2})
	}
	return props
}

// CubicValueInterpolator (typeKey: 138)
type CubicValueInterpolator struct {
	CubicInterpolator
}

func (o *CubicValueInterpolator) TypeKey() uint32 { return 138 }

func (o *CubicValueInterpolator) Properties() []Property {
	return o.CubicInterpolator.Properties()
}

// ElasticInterpolator (typeKey: 174)
type ElasticInterpolator struct {
	KeyFrameInterpolator
	EasingValue uint64  `rive:"405,uint"`
	Amplitude   float64 `rive:"406,float"`
	Period      float64 `rive:"407,float"`
}

func (o *ElasticInterpolator) TypeKey() uint32 { return 174 }

func (o *ElasticInterpolator) Properties() []Property {
	props := o.KeyFrameInterpolator.Properties()
	if o.EasingValue != 1 {
		props = append(props, Property{Key: 405, Type: PropertyTypeUint, Value: o.EasingValue})
	}
	if o.Amplitude != 1 {
		props = append(props, Property{Key: 406, Type: PropertyTypeFloat, Value: o.Amplitude})
	}
	if o.Period != 1 {
		props = append(props, Property{Key: 407, Type: PropertyTypeFloat, Value: o.Period})
	}
	return props
}

// EntryState (typeKey: 63)
type EntryState struct {
	LayerState
}

func (o *EntryState) TypeKey() uint32 { return 63 }

func (o *EntryState) Properties() []Property {
	return o.LayerState.Properties()
}

// ExitState (typeKey: 64)
type ExitState struct {
	LayerState
}

func (o *ExitState) TypeKey() uint32 { return 64 }

func (o *ExitState) Properties() []Property {
	return o.LayerState.Properties()
}

// FocusAction (typeKey: 671) [abstract]
type FocusAction struct {
	ListenerAction
}

func (o *FocusAction) Properties() []Property {
	return o.ListenerAction.Properties()
}

// FocusActionTarget (typeKey: 652)
type FocusActionTarget struct {
	FocusAction
	TargetId uint64 `rive:"952,uint"`
}

func (o *FocusActionTarget) TypeKey() uint32 { return 652 }

func (o *FocusActionTarget) Properties() []Property {
	props := o.FocusAction.Properties()
	if o.TargetId != ^uint64(0) {
		props = append(props, Property{Key: 952, Type: PropertyTypeUint, Value: o.TargetId})
	}
	return props
}

// FocusActionTraversal (typeKey: 672)
type FocusActionTraversal struct {
	FocusAction
	TraversalKind uint64 `rive:"1011,uint"`
}

func (o *FocusActionTraversal) TypeKey() uint32 { return 672 }

func (o *FocusActionTraversal) Properties() []Property {
	props := o.FocusAction.Properties()
	if o.TraversalKind != 0 {
		props = append(props, Property{Key: 1011, Type: PropertyTypeUint, Value: o.TraversalKind})
	}
	return props
}

// InterpolatingKeyFrame (typeKey: 170) [abstract]
type InterpolatingKeyFrame struct {
	KeyFrame
	InterpolationType uint64 `rive:"68,uint"`
	InterpolatorId    uint64 `rive:"69,uint"`
}

func (o *InterpolatingKeyFrame) Properties() []Property {
	props := o.KeyFrame.Properties()
	if o.InterpolationType != 0 {
		props = append(props, Property{Key: 68, Type: PropertyTypeUint, Value: o.InterpolationType})
	}
	if o.InterpolatorId != ^uint64(0) {
		props = append(props, Property{Key: 69, Type: PropertyTypeUint, Value: o.InterpolatorId})
	}
	return props
}

// KeyFrame (typeKey: 29) [abstract]
type KeyFrame struct {
	Frame uint64 `rive:"67,uint"`
}

func (o *KeyFrame) Properties() []Property {
	var props []Property
	if o.Frame != 0 {
		props = append(props, Property{Key: 67, Type: PropertyTypeUint, Value: o.Frame})
	}
	return props
}

// KeyFrameBool (typeKey: 84)
type KeyFrameBool struct {
	InterpolatingKeyFrame
	Value bool `rive:"181,bool"`
}

func (o *KeyFrameBool) TypeKey() uint32 { return 84 }

func (o *KeyFrameBool) Properties() []Property {
	props := o.InterpolatingKeyFrame.Properties()
	if o.Value {
		props = append(props, Property{Key: 181, Type: PropertyTypeUint, Value: boolToUint64(o.Value)})
	}
	return props
}

// KeyFrameCallback (typeKey: 171)
type KeyFrameCallback struct {
	KeyFrame
}

func (o *KeyFrameCallback) TypeKey() uint32 { return 171 }

func (o *KeyFrameCallback) Properties() []Property {
	return o.KeyFrame.Properties()
}

// KeyFrameColor (typeKey: 37)
type KeyFrameColor struct {
	InterpolatingKeyFrame
	Value uint32 `rive:"88,color"`
}

func (o *KeyFrameColor) TypeKey() uint32 { return 37 }

func (o *KeyFrameColor) Properties() []Property {
	props := o.InterpolatingKeyFrame.Properties()
	if o.Value != 0 {
		props = append(props, Property{Key: 88, Type: PropertyTypeColor, Value: uint64(o.Value)})
	}
	return props
}

// KeyFrameDouble (typeKey: 30)
type KeyFrameDouble struct {
	InterpolatingKeyFrame
	Value float64 `rive:"70,float"`
}

func (o *KeyFrameDouble) TypeKey() uint32 { return 30 }

func (o *KeyFrameDouble) Properties() []Property {
	props := o.InterpolatingKeyFrame.Properties()
	if o.Value != 0 {
		props = append(props, Property{Key: 70, Type: PropertyTypeFloat, Value: o.Value})
	}
	return props
}

// KeyFrameId (typeKey: 50)
type KeyFrameId struct {
	InterpolatingKeyFrame
	Value uint64 `rive:"122,uint"`
}

func (o *KeyFrameId) TypeKey() uint32 { return 50 }

func (o *KeyFrameId) Properties() []Property {
	props := o.InterpolatingKeyFrame.Properties()
	if o.Value != ^uint64(0) {
		props = append(props, Property{Key: 122, Type: PropertyTypeUint, Value: o.Value})
	}
	return props
}

// KeyFrameInterpolator (typeKey: 175) [abstract]
type KeyFrameInterpolator struct {
}

func (o *KeyFrameInterpolator) Properties() []Property {
	return nil
}

// KeyFrameString (typeKey: 142)
type KeyFrameString struct {
	InterpolatingKeyFrame
	Value string `rive:"280,string"`
}

func (o *KeyFrameString) TypeKey() uint32 { return 142 }

func (o *KeyFrameString) Properties() []Property {
	props := o.InterpolatingKeyFrame.Properties()
	if o.Value != "" {
		props = append(props, Property{Key: 280, Type: PropertyTypeString, Value: o.Value})
	}
	return props
}

// KeyFrameUint (typeKey: 450)
type KeyFrameUint struct {
	InterpolatingKeyFrame
	Value uint64 `rive:"631,uint"`
}

func (o *KeyFrameUint) TypeKey() uint32 { return 450 }

func (o *KeyFrameUint) Properties() []Property {
	props := o.InterpolatingKeyFrame.Properties()
	if o.Value != 0 {
		props = append(props, Property{Key: 631, Type: PropertyTypeUint, Value: o.Value})
	}
	return props
}

// KeyedObject (typeKey: 25)
type KeyedObject struct {
	ObjectId uint64 `rive:"51,uint"`
}

func (o *KeyedObject) TypeKey() uint32 { return 25 }

func (o *KeyedObject) Properties() []Property {
	var props []Property
	if o.ObjectId != 0 {
		props = append(props, Property{Key: 51, Type: PropertyTypeUint, Value: o.ObjectId})
	}
	return props
}

// KeyedProperty (typeKey: 26)
type KeyedProperty struct {
	PropertyKey uint64 `rive:"53,uint"`
}

func (o *KeyedProperty) TypeKey() uint32 { return 26 }

func (o *KeyedProperty) Properties() []Property {
	var props []Property
	if o.PropertyKey != 0 {
		props = append(props, Property{Key: 53, Type: PropertyTypeUint, Value: o.PropertyKey})
	}
	return props
}

// LayerState (typeKey: 60) [abstract]
type LayerState struct {
	StateMachineLayerComponent
	Flags uint64 `rive:"536,uint"`
}

func (o *LayerState) Properties() []Property {
	props := o.StateMachineLayerComponent.Properties()
	if o.Flags != 0 {
		props = append(props, Property{Key: 536, Type: PropertyTypeUint, Value: o.Flags})
	}
	return props
}

// LinearAnimation (typeKey: 31)
type LinearAnimation struct {
	LinearAnimationResolver
	Fps            uint64  `rive:"56,uint"`
	Duration       uint64  `rive:"57,uint"`
	Speed          float64 `rive:"58,float"`
	LoopValue      uint64  `rive:"59,uint"`
	WorkStart      uint64  `rive:"60,uint"`
	WorkEnd        uint64  `rive:"61,uint"`
	EnableWorkArea bool    `rive:"62,bool"`
	Quantize       bool    `rive:"376,bool"`
}

func (o *LinearAnimation) TypeKey() uint32 { return 31 }

func (o *LinearAnimation) Properties() []Property {
	props := o.LinearAnimationResolver.Properties()
	if o.Fps != 60 {
		props = append(props, Property{Key: 56, Type: PropertyTypeUint, Value: o.Fps})
	}
	if o.Duration != 60 {
		props = append(props, Property{Key: 57, Type: PropertyTypeUint, Value: o.Duration})
	}
	if o.Speed != 1 {
		props = append(props, Property{Key: 58, Type: PropertyTypeFloat, Value: o.Speed})
	}
	if o.LoopValue != 0 {
		props = append(props, Property{Key: 59, Type: PropertyTypeUint, Value: o.LoopValue})
	}
	if o.WorkStart != ^uint64(0) {
		props = append(props, Property{Key: 60, Type: PropertyTypeUint, Value: o.WorkStart})
	}
	if o.WorkEnd != ^uint64(0) {
		props = append(props, Property{Key: 61, Type: PropertyTypeUint, Value: o.WorkEnd})
	}
	if o.EnableWorkArea {
		props = append(props, Property{Key: 62, Type: PropertyTypeUint, Value: boolToUint64(o.EnableWorkArea)})
	}
	if o.Quantize {
		props = append(props, Property{Key: 376, Type: PropertyTypeUint, Value: boolToUint64(o.Quantize)})
	}
	return props
}

// LinearAnimationResolver (typeKey: 550) [abstract]
type LinearAnimationResolver struct {
	Animation
}

func (o *LinearAnimationResolver) Properties() []Property {
	return o.Animation.Properties()
}

// ListenerAction (typeKey: 125) [abstract]
type ListenerAction struct {
	Flags uint64 `rive:"980,uint"`
}

func (o *ListenerAction) Properties() []Property {
	var props []Property
	if o.Flags != 0 {
		props = append(props, Property{Key: 980, Type: PropertyTypeUint, Value: o.Flags})
	}
	return props
}

// ListenerAlignTarget (typeKey: 126)
type ListenerAlignTarget struct {
	ListenerAction
	TargetId       uint64 `rive:"240,uint"`
	PreserveOffset bool   `rive:"541,bool"`
}

func (o *ListenerAlignTarget) TypeKey() uint32 { return 126 }

func (o *ListenerAlignTarget) Properties() []Property {
	props := o.ListenerAction.Properties()
	if o.TargetId != ^uint64(0) {
		props = append(props, Property{Key: 240, Type: PropertyTypeUint, Value: o.TargetId})
	}
	if o.PreserveOffset {
		props = append(props, Property{Key: 541, Type: PropertyTypeUint, Value: boolToUint64(o.PreserveOffset)})
	}
	return props
}

// ListenerBoolChange (typeKey: 117)
type ListenerBoolChange struct {
	ListenerInputChange
	Value uint64 `rive:"228,uint"`
}

func (o *ListenerBoolChange) TypeKey() uint32 { return 117 }

func (o *ListenerBoolChange) Properties() []Property {
	props := o.ListenerInputChange.Properties()
	if o.Value != 1 {
		props = append(props, Property{Key: 228, Type: PropertyTypeUint, Value: o.Value})
	}
	return props
}

// ListenerFireEvent (typeKey: 168)
type ListenerFireEvent struct {
	ListenerAction
	EventId uint64 `rive:"389,uint"`
}

func (o *ListenerFireEvent) TypeKey() uint32 { return 168 }

func (o *ListenerFireEvent) Properties() []Property {
	props := o.ListenerAction.Properties()
	if o.EventId != ^uint64(0) {
		props = append(props, Property{Key: 389, Type: PropertyTypeUint, Value: o.EventId})
	}
	return props
}

// ListenerInputChange (typeKey: 116) [abstract]
type ListenerInputChange struct {
	ListenerAction
	InputId       uint64 `rive:"227,uint"`
	NestedInputId uint64 `rive:"400,uint"`
}

func (o *ListenerInputChange) Properties() []Property {
	props := o.ListenerAction.Properties()
	if o.InputId != ^uint64(0) {
		props = append(props, Property{Key: 227, Type: PropertyTypeUint, Value: o.InputId})
	}
	if o.NestedInputId != ^uint64(0) {
		props = append(props, Property{Key: 400, Type: PropertyTypeUint, Value: o.NestedInputId})
	}
	return props
}

// ListenerInputType (typeKey: 658)
type ListenerInputType struct {
	ListenerTypeValue uint64 `rive:"965,uint"`
}

func (o *ListenerInputType) TypeKey() uint32 { return 658 }

func (o *ListenerInputType) Properties() []Property {
	var props []Property
	if o.ListenerTypeValue != 0 {
		props = append(props, Property{Key: 965, Type: PropertyTypeUint, Value: o.ListenerTypeValue})
	}
	return props
}

// ListenerInputTypeEvent (typeKey: 659)
type ListenerInputTypeEvent struct {
	ListenerInputType
	EventId uint64 `rive:"962,uint"`
}

func (o *ListenerInputTypeEvent) TypeKey() uint32 { return 659 }

func (o *ListenerInputTypeEvent) Properties() []Property {
	props := o.ListenerInputType.Properties()
	if o.EventId != ^uint64(0) {
		props = append(props, Property{Key: 962, Type: PropertyTypeUint, Value: o.EventId})
	}
	return props
}

// ListenerInputTypeKeyboard (typeKey: 665)
type ListenerInputTypeKeyboard struct {
	ListenerInputType
}

func (o *ListenerInputTypeKeyboard) TypeKey() uint32 { return 665 }

func (o *ListenerInputTypeKeyboard) Properties() []Property {
	return o.ListenerInputType.Properties()
}

// ListenerInputTypeSemantic (typeKey: 669)
type ListenerInputTypeSemantic struct {
	ListenerInputType
}

func (o *ListenerInputTypeSemantic) TypeKey() uint32 { return 669 }

func (o *ListenerInputTypeSemantic) Properties() []Property {
	return o.ListenerInputType.Properties()
}

// ListenerInputTypeText (typeKey: 666)
type ListenerInputTypeText struct {
	ListenerInputType
}

func (o *ListenerInputTypeText) TypeKey() uint32 { return 666 }

func (o *ListenerInputTypeText) Properties() []Property {
	return o.ListenerInputType.Properties()
}

// ListenerInputTypeViewModel (typeKey: 660)
type ListenerInputTypeViewModel struct {
	ListenerInputType
	ViewModelPathIds []byte `rive:"963,bytes"`
}

func (o *ListenerInputTypeViewModel) TypeKey() uint32 { return 660 }

func (o *ListenerInputTypeViewModel) Properties() []Property {
	props := o.ListenerInputType.Properties()
	if len(o.ViewModelPathIds) > 0 {
		props = append(props, Property{Key: 963, Type: PropertyTypeBytes, Value: o.ViewModelPathIds})
	}
	return props
}

// ListenerNumberChange (typeKey: 118)
type ListenerNumberChange struct {
	ListenerInputChange
	Value float64 `rive:"229,float"`
}

func (o *ListenerNumberChange) TypeKey() uint32 { return 118 }

func (o *ListenerNumberChange) Properties() []Property {
	props := o.ListenerInputChange.Properties()
	if o.Value != 0 {
		props = append(props, Property{Key: 229, Type: PropertyTypeFloat, Value: o.Value})
	}
	return props
}

// ListenerTriggerChange (typeKey: 115)
type ListenerTriggerChange struct {
	ListenerInputChange
}

func (o *ListenerTriggerChange) TypeKey() uint32 { return 115 }

func (o *ListenerTriggerChange) Properties() []Property {
	return o.ListenerInputChange.Properties()
}

// ListenerViewModelChange (typeKey: 487)
type ListenerViewModelChange struct {
	ListenerAction
}

func (o *ListenerViewModelChange) TypeKey() uint32 { return 487 }

func (o *ListenerViewModelChange) Properties() []Property {
	return o.ListenerAction.Properties()
}

// NestedBool (typeKey: 123)
type NestedBool struct {
	NestedInput
	NestedValue bool `rive:"238,bool"`
}

func (o *NestedBool) TypeKey() uint32 { return 123 }

func (o *NestedBool) Properties() []Property {
	props := o.NestedInput.Properties()
	if o.NestedValue {
		props = append(props, Property{Key: 238, Type: PropertyTypeUint, Value: boolToUint64(o.NestedValue)})
	}
	return props
}

// NestedInput (typeKey: 121) [abstract]
type NestedInput struct {
	Component
	InputId uint64 `rive:"237,uint"`
}

func (o *NestedInput) Properties() []Property {
	props := o.Component.Properties()
	if o.InputId != ^uint64(0) {
		props = append(props, Property{Key: 237, Type: PropertyTypeUint, Value: o.InputId})
	}
	return props
}

// NestedLinearAnimation (typeKey: 97) [abstract]
type NestedLinearAnimation struct {
	NestedAnimation
	Mix float64 `rive:"200,float"`
}

func (o *NestedLinearAnimation) Properties() []Property {
	props := o.NestedAnimation.Properties()
	if o.Mix != 1 {
		props = append(props, Property{Key: 200, Type: PropertyTypeFloat, Value: o.Mix})
	}
	return props
}

// NestedNumber (typeKey: 124)
type NestedNumber struct {
	NestedInput
	NestedValue float64 `rive:"239,float"`
}

func (o *NestedNumber) TypeKey() uint32 { return 124 }

func (o *NestedNumber) Properties() []Property {
	props := o.NestedInput.Properties()
	if o.NestedValue != 0 {
		props = append(props, Property{Key: 239, Type: PropertyTypeFloat, Value: o.NestedValue})
	}
	return props
}

// NestedRemapAnimation (typeKey: 98)
type NestedRemapAnimation struct {
	NestedLinearAnimation
	Time float64 `rive:"202,float"`
}

func (o *NestedRemapAnimation) TypeKey() uint32 { return 98 }

func (o *NestedRemapAnimation) Properties() []Property {
	props := o.NestedLinearAnimation.Properties()
	if o.Time != 0 {
		props = append(props, Property{Key: 202, Type: PropertyTypeFloat, Value: o.Time})
	}
	return props
}

// NestedSimpleAnimation (typeKey: 96)
type NestedSimpleAnimation struct {
	NestedLinearAnimation
	Speed     float64 `rive:"199,float"`
	IsPlaying bool    `rive:"201,bool"`
}

func (o *NestedSimpleAnimation) TypeKey() uint32 { return 96 }

func (o *NestedSimpleAnimation) Properties() []Property {
	props := o.NestedLinearAnimation.Properties()
	if o.Speed != 1 {
		props = append(props, Property{Key: 199, Type: PropertyTypeFloat, Value: o.Speed})
	}
	if o.IsPlaying {
		props = append(props, Property{Key: 201, Type: PropertyTypeUint, Value: boolToUint64(o.IsPlaying)})
	}
	return props
}

// NestedStateMachine (typeKey: 95)
type NestedStateMachine struct {
	NestedAnimation
}

func (o *NestedStateMachine) TypeKey() uint32 { return 95 }

func (o *NestedStateMachine) Properties() []Property {
	return o.NestedAnimation.Properties()
}

// NestedTrigger (typeKey: 122)
type NestedTrigger struct {
	NestedInput
}

func (o *NestedTrigger) TypeKey() uint32 { return 122 }

func (o *NestedTrigger) Properties() []Property {
	return o.NestedInput.Properties()
}

// ScriptedListenerAction (typeKey: 646)
type ScriptedListenerAction struct {
	ListenerAction
	ScriptAssetId uint64 `rive:"930,uint"`
}

func (o *ScriptedListenerAction) TypeKey() uint32 { return 646 }

func (o *ScriptedListenerAction) Properties() []Property {
	props := o.ListenerAction.Properties()
	if o.ScriptAssetId != ^uint64(0) {
		props = append(props, Property{Key: 930, Type: PropertyTypeUint, Value: o.ScriptAssetId})
	}
	return props
}

// ScriptedTransitionCondition (typeKey: 647)
type ScriptedTransitionCondition struct {
	TransitionCondition
	ScriptAssetId uint64 `rive:"931,uint"`
}

func (o *ScriptedTransitionCondition) TypeKey() uint32 { return 647 }

func (o *ScriptedTransitionCondition) Properties() []Property {
	props := o.TransitionCondition.Properties()
	if o.ScriptAssetId != ^uint64(0) {
		props = append(props, Property{Key: 931, Type: PropertyTypeUint, Value: o.ScriptAssetId})
	}
	return props
}

// StateMachine (typeKey: 53)
type StateMachine struct {
	StateMachineResolver
}

func (o *StateMachine) TypeKey() uint32 { return 53 }

func (o *StateMachine) Properties() []Property {
	return o.StateMachineResolver.Properties()
}

// StateMachineBool (typeKey: 59)
type StateMachineBool struct {
	StateMachineInput
	Value bool `rive:"141,bool"`
}

func (o *StateMachineBool) TypeKey() uint32 { return 59 }

func (o *StateMachineBool) Properties() []Property {
	props := o.StateMachineInput.Properties()
	if o.Value {
		props = append(props, Property{Key: 141, Type: PropertyTypeUint, Value: boolToUint64(o.Value)})
	}
	return props
}

// StateMachineComponent (typeKey: 54) [abstract]
type StateMachineComponent struct {
	Name string `rive:"138,string"`
}

func (o *StateMachineComponent) Properties() []Property {
	var props []Property
	if o.Name != "" {
		props = append(props, Property{Key: 138, Type: PropertyTypeString, Value: o.Name})
	}
	return props
}

// StateMachineComponentFolder (typeKey: 151)
type StateMachineComponentFolder struct {
	StateMachineComponent
}

func (o *StateMachineComponentFolder) TypeKey() uint32 { return 151 }

func (o *StateMachineComponentFolder) Properties() []Property {
	return o.StateMachineComponent.Properties()
}

// StateMachineComponentNestedArtboard (typeKey: 172)
type StateMachineComponentNestedArtboard struct {
	StateMachineComponentFolder
}

func (o *StateMachineComponentNestedArtboard) TypeKey() uint32 { return 172 }

func (o *StateMachineComponentNestedArtboard) Properties() []Property {
	return o.StateMachineComponentFolder.Properties()
}

// StateMachineFireAction (typeKey: 615) [abstract]
type StateMachineFireAction struct {
	OccursValue uint64 `rive:"393,uint"`
}

func (o *StateMachineFireAction) Properties() []Property {
	var props []Property
	if o.OccursValue != 0 {
		props = append(props, Property{Key: 393, Type: PropertyTypeUint, Value: o.OccursValue})
	}
	return props
}

// StateMachineFireEvent (typeKey: 169)
type StateMachineFireEvent struct {
	StateMachineFireAction
	EventId uint64 `rive:"392,uint"`
}

func (o *StateMachineFireEvent) TypeKey() uint32 { return 169 }

func (o *StateMachineFireEvent) Properties() []Property {
	props := o.StateMachineFireAction.Properties()
	if o.EventId != ^uint64(0) {
		props = append(props, Property{Key: 392, Type: PropertyTypeUint, Value: o.EventId})
	}
	return props
}

// StateMachineFireTrigger (typeKey: 614)
type StateMachineFireTrigger struct {
	StateMachineFireAction
	ViewModelPathIds []byte `rive:"871,bytes"`
}

func (o *StateMachineFireTrigger) TypeKey() uint32 { return 614 }

func (o *StateMachineFireTrigger) Properties() []Property {
	props := o.StateMachineFireAction.Properties()
	if len(o.ViewModelPathIds) > 0 {
		props = append(props, Property{Key: 871, Type: PropertyTypeBytes, Value: o.ViewModelPathIds})
	}
	return props
}

// StateMachineInput (typeKey: 55) [abstract]
type StateMachineInput struct {
	StateMachineComponent
}

func (o *StateMachineInput) Properties() []Property {
	return o.StateMachineComponent.Properties()
}

// StateMachineInputFolder (typeKey: 149)
type StateMachineInputFolder struct {
	StateMachineComponentFolder
}

func (o *StateMachineInputFolder) TypeKey() uint32 { return 149 }

func (o *StateMachineInputFolder) Properties() []Property {
	return o.StateMachineComponentFolder.Properties()
}

// StateMachineLayer (typeKey: 57)
type StateMachineLayer struct {
	StateMachineComponent
}

func (o *StateMachineLayer) TypeKey() uint32 { return 57 }

func (o *StateMachineLayer) Properties() []Property {
	return o.StateMachineComponent.Properties()
}

// StateMachineLayerComponent (typeKey: 66) [abstract]
type StateMachineLayerComponent struct {
}

func (o *StateMachineLayerComponent) Properties() []Property {
	return nil
}

// StateMachineListener (typeKey: 654)
type StateMachineListener struct {
	StateMachineComponent
	TargetId uint64 `rive:"224,uint"`
}

func (o *StateMachineListener) TypeKey() uint32 { return 654 }

func (o *StateMachineListener) Properties() []Property {
	props := o.StateMachineComponent.Properties()
	if o.TargetId != ^uint64(0) {
		props = append(props, Property{Key: 224, Type: PropertyTypeUint, Value: o.TargetId})
	}
	return props
}

// StateMachineListenerFolder (typeKey: 150)
type StateMachineListenerFolder struct {
	StateMachineComponentFolder
}

func (o *StateMachineListenerFolder) TypeKey() uint32 { return 150 }

func (o *StateMachineListenerFolder) Properties() []Property {
	return o.StateMachineComponentFolder.Properties()
}

// StateMachineListenerSingle (typeKey: 114)
type StateMachineListenerSingle struct {
	StateMachineListener
	ListenerTypeValue uint64 `rive:"225,uint"`
	EventId           uint64 `rive:"399,uint"`
	ViewModelPathIds  []byte `rive:"868,bytes"`
}

func (o *StateMachineListenerSingle) TypeKey() uint32 { return 114 }

func (o *StateMachineListenerSingle) Properties() []Property {
	props := o.StateMachineListener.Properties()
	if o.ListenerTypeValue != 0 {
		props = append(props, Property{Key: 225, Type: PropertyTypeUint, Value: o.ListenerTypeValue})
	}
	if o.EventId != ^uint64(0) {
		props = append(props, Property{Key: 399, Type: PropertyTypeUint, Value: o.EventId})
	}
	if len(o.ViewModelPathIds) > 0 {
		props = append(props, Property{Key: 868, Type: PropertyTypeBytes, Value: o.ViewModelPathIds})
	}
	return props
}

// StateMachineNestedInput (typeKey: 173)
type StateMachineNestedInput struct {
	StateMachineComponent
}

func (o *StateMachineNestedInput) TypeKey() uint32 { return 173 }

func (o *StateMachineNestedInput) Properties() []Property {
	return o.StateMachineComponent.Properties()
}

// StateMachineNumber (typeKey: 56)
type StateMachineNumber struct {
	StateMachineInput
	Value float64 `rive:"140,float"`
}

func (o *StateMachineNumber) TypeKey() uint32 { return 56 }

func (o *StateMachineNumber) Properties() []Property {
	props := o.StateMachineInput.Properties()
	if o.Value != 0 {
		props = append(props, Property{Key: 140, Type: PropertyTypeFloat, Value: o.Value})
	}
	return props
}

// StateMachineResolver (typeKey: 551) [abstract]
type StateMachineResolver struct {
	Animation
}

func (o *StateMachineResolver) Properties() []Property {
	return o.Animation.Properties()
}

// StateMachineTrigger (typeKey: 58)
type StateMachineTrigger struct {
	StateMachineInput
}

func (o *StateMachineTrigger) TypeKey() uint32 { return 58 }

func (o *StateMachineTrigger) Properties() []Property {
	return o.StateMachineInput.Properties()
}

// StateTransition (typeKey: 65)
type StateTransition struct {
	StateMachineLayerComponent
	StateToId         uint64 `rive:"151,uint"`
	Flags             uint64 `rive:"152,uint"`
	Duration          uint64 `rive:"158,uint"`
	ExitTime          uint64 `rive:"160,uint"`
	InterpolationType uint64 `rive:"349,uint"`
	InterpolatorId    uint64 `rive:"350,uint"`
	RandomWeight      uint64 `rive:"537,uint"`
}

func (o *StateTransition) TypeKey() uint32 { return 65 }

func (o *StateTransition) Properties() []Property {
	props := o.StateMachineLayerComponent.Properties()
	if o.StateToId != ^uint64(0) {
		props = append(props, Property{Key: 151, Type: PropertyTypeUint, Value: o.StateToId})
	}
	if o.Flags != 0 {
		props = append(props, Property{Key: 152, Type: PropertyTypeUint, Value: o.Flags})
	}
	if o.Duration != 0 {
		props = append(props, Property{Key: 158, Type: PropertyTypeUint, Value: o.Duration})
	}
	if o.ExitTime != 0 {
		props = append(props, Property{Key: 160, Type: PropertyTypeUint, Value: o.ExitTime})
	}
	if o.InterpolationType != 1 {
		props = append(props, Property{Key: 349, Type: PropertyTypeUint, Value: o.InterpolationType})
	}
	if o.InterpolatorId != ^uint64(0) {
		props = append(props, Property{Key: 350, Type: PropertyTypeUint, Value: o.InterpolatorId})
	}
	if o.RandomWeight != 1 {
		props = append(props, Property{Key: 537, Type: PropertyTypeUint, Value: o.RandomWeight})
	}
	return props
}

// TransitionArtboardCondition (typeKey: 497)
type TransitionArtboardCondition struct {
	TransitionViewModelCondition
}

func (o *TransitionArtboardCondition) TypeKey() uint32 { return 497 }

func (o *TransitionArtboardCondition) Properties() []Property {
	return o.TransitionViewModelCondition.Properties()
}

// TransitionBoolCondition (typeKey: 71)
type TransitionBoolCondition struct {
	TransitionValueCondition
}

func (o *TransitionBoolCondition) TypeKey() uint32 { return 71 }

func (o *TransitionBoolCondition) Properties() []Property {
	return o.TransitionValueCondition.Properties()
}

// TransitionComparator (typeKey: 477) [abstract]
type TransitionComparator struct {
}

func (o *TransitionComparator) Properties() []Property {
	return nil
}

// TransitionCondition (typeKey: 476) [abstract]
type TransitionCondition struct {
}

func (o *TransitionCondition) Properties() []Property {
	return nil
}

// TransitionInputCondition (typeKey: 67) [abstract]
type TransitionInputCondition struct {
	TransitionCondition
	InputId uint64 `rive:"155,uint"`
}

func (o *TransitionInputCondition) Properties() []Property {
	props := o.TransitionCondition.Properties()
	if o.InputId != ^uint64(0) {
		props = append(props, Property{Key: 155, Type: PropertyTypeUint, Value: o.InputId})
	}
	return props
}

// TransitionNumberCondition (typeKey: 70)
type TransitionNumberCondition struct {
	TransitionValueCondition
	Value float64 `rive:"157,float"`
}

func (o *TransitionNumberCondition) TypeKey() uint32 { return 70 }

func (o *TransitionNumberCondition) Properties() []Property {
	props := o.TransitionValueCondition.Properties()
	if o.Value != 0 {
		props = append(props, Property{Key: 157, Type: PropertyTypeFloat, Value: o.Value})
	}
	return props
}

// TransitionPropertyArtboardComparator (typeKey: 496)
type TransitionPropertyArtboardComparator struct {
	TransitionPropertyComparator
	PropertyType uint64 `rive:"677,uint"`
}

func (o *TransitionPropertyArtboardComparator) TypeKey() uint32 { return 496 }

func (o *TransitionPropertyArtboardComparator) Properties() []Property {
	props := o.TransitionPropertyComparator.Properties()
	if o.PropertyType != 0 {
		props = append(props, Property{Key: 677, Type: PropertyTypeUint, Value: o.PropertyType})
	}
	return props
}

// TransitionPropertyComparator (typeKey: 478) [abstract]
type TransitionPropertyComparator struct {
	TransitionComparator
}

func (o *TransitionPropertyComparator) Properties() []Property {
	return o.TransitionComparator.Properties()
}

// TransitionPropertyComponentComparator (typeKey: 667)
type TransitionPropertyComponentComparator struct {
	TransitionPropertyComparator
	ObjectId    uint64 `rive:"977,uint"`
	PropertyKey uint64 `rive:"978,uint"`
}

func (o *TransitionPropertyComponentComparator) TypeKey() uint32 { return 667 }

func (o *TransitionPropertyComponentComparator) Properties() []Property {
	props := o.TransitionPropertyComparator.Properties()
	if o.ObjectId != 0 {
		props = append(props, Property{Key: 977, Type: PropertyTypeUint, Value: o.ObjectId})
	}
	if o.PropertyKey != 0 {
		props = append(props, Property{Key: 978, Type: PropertyTypeUint, Value: o.PropertyKey})
	}
	return props
}

// TransitionPropertyViewModelComparator (typeKey: 479)
type TransitionPropertyViewModelComparator struct {
	TransitionPropertyComparator
}

func (o *TransitionPropertyViewModelComparator) TypeKey() uint32 { return 479 }

func (o *TransitionPropertyViewModelComparator) Properties() []Property {
	return o.TransitionPropertyComparator.Properties()
}

// TransitionSelfComparator (typeKey: 593)
type TransitionSelfComparator struct {
	TransitionComparator
}

func (o *TransitionSelfComparator) TypeKey() uint32 { return 593 }

func (o *TransitionSelfComparator) Properties() []Property {
	return o.TransitionComparator.Properties()
}

// TransitionTriggerCondition (typeKey: 68)
type TransitionTriggerCondition struct {
	TransitionInputCondition
}

func (o *TransitionTriggerCondition) TypeKey() uint32 { return 68 }

func (o *TransitionTriggerCondition) Properties() []Property {
	return o.TransitionInputCondition.Properties()
}

// TransitionValueArtboardComparator (typeKey: 630)
type TransitionValueArtboardComparator struct {
	TransitionValueIdComparator
}

func (o *TransitionValueArtboardComparator) TypeKey() uint32 { return 630 }

func (o *TransitionValueArtboardComparator) Properties() []Property {
	return o.TransitionValueIdComparator.Properties()
}

// TransitionValueAssetComparator (typeKey: 602)
type TransitionValueAssetComparator struct {
	TransitionValueIdComparator
}

func (o *TransitionValueAssetComparator) TypeKey() uint32 { return 602 }

func (o *TransitionValueAssetComparator) Properties() []Property {
	return o.TransitionValueIdComparator.Properties()
}

// TransitionValueBooleanComparator (typeKey: 481)
type TransitionValueBooleanComparator struct {
	TransitionValueComparator
	Value bool `rive:"647,bool"`
}

func (o *TransitionValueBooleanComparator) TypeKey() uint32 { return 481 }

func (o *TransitionValueBooleanComparator) Properties() []Property {
	props := o.TransitionValueComparator.Properties()
	if o.Value {
		props = append(props, Property{Key: 647, Type: PropertyTypeUint, Value: boolToUint64(o.Value)})
	}
	return props
}

// TransitionValueColorComparator (typeKey: 483)
type TransitionValueColorComparator struct {
	TransitionValueComparator
	Value uint32 `rive:"651,color"`
}

func (o *TransitionValueColorComparator) TypeKey() uint32 { return 483 }

func (o *TransitionValueColorComparator) Properties() []Property {
	props := o.TransitionValueComparator.Properties()
	if o.Value != 0 {
		props = append(props, Property{Key: 651, Type: PropertyTypeColor, Value: uint64(o.Value)})
	}
	return props
}

// TransitionValueComparator (typeKey: 480) [abstract]
type TransitionValueComparator struct {
	TransitionComparator
}

func (o *TransitionValueComparator) Properties() []Property {
	return o.TransitionComparator.Properties()
}

// TransitionValueCondition (typeKey: 69) [abstract]
type TransitionValueCondition struct {
	TransitionInputCondition
	OpValue uint64 `rive:"156,uint"`
}

func (o *TransitionValueCondition) Properties() []Property {
	props := o.TransitionInputCondition.Properties()
	if o.OpValue != 0 {
		props = append(props, Property{Key: 156, Type: PropertyTypeUint, Value: o.OpValue})
	}
	return props
}

// TransitionValueEnumComparator (typeKey: 485)
type TransitionValueEnumComparator struct {
	TransitionValueIdComparator
}

func (o *TransitionValueEnumComparator) TypeKey() uint32 { return 485 }

func (o *TransitionValueEnumComparator) Properties() []Property {
	return o.TransitionValueIdComparator.Properties()
}

// TransitionValueIdComparator (typeKey: 601)
type TransitionValueIdComparator struct {
	TransitionValueComparator
	Value uint64 `rive:"653,uint"`
}

func (o *TransitionValueIdComparator) TypeKey() uint32 { return 601 }

func (o *TransitionValueIdComparator) Properties() []Property {
	props := o.TransitionValueComparator.Properties()
	if o.Value != ^uint64(0) {
		props = append(props, Property{Key: 653, Type: PropertyTypeUint, Value: o.Value})
	}
	return props
}

// TransitionValueNumberComparator (typeKey: 484)
type TransitionValueNumberComparator struct {
	TransitionValueComparator
	Value float64 `rive:"652,float"`
}

func (o *TransitionValueNumberComparator) TypeKey() uint32 { return 484 }

func (o *TransitionValueNumberComparator) Properties() []Property {
	props := o.TransitionValueComparator.Properties()
	if o.Value != 0 {
		props = append(props, Property{Key: 652, Type: PropertyTypeFloat, Value: o.Value})
	}
	return props
}

// TransitionValueStringComparator (typeKey: 486)
type TransitionValueStringComparator struct {
	TransitionValueComparator
	Value string `rive:"654,string"`
}

func (o *TransitionValueStringComparator) TypeKey() uint32 { return 486 }

func (o *TransitionValueStringComparator) Properties() []Property {
	props := o.TransitionValueComparator.Properties()
	if o.Value != "" {
		props = append(props, Property{Key: 654, Type: PropertyTypeString, Value: o.Value})
	}
	return props
}

// TransitionValueTriggerComparator (typeKey: 505)
type TransitionValueTriggerComparator struct {
	TransitionValueComparator
	Value uint64 `rive:"689,uint"`
}

func (o *TransitionValueTriggerComparator) TypeKey() uint32 { return 505 }

func (o *TransitionValueTriggerComparator) Properties() []Property {
	props := o.TransitionValueComparator.Properties()
	if o.Value != 0 {
		props = append(props, Property{Key: 689, Type: PropertyTypeUint, Value: o.Value})
	}
	return props
}

// TransitionViewModelCondition (typeKey: 482)
type TransitionViewModelCondition struct {
	TransitionCondition
	OpValue uint64 `rive:"650,uint"`
}

func (o *TransitionViewModelCondition) TypeKey() uint32 { return 482 }

func (o *TransitionViewModelCondition) Properties() []Property {
	props := o.TransitionCondition.Properties()
	if o.OpValue != 0 {
		props = append(props, Property{Key: 650, Type: PropertyTypeUint, Value: o.OpValue})
	}
	return props
}
