// Code generated by rivegen. DO NOT EDIT.
package rive

// BindableProperty (typeKey: 9) [abstract]
type BindableProperty struct {
}

func (o *BindableProperty) Properties() []Property {
	return nil
}

// BindablePropertyArtboard (typeKey: 597)
type BindablePropertyArtboard struct {
	BindablePropertyId
}

func (o *BindablePropertyArtboard) TypeKey() uint32 { return 597 }

func (o *BindablePropertyArtboard) Properties() []Property {
	return o.BindablePropertyId.Properties()
}

// BindablePropertyAsset (typeKey: 588)
type BindablePropertyAsset struct {
	BindablePropertyId
}

func (o *BindablePropertyAsset) TypeKey() uint32 { return 588 }

func (o *BindablePropertyAsset) Properties() []Property {
	return o.BindablePropertyId.Properties()
}

// BindablePropertyBoolean (typeKey: 472)
type BindablePropertyBoolean struct {
	BindableProperty
	PropertyValue bool `rive:"634,bool"`
}

func (o *BindablePropertyBoolean) TypeKey() uint32 { return 472 }

func (o *BindablePropertyBoolean) Properties() []Property {
	props := o.BindableProperty.Properties()
	if o.PropertyValue {
		props = append(props, Property{Key: 634, Type: PropertyTypeUint, Value: boolToUint64(o.PropertyValue)})
	}
	return props
}

// BindablePropertyColor (typeKey: 475)
type BindablePropertyColor struct {
	BindableProperty
	PropertyValue uint32 `rive:"638,color"`
}

func (o *BindablePropertyColor) TypeKey() uint32 { return 475 }

func (o *BindablePropertyColor) Properties() []Property {
	props := o.BindableProperty.Properties()
	if o.PropertyValue != 0 {
		props = append(props, Property{Key: 638, Type: PropertyTypeColor, Value: uint64(o.PropertyValue)})
	}
	return props
}

// BindablePropertyEnum (typeKey: 474)
type BindablePropertyEnum struct {
	BindableProperty
	PropertyValue uint64 `rive:"637,uint"`
}

func (o *BindablePropertyEnum) TypeKey() uint32 { return 474 }

func (o *BindablePropertyEnum) Properties() []Property {
	props := o.BindableProperty.Properties()
	if o.PropertyValue != ^uint64(0) {
		props = append(props, Property{Key: 637, Type: PropertyTypeUint, Value: o.PropertyValue})
	}
	return props
}

// BindablePropertyId (typeKey: 596) [abstract]
type BindablePropertyId struct {
	BindableProperty
	PropertyValue uint64 `rive:"823,uint"`
}

func (o *BindablePropertyId) Properties() []Property {
	props := o.BindableProperty.Properties()
	if o.PropertyValue != ^uint64(0) {
		props = append(props, Property{Key: 823, Type: PropertyTypeUint, Value: o.PropertyValue})
	}
	return props
}

// BindablePropertyInteger (typeKey: 567)
type BindablePropertyInteger struct {
	BindableProperty
	PropertyValue uint64 `rive:"686,uint"`
}

func (o *BindablePropertyInteger) TypeKey() uint32 { return 567 }

func (o *BindablePropertyInteger) Properties() []Property {
	props := o.BindableProperty.Properties()
	if o.PropertyValue != 0 {
		props = append(props, Property{Key: 686, Type: PropertyTypeUint, Value: o.PropertyValue})
	}
	return props
}

// BindablePropertyList (typeKey: 590)
type BindablePropertyList struct {
	BindableProperty
	PropertyValue uint64 `rive:"835,uint"`
}

func (o *BindablePropertyList) TypeKey() uint32 { return 590 }

func (o *BindablePropertyList) Properties() []Property {
	props := o.BindableProperty.Properties()
	if o.PropertyValue != ^uint64(0) {
		props = append(props, Property{Key: 835, Type: PropertyTypeUint, Value: o.PropertyValue})
	}
	return props
}

// BindablePropertyNumber (typeKey: 473)
type BindablePropertyNumber struct {
	BindableProperty
	PropertyValue float64 `rive:"636,float"`
}

func (o *BindablePropertyNumber) TypeKey() uint32 { return 473 }

func (o *BindablePropertyNumber) Properties() []Property {
	props := o.BindableProperty.Properties()
	if o.PropertyValue != 0 {
		props = append(props, Property{Key: 636, Type: PropertyTypeFloat, Value: o.PropertyValue})
	}
	return props
}

// BindablePropertyString (typeKey: 471)
type BindablePropertyString struct {
	BindableProperty
	PropertyValue string `rive:"635,string"`
}

func (o *BindablePropertyString) TypeKey() uint32 { return 471 }

func (o *BindablePropertyString) Properties() []Property {
	props := o.BindableProperty.Properties()
	if o.PropertyValue != "" {
		props = append(props, Property{Key: 635, Type: PropertyTypeString, Value: o.PropertyValue})
	}
	return props
}

// BindablePropertyTrigger (typeKey: 503)
type BindablePropertyTrigger struct {
	BindablePropertyInteger
}

func (o *BindablePropertyTrigger) TypeKey() uint32 { return 503 }

func (o *BindablePropertyTrigger) Properties() []Property {
	return o.BindablePropertyInteger.Properties()
}

// BindablePropertyViewModel (typeKey: 662)
type BindablePropertyViewModel struct {
	BindablePropertyId
}

func (o *BindablePropertyViewModel) TypeKey() uint32 { return 662 }

func (o *BindablePropertyViewModel) Properties() []Property {
	return o.BindablePropertyId.Properties()
}

// DataBind (typeKey: 446)
type DataBind struct {
	PropertyKey uint64 `rive:"586,uint"`
	Flags       uint64 `rive:"587,uint"`
	ConverterId uint64 `rive:"660,uint"`
}

func (o *DataBind) TypeKey() uint32 { return 446 }

func (o *DataBind) Properties() []Property {
	var props []Property
	if o.PropertyKey != 0 {
		props = append(props, Property{Key: 586, Type: PropertyTypeUint, Value: o.PropertyKey})
	}
	if o.Flags != 0 {
		props = append(props, Property{Key: 587, Type: PropertyTypeUint, Value: o.Flags})
	}
	if o.ConverterId != ^uint64(0) {
		props = append(props, Property{Key: 660, Type: PropertyTypeUint, Value: o.ConverterId})
	}
	return props
}

// DataBindContext (typeKey: 447)
type DataBindContext struct {
	DataBind
	SourcePathIds []byte `rive:"588,bytes"`
}

func (o *DataBindContext) TypeKey() uint32 { return 447 }

func (o *DataBindContext) Properties() []Property {
	props := o.DataBind.Properties()
	if len(o.SourcePathIds) > 0 {
		props = append(props, Property{Key: 588, Type: PropertyTypeBytes, Value: o.SourcePathIds})
	}
	return props
}

// DataBindPath (typeKey: 643)
type DataBindPath struct {
	Path       []byte `rive:"920,bytes"`
	IsRelative bool   `rive:"921,bool"`
}

func (o *DataBindPath) TypeKey() uint32 { return 643 }

func (o *DataBindPath) Properties() []Property {
	var props []Property
	if len(o.Path) > 0 {
		props = append(props, Property{Key: 920, Type: PropertyTypeBytes, Value: o.Path})
	}
	if o.IsRelative {
		props = append(props, Property{Key: 921, Type: PropertyTypeUint, Value: boolToUint64(o.IsRelative)})
	}
	return props
}

// DataConverter (typeKey: 488) [abstract]
type DataConverter struct {
	Name string `rive:"662,string"`
}

func (o *DataConverter) Properties() []Property {
	var props []Property
	if o.Name != "" {
		props = append(props, Property{Key: 662, Type: PropertyTypeString, Value: o.Name})
	}
	return props
}

// DataConverterBooleanNegate (typeKey: 535)
type DataConverterBooleanNegate struct {
	DataConverter
}

func (o *DataConverterBooleanNegate) TypeKey() uint32 { return 535 }

func (o *DataConverterBooleanNegate) Properties() []Property {
	return o.DataConverter.Properties()
}

// DataConverterFormula (typeKey: 536)
type DataConverterFormula struct {
	DataConverter
	RandomModeValue uint64 `rive:"887,uint"`
}

func (o *DataConverterFormula) TypeKey() uint32 { return 536 }

func (o *DataConverterFormula) Properties() []Property {
	props := o.DataConverter.Properties()
	if o.RandomModeValue != 0 {
		props = append(props, Property{Key: 887, Type: PropertyTypeUint, Value: o.RandomModeValue})
	}
	return props
}

// DataConverterGroup (typeKey: 499)
type DataConverterGroup struct {
	DataConverter
}

func (o *DataConverterGroup) TypeKey() uint32 { return 499 }

func (o *DataConverterGroup) Properties() []Property {
	return o.DataConverter.Properties()
}

// DataConverterGroupItem (typeKey: 498)
type DataConverterGroupItem struct {
	ConverterId uint64 `rive:"679,uint"`
}

func (o *DataConverterGroupItem) TypeKey() uint32 { return 498 }

func (o *DataConverterGroupItem) Properties() []Property {
	var props []Property
	if o.ConverterId != ^uint64(0) {
		props = append(props, Property{Key: 679, Type: PropertyTypeUint, Value: o.ConverterId})
	}
	return props
}

// DataConverterInterpolator (typeKey: 534)
type DataConverterInterpolator struct {
	DataConverter
	Duration          float64 `rive:"756,float"`
	InterpolationType uint64  `rive:"757,uint"`
	InterpolatorId    uint64  `rive:"758,uint"`
}

func (o *DataConverterInterpolator) TypeKey() uint32 { return 534 }

func (o *DataConverterInterpolator) Properties() []Property {
	props := o.DataConverter.Properties()
	if o.Duration != 1 {
		props = append(props, Property{Key: 756, Type: PropertyTypeFloat, Value: o.Duration})
	}
	if o.InterpolationType != 1 {
		props = append(props, Property{Key: 757, Type: PropertyTypeUint, Value: o.InterpolationType})
	}
	if o.InterpolatorId != ^uint64(0) {
		props = append(props, Property{Key: 758, Type: PropertyTypeUint, Value: o.InterpolatorId})
	}
	return props
}

// DataConverterListToLength (typeKey: 591)
type DataConverterListToLength struct {
	DataConverter
}

func (o *DataConverterListToLength) TypeKey() uint32 { return 591 }

func (o *DataConverterListToLength) Properties() []Property {
	return o.DataConverter.Properties()
}

// DataConverterNumberToList (typeKey: 568)
type DataConverterNumberToList struct {
	DataConverter
	ViewModelId uint64 `rive:"816,uint"`
}

func (o *DataConverterNumberToList) TypeKey() uint32 { return 568 }

func (o *DataConverterNumberToList) Properties() []Property {
	props := o.DataConverter.Properties()
	if o.ViewModelId != ^uint64(0) {
		props = append(props, Property{Key: 816, Type: PropertyTypeUint, Value: o.ViewModelId})
	}
	return props
}

// DataConverterOperation (typeKey: 516)
type DataConverterOperation struct {
	DataConverter
	OperationType uint64 `rive:"682,uint"`
}

func (o *DataConverterOperation) TypeKey() uint32 { return 516 }

func (o *DataConverterOperation) Properties() []Property {
	props := o.DataConverter.Properties()
	if o.OperationType != 0 {
		props = append(props, Property{Key: 682, Type: PropertyTypeUint, Value: o.OperationType})
	}
	return props
}

// DataConverterOperationValue (typeKey: 500)
type DataConverterOperationValue struct {
	DataConverterOperation
	OperationValue float64 `rive:"681,float"`
}

func (o *DataConverterOperationValue) TypeKey() uint32 { return 500 }

func (o *DataConverterOperationValue) Properties() []Property {
	props := o.DataConverterOperation.Properties()
	if o.OperationValue != 1 {
		props = append(props, Property{Key: 681, Type: PropertyTypeFloat, Value: o.OperationValue})
	}
	return props
}

// DataConverterOperationViewModel (typeKey: 517)
type DataConverterOperationViewModel struct {
	DataConverterOperation
	SourcePathIds []byte `rive:"711,bytes"`
}

func (o *DataConverterOperationViewModel) TypeKey() uint32 { return 517 }

func (o *DataConverterOperationViewModel) Properties() []Property {
	props := o.DataConverterOperation.Properties()
	if len(o.SourcePathIds) > 0 {
		props = append(props, Property{Key: 711, Type: PropertyTypeBytes, Value: o.SourcePathIds})
	}
	return props
}

// DataConverterRangeMapper (typeKey: 519)
type DataConverterRangeMapper struct {
	DataConverter
	InterpolationType uint64  `rive:"713,uint"`
	InterpolatorId    uint64  `rive:"714,uint"`
	Flags             uint64  `rive:"715,uint"`
	MinInput          float64 `rive:"716,float"`
	MaxInput          float64 `rive:"717,float"`
	MinOutput         float64 `rive:"718,float"`
	MaxOutput         float64 `rive:"719,float"`
}

func (o *DataConverterRangeMapper) TypeKey() uint32 { return 519 }

func (o *DataConverterRangeMapper) Properties() []Property {
	props := o.DataConverter.Properties()
	if o.InterpolationType != 1 {
		props = append(props, Property{Key: 713, Type: PropertyTypeUint, Value: o.InterpolationType})
	}
	if o.InterpolatorId != ^uint64(0) {
		props = append(props, Property{Key: 714, Type: PropertyTypeUint, Value: o.InterpolatorId})
	}
	if o.Flags != 0 {
		props = append(props, Property{Key: 715, Type: PropertyTypeUint, Value: o.Flags})
	}
	if o.MinInput != 1 {
		props = append(props, Property{Key: 716, Type: PropertyTypeFloat, Value: o.MinInput})
	}
	if o.MaxInput != 1 {
		props = append(props, Property{Key: 717, Type: PropertyTypeFloat, Value: o.MaxInput})
	}
	if o.MinOutput != 1 {
		props = append(props, Property{Key: 718, Type: PropertyTypeFloat, Value: o.MinOutput})
	}
	if o.MaxOutput != 1 {
		props = append(props, Property{Key: 719, Type: PropertyTypeFloat, Value: o.MaxOutput})
	}
	return props
}

// DataConverterRounder (typeKey: 489)
type DataConverterRounder struct {
	DataConverter
	Decimals uint64 `rive:"669,uint"`
}

func (o *DataConverterRounder) TypeKey() uint32 { return 489 }

func (o *DataConverterRounder) Properties() []Property {
	props := o.DataConverter.Properties()
	if o.Decimals != 0 {
		props = append(props, Property{Key: 669, Type: PropertyTypeUint, Value: o.Decimals})
	}
	return props
}

// DataConverterStringPad (typeKey: 530)
type DataConverterStringPad struct {
	DataConverter
	Length  uint64 `rive:"743,uint"`
	Text    string `rive:"744,string"`
	PadType uint64 `rive:"745,uint"`
}

func (o *DataConverterStringPad) TypeKey() uint32 { return 530 }

func (o *DataConverterStringPad) Properties() []Property {
	props := o.DataConverter.Properties()
	if o.Length != 1 {
		props = append(props, Property{Key: 743, Type: PropertyTypeUint, Value: o.Length})
	}
	if o.Text != "" {
		props = append(props, Property{Key: 744, Type: PropertyTypeString, Value: o.Text})
	}
	if o.PadType != 0 {
		props = append(props, Property{Key: 745, Type: PropertyTypeUint, Value: o.PadType})
	}
	return props
}

// DataConverterStringRemoveZeros (typeKey: 531)
type DataConverterStringRemoveZeros struct {
	DataConverter
}

func (o *DataConverterStringRemoveZeros) TypeKey() uint32 { return 531 }

func (o *DataConverterStringRemoveZeros) Properties() []Property {
	return o.DataConverter.Properties()
}

// DataConverterStringTrim (typeKey: 532)
type DataConverterStringTrim struct {
	DataConverter
	TrimType uint64 `rive:"746,uint"`
}

func (o *DataConverterStringTrim) TypeKey() uint32 { return 532 }

func (o *DataConverterStringTrim) Properties() []Property {
	props := o.DataConverter.Properties()
	if o.TrimType != 1 {
		props = append(props, Property{Key: 746, Type: PropertyTypeUint, Value: o.TrimType})
	}
	return props
}

// DataConverterSystemDegsToRads (typeKey: 514)
type DataConverterSystemDegsToRads struct {
	DataConverterOperationValue
}

func (o *DataConverterSystemDegsToRads) TypeKey() uint32 { return 514 }

func (o *DataConverterSystemDegsToRads) Properties() []Property {
	return o.DataConverterOperationValue.Properties()
}

// DataConverterSystemNormalizer (typeKey: 515)
type DataConverterSystemNormalizer struct {
	DataConverterOperationValue
}

func (o *DataConverterSystemNormalizer) TypeKey() uint32 { return 515 }

func (o *DataConverterSystemNormalizer) Properties() []Property {
	return o.DataConverterOperationValue.Properties()
}

// DataConverterToNumber (typeKey: 617)
type DataConverterToNumber struct {
	DataConverter
}

func (o *DataConverterToNumber) TypeKey() uint32 { return 617 }

func (o *DataConverterToNumber) Properties() []Property {
	return o.DataConverter.Properties()
}

// DataConverterToString (typeKey: 490)
type DataConverterToString struct {
	DataConverter
	Flags       uint64 `rive:"764,uint"`
	Decimals    uint64 `rive:"765,uint"`
	ColorFormat string `rive:"766,string"`
}

func (o *DataConverterToString) TypeKey() uint32 { return 490 }

func (o *DataConverterToString) Properties() []Property {
	props := o.DataConverter.Properties()
	if o.Flags != 0 {
		props = append(props, Property{Key: 764, Type: PropertyTypeUint, Value: o.Flags})
	}
	if o.Decimals != 0 {
		props = append(props, Property{Key: 765, Type: PropertyTypeUint, Value: o.Decimals})
	}
	if o.ColorFormat != "" {
		props = append(props, Property{Key: 766, Type: PropertyTypeString, Value: o.ColorFormat})
	}
	return props
}

// DataConverterTrigger (typeKey: 504)
type DataConverterTrigger struct {
	DataConverter
}

func (o *DataConverterTrigger) TypeKey() uint32 { return 504 }

func (o *DataConverterTrigger) Properties() []Property {
	return o.DataConverter.Properties()
}

// FormulaToken (typeKey: 537)
type FormulaToken struct {
}

func (o *FormulaToken) TypeKey() uint32 { return 537 }

func (o *FormulaToken) Properties() []Property {
	return nil
}

// FormulaTokenArgumentSeparator (typeKey: 538)
type FormulaTokenArgumentSeparator struct {
	FormulaToken
}

func (o *FormulaTokenArgumentSeparator) TypeKey() uint32 { return 538 }

func (o *FormulaTokenArgumentSeparator) Properties() []Property {
	return o.FormulaToken.Properties()
}

// FormulaTokenFunction (typeKey: 542)
type FormulaTokenFunction struct {
	FormulaTokenParenthesis
	FunctionType uint64 `rive:"776,uint"`
}

func (o *FormulaTokenFunction) TypeKey() uint32 { return 542 }

func (o *FormulaTokenFunction) Properties() []Property {
	props := o.FormulaTokenParenthesis.Properties()
	if o.FunctionType != 0 {
		props = append(props, Property{Key: 776, Type: PropertyTypeUint, Value: o.FunctionType})
	}
	return props
}

// FormulaTokenInput (typeKey: 545)
type FormulaTokenInput struct {
	FormulaToken
}

func (o *FormulaTokenInput) TypeKey() uint32 { return 545 }

func (o *FormulaTokenInput) Properties() []Property {
	return o.FormulaToken.Properties()
}

// FormulaTokenOperation (typeKey: 541)
type FormulaTokenOperation struct {
	FormulaToken
	OperationType uint64 `rive:"775,uint"`
}

func (o *FormulaTokenOperation) TypeKey() uint32 { return 541 }

func (o *FormulaTokenOperation) Properties() []Property {
	props := o.FormulaToken.Properties()
	if o.OperationType != 0 {
		props = append(props, Property{Key: 775, Type: PropertyTypeUint, Value: o.OperationType})
	}
	return props
}

// FormulaTokenParenthesis (typeKey: 539)
type FormulaTokenParenthesis struct {
	FormulaToken
}

func (o *FormulaTokenParenthesis) TypeKey() uint32 { return 539 }

func (o *FormulaTokenParenthesis) Properties() []Property {
	return o.FormulaToken.Properties()
}

// FormulaTokenParenthesisClose (typeKey: 540)
type FormulaTokenParenthesisClose struct {
	FormulaTokenParenthesis
}

func (o *FormulaTokenParenthesisClose) TypeKey() uint32 { return 540 }

func (o *FormulaTokenParenthesisClose) Properties() []Property {
	return o.FormulaTokenParenthesis.Properties()
}

// FormulaTokenParenthesisOpen (typeKey: 544)
type FormulaTokenParenthesisOpen struct {
	FormulaTokenParenthesis
}

func (o *FormulaTokenParenthesisOpen) TypeKey() uint32 { return 544 }

func (o *FormulaTokenParenthesisOpen) Properties() []Property {
	return o.FormulaTokenParenthesis.Properties()
}

// FormulaTokenValue (typeKey: 543)
type FormulaTokenValue struct {
	FormulaToken
	OperationValue float64 `rive:"777,float"`
}

func (o *FormulaTokenValue) TypeKey() uint32 { return 543 }

func (o *FormulaTokenValue) Properties() []Property {
	props := o.FormulaToken.Properties()
	if o.OperationValue != 1 {
		props = append(props, Property{Key: 777, Type: PropertyTypeFloat, Value: o.OperationValue})
	}
	return props
}
