// Code generated by rivegen. DO NOT EDIT.
package rive

// Bone (typeKey: 40)
type Bone struct {
	SkeletalComponent
	Length float64 `rive:"89,float"`
}

func (o *Bone) TypeKey() uint32 { return 40 }

func (o *Bone) Properties() []Property {
	props := o.SkeletalComponent.Properties()
	if o.Length != 0 {
		props = append(props, Property{Key: 89, Type: PropertyTypeFloat, Value: o.Length})
	}
	return props
}

// CubicWeight (typeKey: 46)
type CubicWeight struct {
	Weight
	InValues   uint64 `rive:"110,uint"`
	InIndices  uint64 `rive:"111,uint"`
	OutValues  uint64 `rive:"112,uint"`
	OutIndices uint64 `rive:"113,uint"`
}

func (o *CubicWeight) TypeKey() uint32 { return 46 }

func (o *CubicWeight) Properties() []Property {
	props := o.Weight.Properties()
	if o.InValues != 255 {
		props = append(props, Property{Key: 110, Type: PropertyTypeUint, Value: o.InValues})
	}
	if o.InIndices != 1 {
		props = append(props, Property{Key: 111, Type: PropertyTypeUint, Value: o.InIndices})
	}
	if o.OutValues != 255 {
		props = append(props, Property{Key: 112, Type: PropertyTypeUint, Value: o.OutValues})
	}
	if o.OutIndices != 1 {
		props = append(props, Property{Key: 113, Type: PropertyTypeUint, Value: o.OutIndices})
	}
	return props
}

// RootBone (typeKey: 41)
type RootBone struct {
	Bone
	X float64 `rive:"90,float"`
	Y float64 `rive:"91,float"`
}

func (o *RootBone) TypeKey() uint32 { return 41 }

func (o *RootBone) Properties() []Property {
	props := o.Bone.Properties()
	if o.X != 0 {
		props = append(props, Property{Key: 90, Type: PropertyTypeFloat, Value: o.X})
	}
	if o.Y != 0 {
		props = append(props, Property{Key: 91, Type: PropertyTypeFloat, Value: o.Y})
	}
	return props
}

// SkeletalComponent (typeKey: 39) [abstract]
type SkeletalComponent struct {
	TransformComponent
}

func (o *SkeletalComponent) Properties() []Property {
	return o.TransformComponent.Properties()
}

// Skin (typeKey: 43)
type Skin struct {
	ContainerComponent
	Xx float64 `rive:"104,float"`
	Yx float64 `rive:"105,float"`
	Xy float64 `rive:"106,float"`
	Yy float64 `rive:"107,float"`
	Tx float64 `rive:"108,float"`
	Ty float64 `rive:"109,float"`
}

func (o *Skin) TypeKey() uint32 { return 43 }

func (o *Skin) Properties() []Property {
	props := o.ContainerComponent.Properties()
	if o.Xx != 1 {
		props = append(props, Property{Key: 104, Type: PropertyTypeFloat, Value: o.Xx})
	}
	if o.Yx != 0 {
		props = append(props, Property{Key: 105, Type: PropertyTypeFloat, Value: o.Yx})
	}
	if o.Xy != 0 {
		props = append(props, Property{Key: 106, Type: PropertyTypeFloat, Value: o.Xy})
	}
	if o.Yy != 1 {
		props = append(props, Property{Key: 107, Type: PropertyTypeFloat, Value: o.Yy})
	}
	if o.Tx != 0 {
		props = append(props, Property{Key: 108, Type: PropertyTypeFloat, Value: o.Tx})
	}
	if o.Ty != 0 {
		props = append(props, Property{Key: 109, Type: PropertyTypeFloat, Value: o.Ty})
	}
	return props
}

// Tendon (typeKey: 44)
type Tendon struct {
	Component
	BoneId uint64  `rive:"95,uint"`
	Xx     float64 `rive:"96,float"`
	Yx     float64 `rive:"97,float"`
	Xy     float64 `rive:"98,float"`
	Yy     float64 `rive:"99,float"`
	Tx     float64 `rive:"100,float"`
	Ty     float64 `rive:"101,float"`
}

func (o *Tendon) TypeKey() uint32 { return 44 }

func (o *Tendon) Properties() []Property {
	props := o.Component.Properties()
	if o.BoneId != ^uint64(0) {
		props = append(props, Property{Key: 95, Type: PropertyTypeUint, Value: o.BoneId})
	}
	if o.Xx != 1 {
		props = append(props, Property{Key: 96, Type: PropertyTypeFloat, Value: o.Xx})
	}
	if o.Yx != 0 {
		props = append(props, Property{Key: 97, Type: PropertyTypeFloat, Value: o.Yx})
	}
	if o.Xy != 0 {
		props = append(props, Property{Key: 98, Type: PropertyTypeFloat, Value: o.Xy})
	}
	if o.Yy != 1 {
		props = append(props, Property{Key: 99, Type: PropertyTypeFloat, Value: o.Yy})
	}
	if o.Tx != 0 {
		props = append(props, Property{Key: 100, Type: PropertyTypeFloat, Value: o.Tx})
	}
	if o.Ty != 0 {
		props = append(props, Property{Key: 101, Type: PropertyTypeFloat, Value: o.Ty})
	}
	return props
}

// Weight (typeKey: 45)
type Weight struct {
	Component
	Values  uint64 `rive:"102,uint"`
	Indices uint64 `rive:"103,uint"`
}

func (o *Weight) TypeKey() uint32 { return 45 }

func (o *Weight) Properties() []Property {
	props := o.Component.Properties()
	if o.Values != 255 {
		props = append(props, Property{Key: 102, Type: PropertyTypeUint, Value: o.Values})
	}
	if o.Indices != 1 {
		props = append(props, Property{Key: 103, Type: PropertyTypeUint, Value: o.Indices})
	}
	return props
}
