// Code generated by rivegen. DO NOT EDIT.
package rive

// DataEnum (typeKey: 510)
type DataEnum struct {
}

func (o *DataEnum) TypeKey() uint32 { return 510 }

func (o *DataEnum) Properties() []Property {
	return nil
}

// DataEnumCustom (typeKey: 438)
type DataEnumCustom struct {
	DataEnum
	Name string `rive:"572,string"`
}

func (o *DataEnumCustom) TypeKey() uint32 { return 438 }

func (o *DataEnumCustom) Properties() []Property {
	props := o.DataEnum.Properties()
	if o.Name != "" {
		props = append(props, Property{Key: 572, Type: PropertyTypeString, Value: o.Name})
	}
	return props
}

// DataEnumSystem (typeKey: 512)
type DataEnumSystem struct {
	DataEnum
	EnumType uint64 `rive:"709,uint"`
}

func (o *DataEnumSystem) TypeKey() uint32 { return 512 }

func (o *DataEnumSystem) Properties() []Property {
	props := o.DataEnum.Properties()
	if o.EnumType != 0 {
		props = append(props, Property{Key: 709, Type: PropertyTypeUint, Value: o.EnumType})
	}
	return props
}

// DataEnumValue (typeKey: 445)
type DataEnumValue struct {
	Key   string `rive:"578,string"`
	Value string `rive:"579,string"`
}

func (o *DataEnumValue) TypeKey() uint32 { return 445 }

func (o *DataEnumValue) Properties() []Property {
	var props []Property
	if o.Key != "" {
		props = append(props, Property{Key: 578, Type: PropertyTypeString, Value: o.Key})
	}
	if o.Value != "" {
		props = append(props, Property{Key: 579, Type: PropertyTypeString, Value: o.Value})
	}
	return props
}

// ViewModel (typeKey: 435)
type ViewModel struct {
	ViewModelComponent
}

func (o *ViewModel) TypeKey() uint32 { return 435 }

func (o *ViewModel) Properties() []Property {
	return o.ViewModelComponent.Properties()
}

// ViewModelComponent (typeKey: 429)
type ViewModelComponent struct {
	Name string `rive:"557,string"`
}

func (o *ViewModelComponent) TypeKey() uint32 { return 429 }

func (o *ViewModelComponent) Properties() []Property {
	var props []Property
	if o.Name != "" {
		props = append(props, Property{Key: 557, Type: PropertyTypeString, Value: o.Name})
	}
	return props
}

// ViewModelInstance (typeKey: 437)
type ViewModelInstance struct {
	ContainerComponent
	ViewModelId uint64 `rive:"566,uint"`
}

func (o *ViewModelInstance) TypeKey() uint32 { return 437 }

func (o *ViewModelInstance) Properties() []Property {
	props := o.ContainerComponent.Properties()
	if o.ViewModelId != 0 {
		props = append(props, Property{Key: 566, Type: PropertyTypeUint, Value: o.ViewModelId})
	}
	return props
}

// ViewModelInstanceArtboard (typeKey: 599)
type ViewModelInstanceArtboard struct {
	ViewModelInstanceValue
	PropertyValue uint64 `rive:"846,uint"`
}

func (o *ViewModelInstanceArtboard) TypeKey() uint32 { return 599 }

func (o *ViewModelInstanceArtboard) Properties() []Property {
	props := o.ViewModelInstanceValue.Properties()
	if o.PropertyValue != ^uint64(0) {
		props = append(props, Property{Key: 846, Type: PropertyTypeUint, Value: o.PropertyValue})
	}
	return props
}

// ViewModelInstanceAsset (typeKey: 586)
type ViewModelInstanceAsset struct {
	ViewModelInstanceValue
	PropertyValue uint64 `rive:"824,uint"`
}

func (o *ViewModelInstanceAsset) TypeKey() uint32 { return 586 }

func (o *ViewModelInstanceAsset) Properties() []Property {
	props := o.ViewModelInstanceValue.Properties()
	if o.PropertyValue != ^uint64(0) {
		props = append(props, Property{Key: 824, Type: PropertyTypeUint, Value: o.PropertyValue})
	}
	return props
}

// ViewModelInstanceAssetImage (typeKey: 587)
type ViewModelInstanceAssetImage struct {
	ViewModelInstanceAsset
}

func (o *ViewModelInstanceAssetImage) TypeKey() uint32 { return 587 }

func (o *ViewModelInstanceAssetImage) Properties() []Property {
	return o.ViewModelInstanceAsset.Properties()
}

// ViewModelInstanceBoolean (typeKey: 449)
type ViewModelInstanceBoolean struct {
	ViewModelInstanceValue
	PropertyValue bool `rive:"593,bool"`
}

func (o *ViewModelInstanceBoolean) TypeKey() uint32 { return 449 }

func (o *ViewModelInstanceBoolean) Properties() []Property {
	props := o.ViewModelInstanceValue.Properties()
	if o.PropertyValue {
		props = append(props, Property{Key: 593, Type: PropertyTypeUint, Value: boolToUint64(o.PropertyValue)})
	}
	return props
}

// ViewModelInstanceColor (typeKey: 426)
type ViewModelInstanceColor struct {
	ViewModelInstanceValue
	PropertyValue uint32 `rive:"555,color"`
}

func (o *ViewModelInstanceColor) TypeKey() uint32 { return 426 }

func (o *ViewModelInstanceColor) Properties() []Property {
	props := o.ViewModelInstanceValue.Properties()
	if o.PropertyValue != 0 {
		props = append(props, Property{Key: 555, Type: PropertyTypeColor, Value: uint64(o.PropertyValue)})
	}
	return props
}

// ViewModelInstanceEnum (typeKey: 432)
type ViewModelInstanceEnum struct {
	ViewModelInstanceValue
	PropertyValue uint64 `rive:"560,uint"`
}

func (o *ViewModelInstanceEnum) TypeKey() uint32 { return 432 }

func (o *ViewModelInstanceEnum) Properties() []Property {
	props := o.ViewModelInstanceValue.Properties()
	if o.PropertyValue != 0 {
		props = append(props, Property{Key: 560, Type: PropertyTypeUint, Value: o.PropertyValue})
	}
	return props
}

// ViewModelInstanceList (typeKey: 441)
type ViewModelInstanceList struct {
	ViewModelInstanceValue
	ListSource uint64 `rive:"966,uint"`
}

func (o *ViewModelInstanceList) TypeKey() uint32 { return 441 }

func (o *ViewModelInstanceList) Properties() []Property {
	props := o.ViewModelInstanceValue.Properties()
	if o.ListSource != ^uint64(0) {
		props = append(props, Property{Key: 966, Type: PropertyTypeUint, Value: o.ListSource})
	}
	return props
}

// ViewModelInstanceListItem (typeKey: 427)
type ViewModelInstanceListItem struct {
	ViewModelId         uint64 `rive:"549,uint"`
	ViewModelInstanceId uint64 `rive:"550,uint"`
}

func (o *ViewModelInstanceListItem) TypeKey() uint32 { return 427 }

func (o *ViewModelInstanceListItem) Properties() []Property {
	var props []Property
	if o.ViewModelId != ^uint64(0) {
		props = append(props, Property{Key: 549, Type: PropertyTypeUint, Value: o.ViewModelId})
	}
	if o.ViewModelInstanceId != ^uint64(0) {
		props = append(props, Property{Key: 550, Type: PropertyTypeUint, Value: o.ViewModelInstanceId})
	}
	return props
}

// ViewModelInstanceNumber (typeKey: 442)
type ViewModelInstanceNumber struct {
	ViewModelInstanceValue
	PropertyValue float64 `rive:"575,float"`
}

func (o *ViewModelInstanceNumber) TypeKey() uint32 { return 442 }

func (o *ViewModelInstanceNumber) Properties() []Property {
	props := o.ViewModelInstanceValue.Properties()
	if o.PropertyValue != 0 {
		props = append(props, Property{Key: 575, Type: PropertyTypeFloat, Value: o.PropertyValue})
	}
	return props
}

// ViewModelInstanceString (typeKey: 433)
type ViewModelInstanceString struct {
	ViewModelInstanceValue
	PropertyValue string `rive:"561,string"`
}

func (o *ViewModelInstanceString) TypeKey() uint32 { return 433 }

func (o *ViewModelInstanceString) Properties() []Property {
	props := o.ViewModelInstanceValue.Properties()
	if o.PropertyValue != "" {
		props = append(props, Property{Key: 561, Type: PropertyTypeString, Value: o.PropertyValue})
	}
	return props
}

// ViewModelInstanceSymbol (typeKey: 565) [abstract]
type ViewModelInstanceSymbol struct {
	ViewModelInstanceValue
}

func (o *ViewModelInstanceSymbol) Properties() []Property {
	return o.ViewModelInstanceValue.Properties()
}

// ViewModelInstanceSymbolListIndex (typeKey: 566)
type ViewModelInstanceSymbolListIndex struct {
	ViewModelInstanceSymbol
	PropertyValue uint64 `rive:"814,uint"`
}

func (o *ViewModelInstanceSymbolListIndex) TypeKey() uint32 { return 566 }

func (o *ViewModelInstanceSymbolListIndex) Properties() []Property {
	props := o.ViewModelInstanceSymbol.Properties()
	if o.PropertyValue != 0 {
		props = append(props, Property{Key: 814, Type: PropertyTypeUint, Value: o.PropertyValue})
	}
	return props
}

// ViewModelInstanceTrigger (typeKey: 501)
type ViewModelInstanceTrigger struct {
	ViewModelInstanceValue
	PropertyValue uint64 `rive:"687,uint"`
}

func (o *ViewModelInstanceTrigger) TypeKey() uint32 { return 501 }

func (o *ViewModelInstanceTrigger) Properties() []Property {
	props := o.ViewModelInstanceValue.Properties()
	if o.PropertyValue != 0 {
		props = append(props, Property{Key: 687, Type: PropertyTypeUint, Value: o.PropertyValue})
	}
	return props
}

// ViewModelInstanceValue (typeKey: 428)
type ViewModelInstanceValue struct {
	Component
	ViewModelPropertyId uint64 `rive:"554,uint"`
}

func (o *ViewModelInstanceValue) TypeKey() uint32 { return 428 }

func (o *ViewModelInstanceValue) Properties() []Property {
	props := o.Component.Properties()
	if o.ViewModelPropertyId != 0 {
		props = append(props, Property{Key: 554, Type: PropertyTypeUint, Value: o.ViewModelPropertyId})
	}
	return props
}

// ViewModelInstanceViewModel (typeKey: 444)
type ViewModelInstanceViewModel struct {
	ViewModelInstanceValue
	PropertyValue uint64 `rive:"577,uint"`
}

func (o *ViewModelInstanceViewModel) TypeKey() uint32 { return 444 }

func (o *ViewModelInstanceViewModel) Properties() []Property {
	props := o.ViewModelInstanceValue.Properties()
	if o.PropertyValue != 0 {
		props = append(props, Property{Key: 577, Type: PropertyTypeUint, Value: o.PropertyValue})
	}
	return props
}

// ViewModelProperty (typeKey: 430)
type ViewModelProperty struct {
	ViewModelComponent
	SymbolTypeValue uint64 `rive:"875,uint"`
	ComponentProps  uint64 `rive:"957,uint"`
}

func (o *ViewModelProperty) TypeKey() uint32 { return 430 }

func (o *ViewModelProperty) Properties() []Property {
	props := o.ViewModelComponent.Properties()
	if o.SymbolTypeValue != 0 {
		props = append(props, Property{Key: 875, Type: PropertyTypeUint, Value: o.SymbolTypeValue})
	}
	if o.ComponentProps != 0 {
		props = append(props, Property{Key: 957, Type: PropertyTypeUint, Value: o.ComponentProps})
	}
	return props
}

// ViewModelPropertyArtboard (typeKey: 598)
type ViewModelPropertyArtboard struct {
	ViewModelProperty
}

func (o *ViewModelPropertyArtboard) TypeKey() uint32 { return 598 }

func (o *ViewModelPropertyArtboard) Properties() []Property {
	return o.ViewModelProperty.Properties()
}

// ViewModelPropertyAsset (typeKey: 584)
type ViewModelPropertyAsset struct {
	ViewModelProperty
}

func (o *ViewModelPropertyAsset) TypeKey() uint32 { return 584 }

func (o *ViewModelPropertyAsset) Properties() []Property {
	return o.ViewModelProperty.Properties()
}

// ViewModelPropertyAssetImage (typeKey: 585)
type ViewModelPropertyAssetImage struct {
	ViewModelPropertyAsset
}

func (o *ViewModelPropertyAssetImage) TypeKey() uint32 { return 585 }

func (o *ViewModelPropertyAssetImage) Properties() []Property {
	return o.ViewModelPropertyAsset.Properties()
}

// ViewModelPropertyBoolean (typeKey: 448)
type ViewModelPropertyBoolean struct {
	ViewModelProperty
}

func (o *ViewModelPropertyBoolean) TypeKey() uint32 { return 448 }

func (o *ViewModelPropertyBoolean) Properties() []Property {
	return o.ViewModelProperty.Properties()
}

// ViewModelPropertyColor (typeKey: 440)
type ViewModelPropertyColor struct {
	ViewModelProperty
}

func (o *ViewModelPropertyColor) TypeKey() uint32 { return 440 }

func (o *ViewModelPropertyColor) Properties() []Property {
	return o.ViewModelProperty.Properties()
}

// ViewModelPropertyEnum (typeKey: 509)
type ViewModelPropertyEnum struct {
	ViewModelProperty
}

func (o *ViewModelPropertyEnum) TypeKey() uint32 { return 509 }

func (o *ViewModelPropertyEnum) Properties() []Property {
	return o.ViewModelProperty.Properties()
}

// ViewModelPropertyEnumCustom (typeKey: 439)
type ViewModelPropertyEnumCustom struct {
	ViewModelPropertyEnum
	EnumId uint64 `rive:"574,uint"`
}

func (o *ViewModelPropertyEnumCustom) TypeKey() uint32 { return 439 }

func (o *ViewModelPropertyEnumCustom) Properties() []Property {
	props := o.ViewModelPropertyEnum.Properties()
	if o.EnumId != ^uint64(0) {
		props = append(props, Property{Key: 574, Type: PropertyTypeUint, Value: o.EnumId})
	}
	return props
}

// ViewModelPropertyEnumSystem (typeKey: 511)
type ViewModelPropertyEnumSystem struct {
	ViewModelPropertyEnum
	EnumType uint64 `rive:"708,uint"`
}

func (o *ViewModelPropertyEnumSystem) TypeKey() uint32 { return 511 }

func (o *ViewModelPropertyEnumSystem) Properties() []Property {
	props := o.ViewModelPropertyEnum.Properties()
	if o.EnumType != 0 {
		props = append(props, Property{Key: 708, Type: PropertyTypeUint, Value: o.EnumType})
	}
	return props
}

// ViewModelPropertyList (typeKey: 434)
type ViewModelPropertyList struct {
	ViewModelProperty
}

func (o *ViewModelPropertyList) TypeKey() uint32 { return 434 }

func (o *ViewModelPropertyList) Properties() []Property {
	return o.ViewModelProperty.Properties()
}

// ViewModelPropertyNumber (typeKey: 431)
type ViewModelPropertyNumber struct {
	ViewModelProperty
}

func (o *ViewModelPropertyNumber) TypeKey() uint32 { return 431 }

func (o *ViewModelPropertyNumber) Properties() []Property {
	return o.ViewModelProperty.Properties()
}

// ViewModelPropertyString (typeKey: 443)
type ViewModelPropertyString struct {
	ViewModelProperty
}

func (o *ViewModelPropertyString) TypeKey() uint32 { return 443 }

func (o *ViewModelPropertyString) Properties() []Property {
	return o.ViewModelProperty.Properties()
}

// ViewModelPropertySymbol (typeKey: 563) [abstract]
type ViewModelPropertySymbol struct {
	ViewModelProperty
}

func (o *ViewModelPropertySymbol) Properties() []Property {
	return o.ViewModelProperty.Properties()
}

// ViewModelPropertySymbolListIndex (typeKey: 564)
type ViewModelPropertySymbolListIndex struct {
	ViewModelPropertySymbol
}

func (o *ViewModelPropertySymbolListIndex) TypeKey() uint32 { return 564 }

func (o *ViewModelPropertySymbolListIndex) Properties() []Property {
	return o.ViewModelPropertySymbol.Properties()
}

// ViewModelPropertyTrigger (typeKey: 502)
type ViewModelPropertyTrigger struct {
	ViewModelProperty
}

func (o *ViewModelPropertyTrigger) TypeKey() uint32 { return 502 }

func (o *ViewModelPropertyTrigger) Properties() []Property {
	return o.ViewModelProperty.Properties()
}

// ViewModelPropertyViewModel (typeKey: 436)
type ViewModelPropertyViewModel struct {
	ViewModelProperty
	ViewModelReferenceId uint64 `rive:"565,uint"`
}

func (o *ViewModelPropertyViewModel) TypeKey() uint32 { return 436 }

func (o *ViewModelPropertyViewModel) Properties() []Property {
	props := o.ViewModelProperty.Properties()
	if o.ViewModelReferenceId != 0 {
		props = append(props, Property{Key: 565, Type: PropertyTypeUint, Value: o.ViewModelReferenceId})
	}
	return props
}
