// Code generated by rivegen. DO NOT EDIT.
package rive

// SemanticData (typeKey: 668)
type SemanticData struct {
	Component
	Role         uint64 `rive:"982,uint"`
	Label        string `rive:"983,string"`
	Value        string `rive:"984,string"`
	Hint         string `rive:"985,string"`
	HeadingLevel uint64 `rive:"986,uint"`
	TraitFlags   uint64 `rive:"987,uint"`
	StateFlags   uint64 `rive:"988,uint"`
	IsExpandable bool   `rive:"989,bool"`
	IsSelectable bool   `rive:"990,bool"`
	IsCheckable  bool   `rive:"991,bool"`
	IsToggleable bool   `rive:"992,bool"`
	IsRequirable bool   `rive:"993,bool"`
	IsEnablable  bool   `rive:"994,bool"`
	IsFocusable  bool   `rive:"995,bool"`
	IsExpanded   bool   `rive:"996,bool"`
	IsSelected   bool   `rive:"997,bool"`
	IsChecked    bool   `rive:"998,bool"`
	IsMixed      bool   `rive:"999,bool"`
	IsToggled    bool   `rive:"1000,bool"`
	IsRequired   bool   `rive:"1001,bool"`
	IsDisabled   bool   `rive:"1002,bool"`
	IsFocused    bool   `rive:"1003,bool"`
	IsHidden     bool   `rive:"1004,bool"`
	IsLiveRegion bool   `rive:"1005,bool"`
	IsReadOnly   bool   `rive:"1006,bool"`
	IsModal      bool   `rive:"1007,bool"`
	IsObscured   bool   `rive:"1008,bool"`
	IsMultiline  bool   `rive:"1009,bool"`
}

func (o *SemanticData) TypeKey() uint32 { return 668 }

func (o *SemanticData) Properties() []Property {
	props := o.Component.Properties()
	if o.Role != 0 {
		props = append(props, Property{Key: 982, Type: PropertyTypeUint, Value: o.Role})
	}
	if o.Label != "" {
		props = append(props, Property{Key: 983, Type: PropertyTypeString, Value: o.Label})
	}
	if o.Value != "" {
		props = append(props, Property{Key: 984, Type: PropertyTypeString, Value: o.Value})
	}
	if o.Hint != "" {
		props = append(props, Property{Key: 985, Type: PropertyTypeString, Value: o.Hint})
	}
	if o.HeadingLevel != 0 {
		props = append(props, Property{Key: 986, Type: PropertyTypeUint, Value: o.HeadingLevel})
	}
	if o.TraitFlags != 0 {
		props = append(props, Property{Key: 987, Type: PropertyTypeUint, Value: o.TraitFlags})
	}
	if o.StateFlags != 0 {
		props = append(props, Property{Key: 988, Type: PropertyTypeUint, Value: o.StateFlags})
	}
	if o.IsExpandable {
		props = append(props, Property{Key: 989, Type: PropertyTypeUint, Value: boolToUint64(o.IsExpandable)})
	}
	if o.IsSelectable {
		props = append(props, Property{Key: 990, Type: PropertyTypeUint, Value: boolToUint64(o.IsSelectable)})
	}
	if o.IsCheckable {
		props = append(props, Property{Key: 991, Type: PropertyTypeUint, Value: boolToUint64(o.IsCheckable)})
	}
	if o.IsToggleable {
		props = append(props, Property{Key: 992, Type: PropertyTypeUint, Value: boolToUint64(o.IsToggleable)})
	}
	if o.IsRequirable {
		props = append(props, Property{Key: 993, Type: PropertyTypeUint, Value: boolToUint64(o.IsRequirable)})
	}
	if o.IsEnablable {
		props = append(props, Property{Key: 994, Type: PropertyTypeUint, Value: boolToUint64(o.IsEnablable)})
	}
	if o.IsFocusable {
		props = append(props, Property{Key: 995, Type: PropertyTypeUint, Value: boolToUint64(o.IsFocusable)})
	}
	if o.IsExpanded {
		props = append(props, Property{Key: 996, Type: PropertyTypeUint, Value: boolToUint64(o.IsExpanded)})
	}
	if o.IsSelected {
		props = append(props, Property{Key: 997, Type: PropertyTypeUint, Value: boolToUint64(o.IsSelected)})
	}
	if o.IsChecked {
		props = append(props, Property{Key: 998, Type: PropertyTypeUint, Value: boolToUint64(o.IsChecked)})
	}
	if o.IsMixed {
		props = append(props, Property{Key: 999, Type: PropertyTypeUint, Value: boolToUint64(o.IsMixed)})
	}
	if o.IsToggled {
		props = append(props, Property{Key: 1000, Type: PropertyTypeUint, Value: boolToUint64(o.IsToggled)})
	}
	if o.IsRequired {
		props = append(props, Property{Key: 1001, Type: PropertyTypeUint, Value: boolToUint64(o.IsRequired)})
	}
	if o.IsDisabled {
		props = append(props, Property{Key: 1002, Type: PropertyTypeUint, Value: boolToUint64(o.IsDisabled)})
	}
	if o.IsFocused {
		props = append(props, Property{Key: 1003, Type: PropertyTypeUint, Value: boolToUint64(o.IsFocused)})
	}
	if o.IsHidden {
		props = append(props, Property{Key: 1004, Type: PropertyTypeUint, Value: boolToUint64(o.IsHidden)})
	}
	if o.IsLiveRegion {
		props = append(props, Property{Key: 1005, Type: PropertyTypeUint, Value: boolToUint64(o.IsLiveRegion)})
	}
	if o.IsReadOnly {
		props = append(props, Property{Key: 1006, Type: PropertyTypeUint, Value: boolToUint64(o.IsReadOnly)})
	}
	if o.IsModal {
		props = append(props, Property{Key: 1007, Type: PropertyTypeUint, Value: boolToUint64(o.IsModal)})
	}
	if o.IsObscured {
		props = append(props, Property{Key: 1008, Type: PropertyTypeUint, Value: boolToUint64(o.IsObscured)})
	}
	if o.IsMultiline {
		props = append(props, Property{Key: 1009, Type: PropertyTypeUint, Value: boolToUint64(o.IsMultiline)})
	}
	return props
}
