package main

// generateFormatRules reads format_contract.json and emits gen_format_rules.go.
// Invoked when the -contract flag is passed to rivegen.

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// ── contract JSON types ───────────────────────────────────────────────────────

type contractInput struct {
	EmissionOrder emissionOrderInput         `json:"emission_order"`
	TocRules      tocRulesInput              `json:"toc_rules"`
	Defaults      map[string]defaultInput    `json:"defaults"`
	ParentIdRules map[string]parentIdInput   `json:"parent_id_rules"`
	TypeRegistry  map[string]string          `json:"type_registry"`
}

type emissionOrderInput struct {
	TypePhasePriority map[string]phasePriorityInput `json:"type_phase_priority"`
}

type phasePriorityInput struct {
	Phase    string `json:"phase"`
	Priority int    `json:"priority"`
}

type tocRulesInput struct {
	IncludeKeys map[string]tocKeyInput `json:"include_keys"`
}

type tocKeyInput struct {
	FieldIndex int `json:"field_index"`
}

type defaultInput struct {
	Name        string      `json:"name"`
	Type        string      `json:"type"`
	RiveDefault interface{} `json:"rive_default"`
	Mismatch    bool        `json:"mismatch"`
}

type parentIdInput struct {
	HasParentId bool   `json:"has_parent_id"`
	RelativeTo  string `json:"relative_to"`
}

// ── Phase string → Go constant name ──────────────────────────────────────────

var phaseConst = map[string]string{
	"global":        "PhaseGlobal",
	"artboard":      "PhaseArtboard",
	"children":      "PhaseChildren",
	"paint":         "PhasePaint",
	"animation":     "PhaseAnimation",
	"state_machine": "PhaseStateMachine",
}

// ── Entry point ───────────────────────────────────────────────────────────────

func generateFormatRules(contractPath, outDir string) error {
	data, err := os.ReadFile(contractPath)
	if err != nil {
		return fmt.Errorf("read %s: %w", contractPath, err)
	}
	var contract contractInput
	if err := json.Unmarshal(data, &contract); err != nil {
		return fmt.Errorf("parse %s: %w", contractPath, err)
	}

	src, err := renderFormatRules(contract, contractPath)
	if err != nil {
		return fmt.Errorf("render: %w", err)
	}

	outPath := filepath.Join(outDir, "gen_format_rules.go")
	if err := os.WriteFile(outPath, src, 0644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}
	return nil
}

// ── Code renderer ─────────────────────────────────────────────────────────────

func renderFormatRules(c contractInput, contractPath string) ([]byte, error) {
	var b bytes.Buffer

	// header
	fmt.Fprintf(&b, "// Code generated by rivegen -contract %s. DO NOT EDIT.\n", filepath.Base(contractPath))
	fmt.Fprintf(&b, "package rive\n\n")

	// EmissionPhase type + constants
	writeEmissionPhase(&b)

	// TypePhase map
	writeTypePhase(&b, c.EmissionOrder.TypePhasePriority)

	// ToCIncludeKeys map
	writeToCIncludeKeys(&b, c.TocRules.IncludeKeys)

	// RiveDefault map (mismatch-only)
	writeRiveDefault(&b, c.Defaults)

	// RiveDefaultMismatch slice
	writeRiveDefaultMismatch(&b, c.Defaults)

	// ParentIdRule struct + ParentIdRules map
	writeParentIdRules(&b, c.ParentIdRules)

	return format.Source(b.Bytes())
}

func writeEmissionPhase(b *bytes.Buffer) {
	fmt.Fprintf(b, `// EmissionPhase classifies where in the object stream a type belongs.
type EmissionPhase int

const (
	PhaseGlobal       EmissionPhase = iota // Before any Artboard (Backboard, FontAsset pairs)
	PhaseArtboard                           // The Artboard itself
	PhaseChildren                           // Artboard children (shapes, text, nodes)
	PhasePaint                              // Fill/Stroke/SolidColor/Gradient
	PhaseAnimation                          // LinearAnimation + keyframes
	PhaseStateMachine                       // StateMachine + layers + states + transitions
)

// TypePhaseInfo holds phase classification for a typeKey.
type TypePhaseInfo struct {
	Phase    EmissionPhase
	Priority int
}

`)
}

func writeTypePhase(b *bytes.Buffer, pp map[string]phasePriorityInput) {
	fmt.Fprintf(b, "// TypePhase maps typeKey → emission phase and priority within that phase.\n")
	fmt.Fprintf(b, "// Derived from official Rive test assets via rivtool analyze.\n")
	fmt.Fprintf(b, "var TypePhase = map[uint32]TypePhaseInfo{\n")

	// Sort by typeKey for determinism
	var keys []int
	for k := range pp {
		ki, _ := strconv.Atoi(k)
		keys = append(keys, ki)
	}
	sort.Ints(keys)

	for _, ki := range keys {
		ks := strconv.Itoa(ki)
		entry := pp[ks]
		phase, ok := phaseConst[entry.Phase]
		if !ok {
			phase = "PhaseChildren" // fallback
		}
		fmt.Fprintf(b, "\t%d: {%s, %d},\n", ki, phase, entry.Priority)
	}
	fmt.Fprintf(b, "}\n\n")
}

func writeToCIncludeKeys(b *bytes.Buffer, includeKeys map[string]tocKeyInput) {
	fmt.Fprintf(b, "// ToCIncludeKeys maps property key → field index in the ToC bit-pack.\n")
	fmt.Fprintf(b, "// Keys present here must appear in every .riv file's Table of Contents.\n")
	fmt.Fprintf(b, "// Keys absent from this set are CoreRegistry-known and must be excluded from the ToC.\n")
	fmt.Fprintf(b, "// Field indices: 0=uint, 1=string/bytes, 2=float, 3=color.\n")
	fmt.Fprintf(b, "var ToCIncludeKeys = map[uint32]uint32{\n")

	var keys []int
	for k := range includeKeys {
		ki, _ := strconv.Atoi(k)
		keys = append(keys, ki)
	}
	sort.Ints(keys)

	for _, ki := range keys {
		ks := strconv.Itoa(ki)
		fi := includeKeys[ks].FieldIndex
		fmt.Fprintf(b, "\t%d: %d,\n", ki, fi)
	}
	fmt.Fprintf(b, "}\n\n")
}

func writeRiveDefault(b *bytes.Buffer, defaults map[string]defaultInput) {
	fmt.Fprintf(b, "// RiveDefault maps property key → Rive runtime default value.\n")
	fmt.Fprintf(b, "// Only contains entries where rive_default differs from Go's zero value (mismatch=true).\n")
	fmt.Fprintf(b, "// Properties at their RiveDefault MUST be omitted from the binary stream.\n")
	fmt.Fprintf(b, "// Properties at Go's zero value that differ from RiveDefault MUST be emitted.\n")
	fmt.Fprintf(b, "var RiveDefault = map[uint32]interface{}{\n")

	var keys []int
	for k, v := range defaults {
		if !v.Mismatch {
			continue
		}
		ki, _ := strconv.Atoi(k)
		keys = append(keys, ki)
	}
	sort.Ints(keys)

	for _, ki := range keys {
		ks := strconv.Itoa(ki)
		v := defaults[ks]
		lit, err := goLiteral(v.Type, v.RiveDefault)
		if err != nil {
			continue // skip unparseable
		}
		comment := v.Name
		if comment == "" {
			comment = "k" + ks
		}
		fmt.Fprintf(b, "\t%d: %s, // %s\n", ki, lit, comment)
	}
	fmt.Fprintf(b, "}\n\n")
}

func writeRiveDefaultMismatch(b *bytes.Buffer, defaults map[string]defaultInput) {
	fmt.Fprintf(b, "// RiveDefaultMismatch lists property keys where Go zero ≠ Rive runtime default.\n")
	fmt.Fprintf(b, "// Struct fields at these keys must be initialized explicitly in constructors.\n")
	fmt.Fprintf(b, "var RiveDefaultMismatch = []uint32{\n")

	var keys []int
	for k, v := range defaults {
		if !v.Mismatch {
			continue
		}
		ki, _ := strconv.Atoi(k)
		keys = append(keys, ki)
	}
	sort.Ints(keys)

	for _, ki := range keys {
		fmt.Fprintf(b, "\t%d,\n", ki)
	}
	fmt.Fprintf(b, "}\n\n")
}

func writeParentIdRules(b *bytes.Buffer, rules map[string]parentIdInput) {
	fmt.Fprintf(b, "// FormatParentIdRule describes parentId semantics for a typeKey.\n")
	fmt.Fprintf(b, "type FormatParentIdRule struct {\n")
	fmt.Fprintf(b, "\tHasParentId bool\n")
	fmt.Fprintf(b, "\tRelativeTo  string // \"artboard\" for artboard-relative parentId, \"\" otherwise\n")
	fmt.Fprintf(b, "}\n\n")

	fmt.Fprintf(b, "// FormatParentIdRules maps typeKey → parentId rule derived from official .riv assets.\n")
	fmt.Fprintf(b, "var FormatParentIdRules = map[uint32]FormatParentIdRule{\n")

	var keys []int
	for k := range rules {
		ki, _ := strconv.Atoi(k)
		keys = append(keys, ki)
	}
	sort.Ints(keys)

	for _, ki := range keys {
		ks := strconv.Itoa(ki)
		r := rules[ks]
		if r.HasParentId {
			fmt.Fprintf(b, "\t%d: {HasParentId: true, RelativeTo: %q},\n", ki, r.RelativeTo)
		} else {
			fmt.Fprintf(b, "\t%d: {HasParentId: false},\n", ki)
		}
	}
	fmt.Fprintf(b, "}\n")
}

// ── Value formatting ──────────────────────────────────────────────────────────

// goLiteral converts a JSON-decoded interface{} value (from format_contract.json)
// to the appropriate Go literal string for the given normalized type.
func goLiteral(normType string, val interface{}) (string, error) {
	switch normType {
	case "float":
		f := toFloat64(val)
		// Format as float64 literal
		if f == float64(int64(f)) {
			return fmt.Sprintf("float64(%d)", int64(f)), nil
		}
		return fmt.Sprintf("float64(%g)", f), nil

	case "uint":
		u := uint64(toFloat64(val))
		if u == ^uint64(0) {
			return "^uint64(0)", nil
		}
		return fmt.Sprintf("uint64(%d)", u), nil

	case "color":
		u := uint64(toFloat64(val))
		return fmt.Sprintf("uint64(0x%08X)", u), nil

	case "bool":
		if b, ok := val.(bool); ok {
			if b {
				return "true", nil
			}
			return "false", nil
		}
		return "", fmt.Errorf("expected bool, got %T", val)

	case "string":
		if s, ok := val.(string); ok {
			return fmt.Sprintf("%q", s), nil
		}
		return "", fmt.Errorf("expected string, got %T", val)

	case "bytes":
		return "([]byte)(nil)", nil
	}
	return "", fmt.Errorf("unhandled type %q", normType)
}

func toFloat64(v interface{}) float64 {
	switch x := v.(type) {
	case float64:
		return x
	case int:
		return float64(x)
	case int64:
		return float64(x)
	case uint64:
		return float64(x)
	}
	return 0
}

// ── String deduplication helper ───────────────────────────────────────────────

func dedupSortedStrings(in []string) []string {
	if len(in) == 0 {
		return nil
	}
	out := []string{in[0]}
	for _, s := range in[1:] {
		if s != out[len(out)-1] {
			out = append(out, s)
		}
	}
	return out
}

var _ = strings.TrimSpace // ensure import used
